In [1]:
list_user_agent = ['Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.90 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.16 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.5672.63 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.5672.24 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.5615.49 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.5615.28 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.5563.64 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.5563.41 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.5563.19 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.5481.77 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.5481.30 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.5414.74 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.5414.25 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.5359.71 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.5359.22 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.5304.62 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.5304.18 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.5249.61 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.5249.21 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.5195.52 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.5195.19 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.79 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.29 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.20 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.24 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.27 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.15 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.20 Safari/537.36']

# = = = = = = = = = = = = = = = = = =

from gevent import monkey
monkey.patch_all()
from gevent.queue import Queue
import gevent

# = = = = = = = = = = = = = = = = = =

import pandas as pd
from selenium.webdriver import ChromeOptions
import random

option = ChromeOptions()
option.add_experimental_option('useAutomationExtension', False)
option.add_argument('blink-settings=imagesEnabled=false')
option.add_argument('--disable-blink-features=AutomationControlled')
option.add_argument('--disable-dev-shm-usage')
option.add_argument('--disable-gpu')
option.add_experimental_option('excludeSwitches', ['enable-automation'])
option.add_argument('--headless')
option.add_argument('--no-sandbox')
option.add_argument('--proxy-server=http://u431.kdltps.com:15818')
option.add_argument('user-agent=' + random.choice(list_user_agent))
option.page_load_strategy = 'eager'

from selenium.webdriver import Chrome
from selenium.webdriver.chrome.service import Service
import time
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

C:\Users\YangTeng\Desktop\venv\lib\site-packages\gevent\hub.py:161: UserWarning: libuv only supports millisecond timer resolution; all times less will be set to 1 ms
  with loop.timer(seconds, ref=ref) as t:

In [2]:
df_menu = pd.read_excel(r'C:\Users\YangTeng\Desktop\数据源\01、RockAuto\RockAuto_OE_处理.xlsx', header=0)
OE = df_menu['OE No.']

OE = OE.fillna(0)

No = df_menu['No.']

for k in range(len(OE)):
    OE[k] = str(OE[k]).split(';')


Dorman = df_menu['Dorman_part']

Dorman = Dorman.fillna(0)

print('总数量：' + str(len(OE)))
print()

总数量：577

C:\Users\YangTeng\Desktop\venv\lib\site-packages\gevent\hub.py:161: UserWarning: libuv only supports millisecond timer resolution; all times less will be set to 1 ms
  with loop.timer(seconds, ref=ref) as t:

In [3]:
def detail( index ):
    
    global df_temp
    
    for _ in range(1):
        try:
    
            Part_Number_part = browser.find_elements(By.XPATH,'//span[@title="Buyer\'s Guide"]')[index].text
            
            # 
            list_part = browser.find_elements(by=By.XPATH, value='//tbody[@class="listing-inner altrow-a-1  "]') + browser.find_elements(by=By.XPATH, value='//tbody[@class="listing-inner altrow-a-0  "]')
            
            list_part_number = [part.find_element(by=By.XPATH, value='./descendant::div[@class="listing-text-row-moreinfo-truck"]/span[@title="Buyer\'s Guide"]') for part in list_part]
            
            list_part_number
            
            part_index = [part_number.text for part_number in list_part_number].index(Part_Number_part)
            
            part_index
            
            manufacturer = manufacturer_list[index]
            
            # 
            browser.find_elements(By.XPATH,'//span[@title="Buyer\'s Guide"]')[index].click()
            
            time.sleep(5)
            
            list_vehicle = browser.find_element(by=By.XPATH, value='//div[@id="buyersguidepopup-outer_c"]').find_elements(by=By.XPATH, value='./descendant::table[@class="nobmp"]')
            if len(list_vehicle) == 0:
                vehicle = ''
            else:
                vehicle = list_vehicle[0].text
            
                vehicle
            
            # part_index = [part_number.find_element(By.XPATH,'//span[@class="span-link-underline-remover"]').text for part_number in list_item][Dorman_index]
            
            # note_1 = browser.find_elements(By.XPATH,'//span[@class="span-link-underline-remover"]')[Dorman_index].text
            
            note_1 = ';'.join(row.text for row in list_part[part_index].find_elements(by=By.XPATH, value='./descendant::div[@class="listing-text-row-moreinfo-truck"]/span[@class="span-link-underline-remover"]'))
            
            note_1
            
            info = ';'.join(row.get_attribute('href') for row in list_part[part_index].find_elements(by=By.XPATH, value='./descendant::div[@class="listing-text-row-moreinfo-truck"]/a[@class="ra-btn ra-btn-moreinfo"]'))
            
            note_2 = ';'.join(row.text for row in list_part[part_index].find_elements(by=By.XPATH, value='./descendant::div[@class="listing-text-row"]'))
            
            
            src = ';'.join(row.get_attribute('src') for row in list_part[part_index].find_elements(by=By.XPATH, value='./descendant::img[@class=" listing-inline-image"]'))
            
               
            oe = oe_list[index]
            
            # src = browser.find_elements(By.XPATH, './descendant::img[@class=" listing-inline-image"]')[index].get_attribute('src')
            
            status = 'ok'
            df_temp = pd.DataFrame([{'No':No[i],
                                     'Part_Number': Part_Number_part,
                                     'Manufacturer': manufacturer,
                                     'Vehicle': vehicle,
                                     'Note_1': note_1,
                                     'Info': info,
                                     'Note_2': note_2,
                                     'Alternate_OE_Part_Numbers': oe,
                                     'Src': src,
                                     'url':url,
                                     'status': 'ok'}])
            return df_temp
        
            break
        except:
            time.sleep(3)
           
            continue

In [4]:
work = Queue()
for i in range(13,16):
    work.put_nowait(i)
    
df = pd.DataFrame(columns=['No',
                           'Part_Number',
                           'Manufacturer',
                           'Vehicle',
                           'Note_1',
                           'Info',
                           'Note_2',
                           'Alternate_OE_Part_Numbers',
                           'Src',
                           'status'])
df

Empty DataFrame
Columns: [No, Part_Number, Manufacturer, Vehicle, Note_1, Info, Note_2, Alternate_OE_Part_Numbers, Src, status]
Index: []

C:\Users\YangTeng\Desktop\venv\lib\site-packages\gevent\hub.py:161: UserWarning: libuv only supports millisecond timer resolution; all times less will be set to 1 ms
  with loop.timer(seconds, ref=ref) as t:

In [5]:
def crawler():
    global df
    
    while not work.empty():
        i = work.get_nowait()
        
        status = 'error'
        
        if int(Dorman[i]) != 0:
            for _ in range(2):
                try:

                    browser = Chrome(service=Service(r'C:\Users\YangTeng\Desktop\venv\chromedriver'), options=option)
                    browser.maximize_window()

                    browser.get('https://www.rockauto.com/en/partsearch/?partnum=UF510')

                    time.sleep(3)

                    wait = WebDriverWait(browser, 60)    

                    wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="partnum_partsearch_007"]')))

                    input_OE = browser.find_element(by=By.XPATH, value='//*[@id="partnum_partsearch_007"]')

                    input_OE.clear()

                    a = str(int(Dorman[i]))

                    input_OE.send_keys(a,Keys.ENTER)

                    time.sleep(5)

                    url = browser.current_url

                    wait.until(EC.presence_of_element_located((By.XPATH, '//tbody[@class="listing-inner altrow-a-1  "]')))

                    list_part = browser.find_elements(by=By.XPATH, value='//tbody[@class="listing-inner altrow-a-1  "]') + browser.find_elements(by=By.XPATH, value='//tbody[@class="listing-inner altrow-a-0  "]')

                    list_part

                    list_part_number = [part.find_element(by=By.XPATH, value='./descendant::div[@class="listing-text-row-moreinfo-truck"]/span[@title="Buyer\'s Guide"]') for part in list_part]

                    list_part_number

                    part_index = [part_number.text for part_number in list_part_number].index(a)

                    part_index

                    manufacturer = list_part[part_index].find_element(by=By.XPATH, value='./descendant::div[@class="listing-text-row-moreinfo-truck"]/span[@class="listing-final-manufacturer "]').text

                    manufacturer

                    list_part_number[part_index].click()
                    time.sleep(5)

                    list_vehicle = browser.find_element(by=By.XPATH, value='//div[@id="buyersguidepopup-outer_c"]').find_elements(by=By.XPATH, value='./descendant::table[@class="nobmp"]')
                    if len(list_vehicle) == 0:
                        vehicle = ''
                    else:
                        vehicle = list_vehicle[0].text

                    vehicle

                    note_1 = ';'.join(row.text for row in list_part[part_index].find_elements(by=By.XPATH, value='./descendant::div[@class="listing-text-row-moreinfo-truck"]/span[@class="span-link-underline-remover"]'))

                    note_1

                    info = ';'.join(row.get_attribute('href') for row in list_part[part_index].find_elements(by=By.XPATH, value='./descendant::div[@class="listing-text-row-moreinfo-truck"]/a[@class="ra-btn ra-btn-moreinfo"]'))

                    info

                    note_2 = ';'.join(row.text for row in list_part[part_index].find_elements(by=By.XPATH, value='./descendant::div[@class="listing-text-row"]'))

                    note_2

                    oe = ';'.join(row.get_attribute('textContent') for row in list_part[part_index].find_elements(by=By.XPATH, value='./descendant::span[@title="Replaces these Alternate/ OE Part Numbers"]'))
                    oe = ';'.join(oe.split(', '))

                    oe

                    src = ';'.join(row.get_attribute('src') for row in list_part[part_index].find_elements(by=By.XPATH, value='./descendant::img[@class=" listing-inline-image"]'))

                    src
                    
                    status = 'ok'

                    df_temp = pd.DataFrame([{'No':No[i],
                                             'Part_Number': int(Dorman[i]),
                                             'Manufacturer': manufacturer,
                                             'Vehicle': vehicle,
                                             'Note_1': note_1,
                                             'Info': info,
                                             'Note_2': note_2,
                                             'Alternate_OE_Part_Numbers': oe,
                                             'Src': src,
                                             'url':url,
                                             'status': 'ok'}])



                    break
                except:
                    time.sleep(3)
             
                    continue
        else:
            if OE[i][0] == '0':
                df_temp = pd.DataFrame([{'No':No[i],
                                         'Part_Number': '',
                                         'status': '无法查询'}])
            
            else:
                for j in OE[i]:
                    
                    url = 'https://www.rockauto.com/en/partsearch/?partnum=' + j
                    
                    browser.get(url)
                
                    time.sleep(5)
                    
                    if len(browser.find_elements(by=By.XPATH, value='//span[@class="navlabellink nvoffset nnormal"]')) != 0:
                        print('No Parts Found')
                        
                        df_temp = pd.DataFrame([{'No':No[i],
                                                 'Part_Number': j,
                                                 'status': 'No Parts Found'}])

                    else:
                    
                        wait = WebDriverWait(browser, 60)    
            
                        wait.until(EC.presence_of_element_located((By.XPATH, '//*[@class="listing-container-border"]')))
            
                        items = browser.find_elements(By.XPATH,'//div[@class="listing-container-border"]')
                        
                        ###
                        if len(items) != 0:
                            
                            list_item = browser.find_elements(By.XPATH,'//div[@class="listing-text-row-moreinfo-truck"]')
                            
                            part_OE_list = []
                            
                            manufacturer_list = []
                            
                            oe_list = []
                            
                            ####
                            for item_index in range(len(list_item)):
                                
                                # note_1 = item.find_elements(By.XPATH,'//span[@class="span-link-underline-remover"]')
                                # 
                                list_part = browser.find_elements(by=By.XPATH, value='//tbody[@class="listing-inner altrow-a-1  "]') + browser.find_elements(by=By.XPATH, value='//tbody[@class="listing-inner altrow-a-0  "]')
                                # 
                                part_OE = browser.find_elements(By.XPATH,'//span[@class="listing-final-partnumber  as-link-if-js"]')[item_index].text
                                
                                part_OE_list.append(part_OE)
                                
                                manufacturer = browser.find_elements(By.XPATH,'//span[@class="listing-final-manufacturer "]')[item_index].text
                            
                                manufacturer_list.append(manufacturer)
                                
                                oe = ';'.join(row.get_attribute('textContent') for row in list_part[item_index].find_elements(by=By.XPATH, value='./descendant::span[@title="Replaces these Alternate/ OE Part Numbers"]'))
                                # oe = browser.find_elements(by=By.XPATH, value='//span[@title="Replaces these Alternate/ OE Part Numbers"]')[item_index].get_attribute('textContent')
                                
                                oe_1 = ';'.join(row for row in part_OE_list)
                                
                                oe = oe + oe_1
                                
                                oe = ';'.join(oe.split(', '))
        
                                oe_list.append(oe)
                                
                            if 'DORMAN' in manufacturer_list:
                                Dorman_index = manufacturer_list.index('DORMAN')
                                for p in OE[i]:
                                    if p in oe_list[Dorman_index]:
                            
                                        detail( Dorman_index )
                                        break
                                        
                                break
                                                               
                            ####
                            elif 'SPECTRA PREMIUM' in manufacturer_list:
                    
                                SPECTRA_PREMIUM_index = manufacturer_list.index('SPECTRA PREMIUM')
                                for p in OE[i]:
                                    if p in oe_list[SPECTRA_PREMIUM_index]:
                            
                                        detail( SPECTRA_PREMIUM_index )
                                        break
                                        
                                break
                                                             
                            ####                                           
                            else: 
                                for p in OE[i]:
                                    for z in oe_list:
                                        
                                        if p in z:
                                            oe_index = oe_list.index(z)
                                            
                                            detail( oe_index )
                                            break
                                                                                
                                    break
                                
                                break
                        else:
                            df_temp = pd.DataFrame([{'No':No[i],
                                                     'Part_Number': j,
                                                     'status': '没有结果'}])
        ####
        if status == 'error':
            df_temp = pd.DataFrame([{'No': No[i],
                                     'status': 'error'}])

        df = pd.concat([df, df_temp], ignore_index=True).fillna('')

        
        print( str(No[i]) +  '  <->  [' + status + '] - 剩余数量：' + str(work.qsize()))

In [6]:
list_task = []
for _ in range(2):
    task = gevent.spawn(crawler)
    list_task.append(task)
gevent.joinall(list_task)

Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "C:\Users\YangTeng\AppData\Local\Temp\ipykernel_21628\4172328562.py", line 118, in crawler
    browser.get(url)
UnboundLocalError: local variable 'browser' referenced before assignment
2023-08-01T05:53:36Z <Greenlet at 0x1e17b615e40: crawler> failed with UnboundLocalError

15  <->  [ok] - 剩余数量：1
16  <->  [error] - 剩余数量：0

C:\Users\YangTeng\Desktop\venv\lib\site-packages\gevent\hub.py:161: UserWarning: libuv only supports millisecond timer resolution; all times less will be set to 1 ms
  with loop.timer(seconds, ref=ref) as t:

In [7]:
df

,No,Part_Number,Manufacturer,Vehicle,Note_1,Info,Note_2,Alternate_OE_Part_Numbers,Src,status,url
0,15,573020.0,DORMAN,CHEVROLET C10 PICKUP 1982-1986\nCHEVROLET C20 ...,,https://www.rockauto.com/en/moreinfo.php?pk=12...,Category: Fuel Filler Hose,14040786,https://www.rockauto.com/info/42/573-020-007__...,ok,"https://www.rockauto.com/en/parts/dorman,57302..."
1,16,,,,,,,,,error,

C:\Users\YangTeng\Desktop\venv\lib\site-packages\gevent\hub.py:161: UserWarning: libuv only supports millisecond timer resolution; all times less will be set to 1 ms
  with loop.timer(seconds, ref=ref) as t:

In [9]:
OE[i]

['15636251']

In [13]:
int(Dorman[i]) != 0

False