In [8]:
import os
list_file = list(os.walk(r'C:\Users\YangTeng\Desktop\爬虫\12.AutotelieDIREKT\SKF-EBI\menu'))[0][2]
if '.DS_Store' in list_file:
    list_file.remove('.DS_Store')
if '0.null.txt' in list_file:
    list_file.remove('0.null.txt')
    
len(list_file)

108

In [9]:
import pandas as pd
df = pd.DataFrame()

df

Empty DataFrame
Columns: []
Index: []

In [10]:
from tqdm import tqdm
import json
for file in tqdm(list_file, desc='进度', ncols=77):
    with open('C:/Users/YangTeng/Desktop/爬虫/12.AutotelieDIREKT/SKF-EBI/menu/' + file, 'r', encoding='UTF-8') as f:
        df = pd.concat([df, pd.DataFrame(json.loads(f.read()))], ignore_index=False)
        
df = df[['brand', 'Art. Nr','Url','Scr']]

df.to_excel(r'C:\Users\YangTeng\Desktop\爬虫\12.AutotelieDIREKT\SKF-EBI\menu.xlsx', index=False)

df

进度: 100%|███████████████████████████████| 108/108 [00:00<00:00, 709.35it/s]

,brand,Art. Nr,Url,Scr
0,Radlagersatz SKF,VKBA 944,https://www.autoteiledirekt.de/skf-1363314.html,https://cdn.autoteiledirekt.de/thumb?id=136331...
1,Radlagersatz SKF,VKBA 3717,https://www.autoteiledirekt.de/skf-1362803.html,https://cdn.autoteiledirekt.de/thumb?id=136280...
2,Radlagersatz SKF,VKBA 3716,https://www.autoteiledirekt.de/skf-1362802.html,https://cdn.autoteiledirekt.de/thumb?id=136280...
3,Radlagersatz SKF,VKBA 1931,https://www.autoteiledirekt.de/skf-1362413.html,https://cdn.autoteiledirekt.de/thumb?id=136241...
4,Radlagersatz SKF,VKBA 1927,https://www.autoteiledirekt.de/skf-1362409.html,https://cdn.autoteiledirekt.de/thumb?id=136240...
...,...,...,...,...
10,Radlagersatz SKF,VKBA 5038,https://www.autoteiledirekt.de/skf-18387.html,https://cdn.autoteiledirekt.de/thumb?id=18387&...
11,Radlagersatz SKF,VKBA 6580,https://www.autoteiledirekt.de/skf-1363008.html,https://cdn.autoteiledirekt.de/thumb?id=136300...
12,Radlagersatz SKF,VKBA 3498,None,https://cdn.autoteiledirekt.de/uploads/generic...
13,Radlagersatz SKF,VKBA 727,https://www.autoteiledirekt.de/skf-1363192.html,https://cdn.autoteiledirekt.de/thumb?id=136319...
14,Radlagersatz SKF,VKBA 3471,https://www.autoteiledirekt.de/skf-1362595.html,https://cdn.autoteiledirekt.de/uploads/generic...