In [1]:
import os
list_file = list(os.walk(r'C:\Users\YangTeng\Desktop\爬虫\12.AutotelieDIREKT\SKF-EBI\detail'))[0][2]
if '.DS_Store' in list_file:
    list_file.remove('.DS_Store')
if '0.null.txt' in list_file:
    list_file.remove('0.null.txt')
    
len(list_file)

12

In [2]:
import pandas as pd
df = pd.DataFrame()

df

Empty DataFrame
Columns: []
Index: []

In [3]:
from tqdm import tqdm
import json
for file in tqdm(list_file, desc='进度', ncols=77):
    with open('C:/Users/YangTeng/Desktop/爬虫/12.AutotelieDIREKT/SKF-EBI/detail/' + file, 'r', encoding='UTF-8') as f:
        df = pd.concat([df, pd.DataFrame(json.loads(f.read()))], ignore_index=False)

df.to_excel(r'C:\Users\YangTeng\Desktop\爬虫\12.AutotelieDIREKT\SKF-EBI\detail.xlsx', index=False)

df

进度: 100%|█████████████████████████████████| 12/12 [00:00<00:00, 247.75it/s]

,Title,Specification,Price,OE,Vehicle,make,Pic,Url,Src,innendurchmesser [mm]:,...,BLUE PRINT,DR!VE+,GSP,METZGER,TRISCAN,innendurchmesser 2 [mm]:,breite 2 [mm]:,breite 1 [mm]:,außendurchmesser 2 [mm]:,FIRST LINE
0,SKF VKBA 6732 Radlagersatz,71 mm,"48,24 €",GENERAL MOTORS / OPEL - OE-13584680;OPEL - OE-...,OPEL Karl (C16) (Baujahr 01.2015 - ...)\nVAUXH...,OPEL\nVAUXHALL\n,https://www.autoteiledirekt.de/skf-12272917.ht...,https://www.autoteiledirekt.de/skf-12272917.ht...,https://cdn.autoteiledirekt.de/thumb?id=122729...,38,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,SKF VKBA 3605 Radlagersatz,82 mm,"38,24 €",AUDI / AUDI (FAW) / VW / VW (SVW) - OE-4D0 407...,AUDI A4 B6 Limousine (8E2) (Baujahr 11.2000 - ...,AUDI\n,https://www.autoteiledirekt.de/skf-1362710.html,https://www.autoteiledirekt.de/skf-1362710.html,https://media.autoteiledirekt.de/360_photos/13...,43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,SKF VKBA 3605 Radlagersatz,82 mm,"38,24 €",AUDI / AUDI (FAW) / VW / VW (SVW) - OE-4D0 407...,AUDI A4 B6 Limousine (8E2) (Baujahr 11.2000 - ...,AUDI\n,https://www.autoteiledirekt.de/skf-1362710.htm...,https://www.autoteiledirekt.de/skf-1362710.htm...,https://media.autoteiledirekt.de/360_photos/13...,43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,SKF VKBA 3616 Radlagersatz,86 mm,"54,48 €",NISSAN - OE-40210-00QAF;OPEL / VAUXHALL - OE-4...,NISSAN Primastar Bus (X83) (Baujahr 03.2001 - ...,NISSAN\nOPEL\nRENAULT\nVAUXHALL\n,https://www.autoteiledirekt.de/skf-1362721.htm...,https://www.autoteiledirekt.de/skf-1362721.htm...,https://cdn.autoteiledirekt.de/thumb?id=136272...,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,SKF VKBA 3650 Radlagersatz,mit integriertem ABS-Sensor,"98,24 €",OPEL / VAUXHALL - OE-13125106;OPEL / VAUXHALL ...,OPEL Astra H Schrägheck (A04) (Baujahr 01.2004...,OPEL\nVAUXHALL\n,https://www.autoteiledirekt.de/skf-1362750.htm...,https://www.autoteiledirekt.de/skf-1362750.htm...,https://cdn.autoteiledirekt.de/thumb?id=136275...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,SKF VKBA 3782 Radlagersatz,NaN,"104,96 €",HONDA - OE-42200-SR3-A05;HONDA - OE-42200-SR3-...,"HONDA Civic V Limousine (EG, EH) (Baujahr 10.1...",HONDA\n,https://www.autoteiledirekt.de/skf-1362830.htm...,https://www.autoteiledirekt.de/skf-1362830.htm...,https://cdn.autoteiledirekt.de/thumb?id=136283...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,SKF VKBA 3786 Radlagersatz,64 mm,"24,96 €",CHEVROLET / DAEWOO - OE-94535249;CHEVROLET / D...,CHEVROLET Kalos Schrägheck (Baujahr 03.2005 - ...,CHEVROLET\nDAEWOO\n,https://www.autoteiledirekt.de/skf-1362833.htm...,https://www.autoteiledirekt.de/skf-1362833.htm...,https://media.autoteiledirekt.de/360_photos/13...,34,...,ADG08255,DP2010.10.0081,GK3256,WM 3786,"853021103, 8530 21103",NaN,NaN,NaN,NaN,NaN
0,SKF VKBA 7470 Radlagersatz,"mit Wellendichtring, 68 mm","51,24 €",HOLDEN - OE-5-09812-045-0;ISUZU - OE-8-94227-0...,"ISUZU D-Max I Pickup (TFR, TFS) (Baujahr 05.20...",ISUZU\n,https://www.autoteiledirekt.de/skf-1363229.htm...,https://www.autoteiledirekt.de/skf-1363229.htm...,https://cdn.autoteiledirekt.de/thumb?id=136322...,NaN,...,ADZ98209,NaN,NaN,NaN,NaN,"40, 45",20,19,75,NaN
0,SKF VKBA 6722 Radlagersatz,80 mm,"61,24 €",NISSAN - OE-43210-00Q0A;NISSAN - OE-43210-00Q1...,"NISSAN NV400 Kastenwagen (X62, X62B) (Baujahr ...",NISSAN\nOPEL\nRENAULT\nVAUXHALL\n,https://www.autoteiledirekt.de/skf-7017880.htm...,https://www.autoteiledirekt.de/skf-7017880.htm...,https://media.autoteiledirekt.de/360_photos/70...,45,...,ADN18385,NaN,NaN,WM 6722,NaN,NaN,NaN,NaN,NaN,NaN
0,SKF VKBA 6742 Radlagersatz,100 mm,"52,96 €",ADR - OE-59132013X;FIAT / IVECO - OE-1101597;F...,OPEL Movano B Kastenwagen (X62) (Baujahr 05.20...,OPEL\nRENAULT\nVAUXHALL\n,https://www.autoteiledirekt.de/skf-7020763.htm...,https://www.autoteiledirekt.de/skf-7020763.htm...,https://cdn.autoteiledirekt.de/thumb?id=702076...,NaN,...,ADN18383,NaN,NaN,NaN,NaN,"65, 55",23,23,90,FBK1396
0,SKF VKBA 6743 Radlagersatz,90 mm,"82,72 €",NISSAN - OE-43210-00Q0B;OPEL / VAUXHALL - OE-4...,"NISSAN NV400 Kastenwagen (X62, X62B) (Baujahr ...",NISSAN\nOPEL\nRENAULT\nVAUXHALL\n,https://www.autoteiledirekt.de/skf-7020904.htm...,https://www.autoteiledirekt.de/skf-7020904.htm...,https://cdn.autoteiledirekt.de/thumb?id=702090...,55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,SKF VKBA 7032 Radlagersatz,62 mm,"36,24 €",DACIA / RENAULT - OE-82 00 639 543;PEUGEOT (DF...,RENAULT Clio IV Schrägheck (BH) (Baujahr 11.20...,RENAULT\n,https://www.autoteiledirekt.de/skf-7487185.htm...,https://www.autoteiledirekt.de/skf-7487185.htm...,https://cdn.autoteiledirekt.de/thumb?id=748718...,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN