In [4]:
import os
list_file = list(os.walk(r'C:\Users\YangTeng\Desktop\try'))[0][2]
if '.DS_Store' in list_file:
    list_file.remove('.DS_Store')
if '0.null.txt' in list_file:
    list_file.remove('0.null.txt')
    
len(list_file)

1

In [5]:
import pandas as pd
df = pd.DataFrame()

df

Empty DataFrame
Columns: []
Index: []

In [7]:
from tqdm import tqdm
import json
for file in tqdm(list_file, desc='进度', ncols=77):
    with open('C:/Users/YangTeng/Desktop/try/' + file, 'r', encoding='UTF-8') as f:
        df = pd.concat([df, pd.DataFrame(json.loads(f.read()))], ignore_index=False)

# df.to_excel(r'C:\Users\YangTeng\Downloads\爬虫\12.AutotelieDIREKT.DE-2\item.xlsx', index=False)

df

进度: 100%|███████████████████████████████████| 1/1 [00:00<00:00, 205.07it/s]

,Title,Specification,Price,OE,Vehicle,make,Pic,Url,Src,innendurchmesser [mm]:,...,durchmesser [mm]:,breite [mm]:,zustand:,A.B.S.,DELPHI,FAG,FEBI BILSTEIN,OPTIMAL,RUVILLE,SNR
0,SKF VKBA 3581 Radlagersatz,"mit integriertem ABS-Sensor, 72 mm","34,48 €",ABARTH / ALFA ROMEO / FIAT / LANCIA - OE-46773...,CITROËN E-Méhari Cabrio (Baujahr 06.2016 - ......,CITROËN\nFIAT\n,https://www.autoteiledirekt.de/skf-1362689.html,https://www.autoteiledirekt.de/skf-1362689.html,https://cdn.autoteiledirekt.de/thumb?id=136268...,37,...,72,37,Brandneu,201458,BK1286,713 6903 50,28142,801838,5857,R158.58

In [8]:
df.to_excel(r'C:\Users\YangTeng\Desktop\try.xlsx', index=False)