In [1]:
import pandas as pd
df_menu = pd.read_excel(r'C:\Users\YangTeng\Downloads\CARID_menu.xlsx', header=0)
list_url = df_menu['Url'].to_list()

print('总数量：' + str(len(list_url)))
list_url

总数量：791

['https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm4055.html?singleid=3770807666',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9313.html?singleid=3770802651',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9353.html?singleid=3770801692',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9313.html?singleid=3770753716',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9318.html?singleid=3447406941',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9309.html?singleid=2926659524',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9242.html?singleid=2926659481',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9299.html?singleid=2926659432',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9215.html?singleid=2926658444',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm129.html?singleid=2926651525',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm2714.html?singleid=2926651481',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9310.html?singleid=2926649515',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9205.html?singleid=2926643444',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9306.html?singleid=2926642556',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9205.html?singleid=2926642554',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm138.html?singleid=2926642451',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9247.html?singleid=2926641504',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm140.html?singleid=2926641428',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9373.html?singleid=2926640538',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9243.html?singleid=2926639514',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9350.html?singleid=2926638469',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9279.html?singleid=2926636450',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9194.html?singleid=2926635487',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9208.html?singleid=2926634472',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9218.html?singleid=2926631529',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9354.html?singleid=2926629504',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9242.html?singleid=2926629441',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9285.html?singleid=2926629438',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9220.html?singleid=2926629428',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9274.html?singleid=2926626551',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm4071.html?singleid=2926625498',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9240.html?singleid=2926624553',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm2728.html?singleid=2926624519',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm136.html?singleid=2926622539',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9295.html?singleid=2926620554',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9292.html?singleid=2926616428',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9283.html?singleid=2926615506',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9215.html?singleid=2926613602',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9325.html?singleid=2926611680',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm138.html?singleid=2926608694',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9351.html?singleid=2926607697',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm129.html?singleid=2926606688',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm4035.html?singleid=2926604614',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9377.html?singleid=2926603636',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9355.html?singleid=2926600629',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9186.html?singleid=2926600596',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9252.html?singleid=2926598698',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9288.html?singleid=2926598582',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9313.html?singleid=2926597614',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9301.html?singleid=2926597600',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9204.html?singleid=2926595686',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9245.html?singleid=2926595644',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9316.html?singleid=2926591655',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9197.html?singleid=2926591594',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9182.html?singleid=2926590629',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9315.html?singleid=2926589693',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm4106.html?singleid=2926586659',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9273.html?singleid=2926586650',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9366.html?singleid=2926584652',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9296.html?singleid=2926583650',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9357.html?singleid=2926583641',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9184.html?singleid=2926582586',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9314.html?singleid=2926582578',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9324.html?singleid=2926580609',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm149.html?singleid=2926580602',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9214.html?singleid=2926579581',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm4060.html?singleid=2926578598',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9180.html?singleid=2926575603',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9269.html?singleid=2926573610',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9294.html?singleid=2926572642',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9295.html?singleid=2926570575',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm3943.html?singleid=2926569703',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9324.html?singleid=2926569653',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm4001.html?singleid=2926568669',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9254.html?singleid=2926566642',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9281.html?singleid=2926565585',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9269.html?singleid=2926563639',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9223.html?singleid=2926563572',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm140.html?singleid=2926561692',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9275.html?singleid=2926560681',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm141.html?singleid=2926559624',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9304.html?singleid=2926555577',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9380.html?singleid=2926554674',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm3799.html?singleid=2926554670',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm3787.html?singleid=2926554626',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm3340.html?singleid=2926553584',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9220.html?singleid=2926552632',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9177.html?singleid=2926552571',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm151.html?singleid=2926549629',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm4059.html?singleid=2926549598',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9298.html?singleid=2926549579',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9308.html?singleid=2926548703',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9214.html?singleid=2926547630',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm3787.html?singleid=2926547627',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm3313.html?singleid=2926546584',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9202.html?singleid=2926545664',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9380.html?singleid=2926542607',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm131.html?singleid=2926540657',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9178.html?singleid=2926539669',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9306.html?singleid=2926539615',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9358.html?singleid=2926538688',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9306.html?singleid=2926537656',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9199.html?singleid=2926536649',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9176.html?singleid=2926536622',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9276.html?singleid=2926532715',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9308.html?singleid=2926530622',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9291.html?singleid=1063353039',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9193.html?singleid=1063296116',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9379.html?singleid=834980478',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9188.html?singleid=834979516',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9200.html?singleid=834971465',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm6009.html?singleid=834968496',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9364.html?singleid=834962464',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9353.html?singleid=834961527',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9249.html?singleid=834959541',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm149.html?singleid=834959534',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9297.html?singleid=834944558',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9293.html?singleid=834943527',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm2714.html?singleid=834943525',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9317.html?singleid=834943520',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9282.html?singleid=834941532',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9199.html?singleid=834930508',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm4068.html?singleid=834927555',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9381.html?singleid=834924497',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9237.html?singleid=834915564',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm4065.html?singleid=834912570',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9290.html?singleid=834911555',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9193.html?singleid=834911488',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9201.html?singleid=834910479',
 'https://www.carid.com/vdo/hvac-blower-motor-with-wheel-mpn-pm9397.html?singleid=834910463',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-w0133-4443916-vdo.html?singleid=5370980372',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-w0133-2071299-vdo.html?singleid=5370972358',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-w0133-2071299-vdo.html?singleid=5370967488',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-w0133-2071299-vdo.html?singleid=5370964453',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-w0133-4443916-vdo.html?singleid=5123120533',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-w0133-4696454-vdo.html?singleid=5123098578',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-w0133-4696454-vdo.html?singleid=5123094542',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-w0133-1793191-vdo.html?singleid=5035493586',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-w0133-1793191-vdo.html?singleid=5035486557',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-w0133-4684889-vdo.html?singleid=5035470439',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-w0133-3005987-vdo.html?singleid=4894812753',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-w0133-1907472-vdo.html?singleid=2610328849',
 'https://www.carid.com/vdo/hvac-blower-motor-wheel-mpn-bw9302.html?singleid=4430383872',
 'https://www.carid.com/vdo/hvac-blower-motor-wheel-mpn-bw9302.html?singleid=4430377872',
 'https://www.carid.com/vdo/hvac-blower-motor-wheel-mpn-bw9302.html?singleid=4430338872',
 'https://www.carid.com/vdo/hvac-blower-motor-wheel-mpn-bw9311.html?singleid=2926657486',
 'https://www.carid.com/vdo/hvac-blower-motor-wheel-mpn-bw9319.html?singleid=2926657451',
 'https://www.carid.com/vdo/hvac-blower-motor-wheel-mpn-bw9302.html?singleid=2926654494',
 'https://www.carid.com/vdo/hvac-blower-motor-wheel-mpn-bw9328.html?singleid=2926644436',
 'https://www.carid.com/vdo/hvac-blower-motor-wheel-mpn-bw9302.html?singleid=2926641488',
 'https://www.carid.com/vdo/hvac-blower-motor-wheel-mpn-bw9303.html?singleid=2926641429',
 'https://www.carid.com/vdo/hvac-blower-motor-wheel-mpn-bw9319.html?singleid=2926634431',
 'https://www.carid.com/vdo/hvac-blower-motor-wheel-mpn-bw0307.html?singleid=2926631515',
 'https://www.carid.com/vdo/hvac-blower-motor-wheel-mpn-bw9334.html?singleid=2926629554',
 'https://www.carid.com/vdo/hvac-blower-motor-wheel-mpn-bw0307.html?singleid=2926625473',
 'https://www.carid.com/vdo/hvac-blower-motor-wheel-mpn-bw0306.html?singleid=2926618516',
 'https://www.carid.com/vdo/hvac-blower-motor-wheel-mpn-bw0306.html?singleid=2926585594',
 'https://www.carid.com/vdo/hvac-blower-motor-wheel-mpn-bw9309.html?singleid=2926580581',
 'https://www.carid.com/vdo/hvac-blower-motor-wheel-mpn-bw0306.html?singleid=2926576703',
 'https://www.carid.com/vdo/hvac-blower-motor-wheel-mpn-bw0302.html?singleid=2926574695',
 'https://www.carid.com/vdo/hvac-blower-motor-wheel-mpn-bw9301.html?singleid=2926562618',
 'https://www.carid.com/vdo/hvac-blower-motor-wheel-mpn-bw0302.html?singleid=2926558589',
 'https://www.carid.com/vdo/hvac-blower-motor-wheel-mpn-bw9308.html?singleid=2926539684',
 'https://www.carid.com/vdo/hvac-blower-motor-wheel-mpn-bw9350.html?singleid=1063272995',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm5170.html?singleid=5121611696',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4668.html?singleid=5121603704',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4882.html?singleid=5121586707',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4871.html?singleid=5121584706',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm5241.html?singleid=5121561709',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4367.html?singleid=5121510687',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4844.html?singleid=5121494708',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4508.html?singleid=5121468700',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4987.html?singleid=5121465701',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4427.html?singleid=4313653497',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm5084.html?singleid=4313563484',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4857.html?singleid=4313550486',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4102.html?singleid=4313534472',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm5226.html?singleid=4313520474',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4102.html?singleid=4313518466',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4427.html?singleid=4313516478',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4082.html?singleid=3949436396',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm5267.html?singleid=3949374389',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4904.html?singleid=3770864550',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4102.html?singleid=3770862570',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm3914.html?singleid=3770862559',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4102.html?singleid=3770848592',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4118.html?singleid=3770847575',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4046.html?singleid=3770823731',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4914.html?singleid=3770816719',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4374.html?singleid=3770807714',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4540.html?singleid=3770788762',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm2713.html?singleid=3770779655',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm5226.html?singleid=3770764762',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm3785.html?singleid=3770757711',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4427.html?singleid=3770752694',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm5084.html?singleid=3770725671',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4102.html?singleid=3770723737',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4728.html?singleid=3770714638',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4970.html?singleid=3770710734',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4427.html?singleid=3770710691',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm3748.html?singleid=2926658466',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm220.html?singleid=2926657529',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4540.html?singleid=2926657525',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4970.html?singleid=2926657524',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm3798.html?singleid=2926657493',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4374.html?singleid=2926656522',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4072.html?singleid=2926656460',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm3316.html?singleid=2926655443',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm281.html?singleid=2926652509',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm5037.html?singleid=2926652484',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm255.html?singleid=2926650537',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm2711.html?singleid=2926650530',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4119.html?singleid=2926650475',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm3319.html?singleid=2926648548',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4427.html?singleid=2926648538',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm4517.html?singleid=2926648434',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm3933.html?singleid=2926644498',
 'https://www.carid.com/vdo/hvac-blower-motor-mpn-pm3903.html?singleid=2926644490',

In [2]:
df = pd.DataFrame(columns=['Url',
                           'Title',
                           'mpn',
                           'Brand',
                           'Part_Number',
                           'UPC',
                           'Vehicle',
                           'Src',
                           'status'])

df

Empty DataFrame
Columns: [Url, Title, mpn, Brand, Part_Number, UPC, Vehicle, Src, status]
Index: []

In [3]:
from selenium.webdriver import ChromeOptions
option = ChromeOptions()
option.add_experimental_option('useAutomationExtension', False)
option.add_argument('blink-settings=imagesEnabled=false')
option.add_argument('--disable-blink-features=AutomationControlled')
option.add_argument('--disable-dev-shm-usage')
option.add_argument('--disable-gpu')
option.add_experimental_option('excludeSwitches', ['enable-automation'])
# option.add_argument('--headless')
option.add_argument('--no-sandbox')
option.add_argument('--proxy-server=http://u431.kdltps.com:15818')
option.add_argument('user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36')
option.page_load_strategy = 'eager'

In [4]:
from selenium.webdriver import Chrome
from selenium.webdriver.chrome.service import Service
browser = Chrome(service=Service(r'C:\Users\YangTeng\Desktop\venv\chromedriver'), options=option)

browser.maximize_window()

In [5]:
import time
i = 4

browser.get(list_url[i])

time.sleep(5)

In [6]:
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.by import By

wait = WebDriverWait(browser, 60)
wait.until(EC.presence_of_element_located((By.XPATH, '//div[@class="prod-title js-prod-title"]/h1[@class="name"]')))
title = browser.find_element(by=By.XPATH, value='//div[@class="prod-title js-prod-title"]/h1[@class="name"]').text

title

'VDO® - HVAC Blower Motor with Wheel'

In [7]:
list_row = browser.find_element(by=By.XPATH, value='//div[@class="prod-title js-prod-title"]').text.split('|')
mpn = ''
for row in list_row:
    if row.startswith('Item # mpn'):
        mpn = row.split('Item # mpn')[1]

mpn

'4689752193'

In [10]:
wait.until(EC.presence_of_element_located((By.XPATH, '//div[@class="prod-offer"]')))
list_offer = browser.find_elements(by=By.XPATH, value='//div[@class="prod-offer"]/div[@class="prod-offer-item"]')

list_offer

[<selenium.webdriver.remote.webelement.WebElement (session="ac1b79db209fc9107c77aea02e7f5673", element="E8BB43AFE14419B004CB3DA8CA824683_element_54")>,
 <selenium.webdriver.remote.webelement.WebElement (session="ac1b79db209fc9107c77aea02e7f5673", element="E8BB43AFE14419B004CB3DA8CA824683_element_55")>,
 <selenium.webdriver.remote.webelement.WebElement (session="ac1b79db209fc9107c77aea02e7f5673", element="E8BB43AFE14419B004CB3DA8CA824683_element_56")>,
 <selenium.webdriver.remote.webelement.WebElement (session="ac1b79db209fc9107c77aea02e7f5673", element="E8BB43AFE14419B004CB3DA8CA824683_element_57")>]

In [11]:
brand = ''
part_number = ''
upc = ''
for offer in list_offer:
    if offer.text.startswith('Brand:'):
        brand = offer.text.split('Brand:')[1]
    elif offer.text.startswith('Part Number:'):
        part_number = offer.text.split('Part Number:')[1]
    elif offer.text.startswith('UPC:'):
        upc = offer.text.split('UPC:')[1]
        
brand, part_number, upc

('VDO', 'PM9318', '053674093182')

In [12]:
js = '''let list_expand = document.querySelectorAll('div[class="mmy-row"]');
for(let i=0; i<list_expand.length; i++) {
        list_expand[i].getElementsByClassName('mmy-row-expand')[0].click();
}'''

browser.execute_script(js)

In [13]:
wait.until(EC.presence_of_element_located((By.XPATH, '//div[@class="prod-section-content"]')))
list_row = browser.find_elements(by=By.XPATH, value='//div[@class="prod-section-content"]')

list_vehicle = []
for row in list_row:
    if row.text.startswith('Vehicle Fitment'):
        list_make = row.find_elements(by=By.XPATH, value='./descendant::div[@class="mmy-row-title pointer js-mmy-row-expand"]')
        for make in list_make:
            list_vehicle += [make.text + ' ' + model_year.text for model_year in make.find_elements(by=By.XPATH, value='./following-sibling::div[@class="mmy-row-description"]/descendant::div[@class="mmy-subrow-title"]')]
            
vehicle = '\n'.join(list_vehicle)

vehicle

'Nissan Altima 2005-2006\nNissan Maxima 2003-2007'

In [14]:
wait.until(EC.presence_of_element_located((By.XPATH, '//a[@class="product-image-main"]')))
src = browser.find_element(by=By.XPATH, value='//a[@class="product-image-main"]').get_attribute('href')

src

'https://images.carid.com/vdo/items/pm9318.jpg'

In [15]:
df_temp = pd.DataFrame([{'Url': list_url[i],
                         'Title': title,
                         'mpn': mpn,
                         'Brand': brand,
                         'Part_Number': part_number,
                         'UPC': upc,
                         'Vehicle': vehicle,
                         'Src': src,
                         'status': 'ok'}])

df_temp

,Url,Title,mpn,Brand,Part_Number,UPC,Vehicle,Src,status
0,https://www.carid.com/vdo/hvac-blower-motor-wi...,VDO® - HVAC Blower Motor with Wheel,4689752193,VDO,PM9318,053674093182,Nissan Altima 2005-2006\nNissan Maxima 2003-2007,https://images.carid.com/vdo/items/pm9318.jpg,ok

In [16]:
wait.until(EC.presence_of_element_located((By.XPATH, '//table[@class="spec-stripped-table"]')))
list_row = [row.text for row in browser.find_elements(by=By.XPATH, value='//table[@class="spec-stripped-table"]/tbody/tr/td')]

start = ''
for row in list_row:
    if ':' in row:
        name_value = row.split(': ')
        df_temp[(start + ' ' + name_value[0]).strip().lower()] = ': '.join(name_value[1:])
    else:
        start = row
        
browser.quit()

df = pd.concat([df, df_temp], ignore_index=True).fillna('')

df

,Url,Title,mpn,Brand,Part_Number,UPC,Vehicle,Src,status,voltage,...,mounting hardware included,terminal quantity,terminal gender,mounting method,connector gender,connector type,wheel diameter,flanged end,vented,shaft type
0,https://www.carid.com/vdo/hvac-blower-motor-wi...,VDO® - HVAC Blower Motor with Wheel,4689752193,VDO,PM9318,053674093182,Nissan Altima 2005-2006\nNissan Maxima 2003-2007,https://images.carid.com/vdo/items/pm9318.jpg,ok,12V,...,No,2,Male,Flange Mounted,Female,Plug,6.000 in,Yes,Yes,Single Shaft