In [1]:
import os
list_file = list(os.walk(r'C:\Users\YangTeng\Downloads\爬虫\amazon\detail-1'))[0][2]
if '.DS_Store' in list_file:
    list_file.remove('.DS_Store')
if '0.null.txt' in list_file:
    list_file.remove('0.null.txt')
    
len(list_file)

100

In [2]:
import pandas as pd
df = pd.DataFrame()

df

Empty DataFrame
Columns: []
Index: []

In [3]:
from tqdm import tqdm
import json
for file in tqdm(list_file, desc='进度', ncols=77):
    with open('C:/Users/YangTeng/Downloads/爬虫/amazon/detail-1/' + file, 'r', encoding='UTF-8') as f:
        df = pd.concat([df, pd.DataFrame(json.loads(f.read()))], ignore_index=False)

df.to_excel(r'C:\Users\YangTeng\Downloads\爬虫\amazon\detail-1\detail-1.xlsx', index=False)

df

进度: 100%|███████████████████████████████| 100/100 [00:00<00:00, 254.41it/s]

,ASIN,Title,Price,About,Pic,Url,Src,auto part position,item dimensions lxwxh,brand,...,mirror lighting type,voltage,abpa partslink number,bulb type,batteries,position,lift type,vehicle service type,lens color,lens material
0,B07NY4FZ9X,AERDM New Pair Towing Mirrors Manual Operated ...,$87.85,1. These Mirrors Will Fit The Following Models...,,https://www.amazon.com/AERDM-Operated-Telescop...,https://m.media-amazon.com/images/I/61uDfPJyeW...,‎Rear,‎21.46 x 13.78 x 15.35 inches,‎AERDM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,B081B1XVRY,AERDM New Towing Mirror Black Housing with Tem...,$225.99,1. FITMENT: 1999-2016 Ford Super Duty F-250 F-...,,https://www.amazon.com/AERDM-Temperature-1999-...,https://m.media-amazon.com/images/I/41szaCVjuq...,‎Left,NaN,‎AERDM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,B0C3LSC7Z5,"Ajxn Pack-2 Car Towing Mirrors, Adjustable 360...",$39.99,1. Specifications: You will receive 2 universa...,,https://www.amazon.com/Ajxn-Adjustable-Extensi...,https://m.media-amazon.com/images/I/61qwF-LA73...,"‎Left, Right",NaN,‎Ajxn,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,B07FSVG277,Power Heated Signal Side View Towing Mirror As...,Sanooer Towing Mirrors Compatible with 2009-20...,1. [Package Content] - ONLY driver side includ...,,https://www.amazon.com/Assembly-Compatible-201...,https://m.media-amazon.com/images/I/415WrzExuw...,‎Front Left,‎9 x 13 x 24 inches,‎VIPMOTOZ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,B071NGCBSN,SCITOO Towing Mirrors Exterior Mirrors fit for...,$149.99,1. 🎅FITMENT - For 07 NEW BODY STYLE For Silver...,,https://www.amazon.com/Automotive-Exterior-200...,https://m.media-amazon.com/images/I/51F4eXWVFG...,‎Outside,‎20.87 x 16.54 x 13.98 inches,‎SCITOO,...,‎Turn Signal Indicator,‎12 Volts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,B01ICMZC78,YITAMOTOR Towing Mirrors Compatible for 99-07 ...,$161.01,1. Fitment: compatible with Ford 1999-2007 F25...,,https://www.amazon.com/YITAMOTOR-Towing-Mirror...,https://m.media-amazon.com/images/I/81uviMZVa0...,‎Front Left Outer,‎21 x 15 x 20 inches,‎YITAMOTOR,...,NaN,NaN,NaN,‎Halogen Lamp,NaN,NaN,NaN,NaN,NaN,NaN
0,B01HPD0BUI,YITAMOTOR Towing Mirrors Compatible with Ford ...,AERDM Towing Mirrors Compatible with Ford F150...,1. Fitment: compatible with 2007 - 2014 Ford F...,,https://www.amazon.com/YITAMOTOR-Towing-Mirror...,https://m.media-amazon.com/images/I/71zwj22rsJ...,‎Front Left Outer,‎22 x 20 x 16 inches,‎YITAMOTOR,...,NaN,NaN,NaN,‎LED,NaN,NaN,NaN,NaN,NaN,NaN
0,B01FTGRTN0,YITAMOTOR Towing Mirrors Compatible with 07-14...,$108.85,1. FITMENT - Compatible with Chevy Silverado G...,,https://www.amazon.com/YITAMOTOR-Towing-Mirror...,https://m.media-amazon.com/images/I/71qmFVxhRP...,‎Front Left Outer,‎21.65 x 13.39 x 14.57 inches,‎YITAMOTOR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,B0BZKMBBHT,Youxmoto Towing Mirrors for Dodge Ram 1500 200...,$158.99,"1. 🚘【OEM DESIGN, DIRECT FIT】: Youxmoto Towing ...",,https://www.amazon.com/Youxmoto-Towing-Mirrors...,https://m.media-amazon.com/images/I/61yNQim97O...,‎Right,‎13 x 13 x 20 inches,‎Youxmoto,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,B0B15BDXTK,ZAPOSTS Towing Mirrors Replacement Fit for 02-...,$89.80,1. fit for Pickup Truck：2002-2008 Dodge Ram 15...,,https://www.amazon.com/ZAPOSTS-Mirrors-Replace...,https://m.media-amazon.com/images/I/61OP1py2y0...,‎Front Left Outer,NaN,‎ZAPOSTS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN