In [1]:
import os
list_file = list(os.walk(r'C:\Users\YangTeng\Downloads\爬虫\amazon\销量-1'))[0][2]
if '.DS_Store' in list_file:
    list_file.remove('.DS_Store')
if '0.null.txt' in list_file:
    list_file.remove('0.null.txt')
    
len(list_file)

100

In [2]:
import pandas as pd
df = pd.DataFrame()

df

Empty DataFrame
Columns: []
Index: []

In [4]:
from tqdm import tqdm
import json
for file in tqdm(list_file, desc='进度', ncols=77):
    with open('C:/Users/YangTeng/Downloads/爬虫/amazon/销量-1/' + file, 'r', encoding='UTF-8') as f:
        df = pd.concat([df, pd.DataFrame(json.loads(f.read()))], ignore_index=False)

df.to_excel(r'C:\Users\YangTeng\Downloads\爬虫\amazon\销量\销量-1.xlsx', index=False)

df

进度: 100%|███████████████████████████████| 100/100 [00:00<00:00, 494.61it/s]

,ASIN,标识,PASIN,品牌,品牌链接,大类BSR,BSR增长数,BSR增长率,父体月销量,父体月销量增长率,...,小类目,小类目链接,重量_1,重量_2,体积_1,体积_2,LQS,变体数,SKU,卖家数
0,B00069CN2I,A+;AC,B004OQLPR8,CIPA,https://www.amazon.com/CIPA/b/ref=bl_dp_s_web_...,"26,470","10,708",40%,186,-28%,...,Towing Hitch Towing Mirrors,https://www.amazon.com/gp/bestsellers/automoti...,3.55 pounds,1.61 kg,18 x 9.5 x 10 inches,45.72 x 24.13 x 25.40 cm,8.8,3个,Style: Pair,49家
0,B001ABPKUS,A+;AC,B004OQNUNK,CIPA,https://www.amazon.com/CIPA/b/ref=bl_dp_s_web_...,"41,277","-8,714",-26%,174,-16%,...,Towing Hitch Towing Mirrors,https://www.amazon.com/gp/bestsellers/automoti...,1.81 Kilograms,1.81 kg,18 x 9.25 x 9.5 inches,45.72 x 23.50 x 24.13 cm,9.1,3个,Style: Pair,50家
0,B000B5QFE4,A+;AC,B004OQGUQE,CIPA,https://www.amazon.com/CIPA/b/ref=bl_dp_s_web_...,"23,637","82,197",348%,165,-21%,...,Towing Hitch Towing Mirrors,https://www.amazon.com/gp/bestsellers/automoti...,4.3 pounds,1.95 kg,18 x 9 x 10 inches,45.72 x 22.86 x 25.40 cm,9.1,3个,Style: Pair,49家
0,B0C2V2B72J,A+;BS,B0C2Z2LZZC,CIPA,https://www.amazon.com/CIPA/b/ref=bl_dp_s_web_...,"7,397","-4,127",-56%,876,-36%,...,Towing Hitch Towing Mirrors,https://www.amazon.com/gp/bestsellers/automoti...,32 Ounces,907.18 g,--,--,8.4,2个,Size: 15.75 Inch (Pack of 2),1家
0,B00T36HLYU,A+;AC,B00T36HLYU,CIPA,https://www.amazon.com/CIPA/b/ref=bl_dp_s_web_...,"30,661","7,290",37%,257,-36%,...,Towing Hitch Towing Mirrors,https://www.amazon.com/gp/bestsellers/automoti...,3.99 pounds,1.81 kg,18 x 9.5 x 10.5 inches,45.72 x 24.13 x 26.67 cm,8.9,无,,29家
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,B091CDBCW9,A+;V,B0BPLY5M3C,AUTOSAVER88,https://www.amazon.com/stores/AUTOSAVER88/page...,"100,296","64,904",84%,39,37%,...,Towing Hitch Towing Mirrors,https://www.amazon.com/gp/bestsellers/automoti...,19.8 Pounds,8.98 kg,22.44 x 14.17 x 14.76 inches,57.00 x 35.99 x 37.49 cm,10.0,6个,Configuration: 2003-2007 | Style: Chrome,2家
0,B089CX2SWF,A+;V;AC,B089CX2SWF,AUTOSAVER88,https://www.amazon.com/stores/AUTOSAVER88/page...,"125,630","-34,947",-28%,56,11%,...,Towing Hitch Towing Mirrors,https://www.amazon.com/gp/bestsellers/automoti...,20.5 pounds,9.30 kg,23 x 15.7 x 14.4 inches,58.42 x 39.88 x 36.58 cm,10.0,无,,2家
0,B0951MK5B5,A+;V;AC,B0B7ZQX52Z,BOOLEE,https://www.amazon.com/stores/BOOLEE/page/B38B...,"35,179","-6,145",-17%,150,-11%,...,Towing Hitch Towing Mirrors,https://www.amazon.com/gp/bestsellers/automoti...,24.8 pounds,11.25 kg,23.75 x 15 x 15 inches,60.33 x 38.10 x 38.10 cm,10.0,8个,Color: 17-20 F250 350 450 Towing Mirrors Black,1家
0,B0C8CN8ML9,A+;V;NR,B0C8CN8ML9,CAFOPAR,https://www.amazon.com/stores/CAFOPAR/page/62D...,"23,664","15,357",65%,170,49%,...,Towing Hitch Towing Mirrors,https://www.amazon.com/gp/bestsellers/automoti...,2.51 pounds,1.14 kg,14.96 x 6.14 x 4.76 inches,38.00 x 15.60 x 12.09 cm,9.5,无,,1家
0,B07NY4FZ9X,A+,B07NY4FZ9X,AERDM,https://www.amazon.com/stores/AERDM/page/014EF...,"36,510","8,991",28%,219,-9%,...,Towing Hitch Towing Mirrors,https://www.amazon.com/gp/bestsellers/automoti...,14.42 pounds,6.54 kg,21.5 x 13.8 x 15.4 inches,54.61 x 35.05 x 39.12 cm,10.0,无,,1家