In [2]:
import os
list_file = list(os.walk('C:/Users/YangTeng/Desktop/文档/爬虫/blower motor resistor'))[0][2]
if '.DS_Store' in list_file:
    list_file.remove('.DS_Store')
if '0.null.txt' in list_file:
    list_file.remove('0.null.txt')
    
len(list_file)

5

In [3]:
import pandas as pd
df = pd.DataFrame()

df

Empty DataFrame
Columns: []
Index: []

In [7]:
from tqdm import tqdm
import json
for file in tqdm(list_file, desc='Progress', ncols=77):
    with open('C:/Users/YangTeng/Desktop/文档/爬虫/blower motor resistor/' + file, 'r', encoding='UTF-8') as f:
        df = pd.concat([df, pd.DataFrame(json.loads(f.read()))], ignore_index=False)
        
df = df[['Part_Number', 'Url']]

df.to_excel('C:/Users/YangTeng/Desktop/文档/爬虫/blower motor resistor.xlsx', index=False)

df

Progress: 100%|███████████████████████████████| 5/5 [00:00<00:00, 469.31it/s]

   Part_Number                                                Url
0      973-966  https://www.dormanproducts.com/p-134922-973-96...
1      973-896  https://www.dormanproducts.com/p-135246-973-89...
2      973-913  https://www.dormanproducts.com/p-145970-973-91...
3      973-952  https://www.dormanproducts.com/p-139568-973-95...
4      973-954  https://www.dormanproducts.com/p-133322-973-95...
..         ...                                                ...
35     645-566  https://www.dormanproducts.com/p-74672-645-566...
36     645-217  https://www.dormanproducts.com/p-85934-645-217...
37       84645  https://www.dormanproducts.com/p-50806-84645.a...
38     645-702  https://www.dormanproducts.com/p-10376-645-702...
39     645-596  https://www.dormanproducts.com/p-65606-645-596...

[880 rows x 2 columns]