###### 网站：https://www.dormanproducts.com/gsearch.aspx?type=keyword&origin=keyword&q=Climate%2520Control%2520Module&start=0&num=100

In [1]:
import os
import pandas as pd
import requests
import re 
from bs4 import BeautifulSoup
from lxml import etree
import json
from selenium.webdriver import ChromeOptions

In [6]:
import sys
sys.path.append('C:/Users/YangTeng/Desktop/venv/00.module')
import UA
import Proxy

In [2]:
df_menu = pd.read_excel('C:/Users/YangTeng/Downloads/Dorman_memu.xlsx', header=0)
list_url = df_menu['Url'].to_list()

print('总数量：' + str(len(list_url)))
list_url

总数量：490

['https://www.dormanproducts.com/p-137962-926-758.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-107261-926-133.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-64242-604-010.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-64244-604-011.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-107572-902-603.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-64236-604-012.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-129361-604-018.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-76147-604-908.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-142540-adakit010.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-142539-adakit009.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-64690-604-020.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-97856-604-056.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-76224-604-918.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-142537-adakit006.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-142534-adakit003.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-103305-604-050.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-65477-604-043.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-65468-604-046.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-135060-604-387.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-142600-adakit007.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-142535-adakit004.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-142533-adakit001.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-142541-adakit011.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-87721-604-5106cd.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-130988-926-180.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-87706-604-5101cd.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-79755-604-942.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-64233-604-008.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-90897-604-315.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-70297-604-239.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-71274-604-240.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-74516-604-280.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-135203-604-386.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-91973-604-057.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-70485-604-244.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-71275-604-250.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-76228-604-910.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-75606-604-905.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-81281-604-938.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-84138-604-941.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-76220-604-911.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-142538-adakit008.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-67500-604-256.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-66347-604-275.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-99959-604-874.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-97671-604-875.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-98705-604-863.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-90890-604-710.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-101172-604-832.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-97687-604-868.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-96549-604-880.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-97857-604-705.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-90027-604-856.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-97688-604-869.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-101706-604-962.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-105571-604-939.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-72826-604-277.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-66367-604-272.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-77402-604-5107.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-82033-604-917.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-85964-604-970.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-81082-604-935.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-77692-604-916.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-67081-604-017.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-66356-604-035.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-66483-604-259.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-66338-604-253.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-126293-604-324.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-94744-604-290.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-142536-adakit005.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-142599-adakit002.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-102043-604-833.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-98704-604-862.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-98416-604-624.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-100087-604-625.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-97841-604-704.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-96564-604-881.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-98630-604-828.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-97844-604-822.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-90880-604-700.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-98072-604-817.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-97978-604-870.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-101684-604-953.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-126063-604-958.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-102658-604-947.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-102775-604-946.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-102529-604-322.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-81068-604-907.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-85962-604-813.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-76207-604-913.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-77362-604-930.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-77374-604-931.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-76212-604-912.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-77226-604-919.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-64096-604-260.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-64237-604-006.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-78255-604-5120.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-79224-604-5131.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-81866-604-811.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-80133-604-932.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-80117-604-933.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-97865-604-824.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-98635-604-819.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-80240-604-922.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-125929-604-948.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-98697-604-860.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-100238-604-830.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-101171-604-831.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-98698-604-883.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-98444-604-627.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-99980-604-876.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-99952-604-877.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-90026-604-854.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-94491-604-706.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-99961-604-955.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-76318-604-915.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-84106-604-945.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-76221-604-914.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-82727-604-936.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-84825-604-400.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-85968-604-814.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-84826-604-401.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-67319-604-850.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-77678-604-5104.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-50932-604-5101.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-76146-604-909.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-100239-604-835.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-101173-604-834.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-90889-604-701.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-97858-604-823.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-101170-604-829.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-96555-604-871.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-98690-604-864.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-96339-604-952.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-143026-604-925.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-78252-604-5155.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-97851-604-816.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-66333-604-900.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-96291-604-951.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-96290-604-950.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-97843-604-821.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-99966-604-872.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-99999-604-873.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-97842-604-815.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-101174-604-836.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-99955-604-867.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-99960-604-878.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-99967-604-879.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-98650-604-820.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-104158-604-298.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-64094-604-267.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-75614-604-901.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-80134-604-934.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-80223-604-923.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-98417-604-861.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-98742-604-882.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-90873-604-707.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-98092-604-818.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-98736-604-960.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-99968-604-954.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-101175-604-837.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-141208-604-193.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-141220-604-271.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-68422-604-600.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-79213-604-5113.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-75604-604-902.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-78151-604-5106.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-64691-604-009.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-75608-604-903.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-106972-604-943.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-79235-604-924.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-81076-604-906.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-106828-604-944.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-97345-604-709.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-99954-604-866.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-98445-604-628.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-98723-604-884.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-129362-604-885.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-102442-604-827.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-44841-604-115.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-141181-604-081.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-80239-604-921.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-81077-604-937.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-87734-604-5103cd.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-53635-604-219.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-20138-604-209.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-80908-604-048.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-11915-604-001.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-80490-604-5105.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-63837-604-184.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-34050-604-211.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-22254-604-202.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-22255-604-207.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-138476-604-361.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-74511-604-002.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-46575-604-126.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-66365-604-029.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-35291-604-112.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-91947-604-059.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-91959-604-058.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-5259-604-204.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-3530-604-106.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-15959-604-103.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-45688-604-214.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-45685-604-121.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-66366-604-038.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-24320-604-201.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-45683-604-213.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-90879-604-291.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-44785-604-120.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-65244-604-155.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-135204-604-388.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-67362-604-245.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-67411-604-237.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-77682-604-278.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-76226-604-273.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-73305-604-284.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-66987-604-044.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-72869-604-014.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-67510-604-036.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-66653-604-021.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-67392-604-037.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-76846-604-5103.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-134959-604-337.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-134955-604-314.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-134963-604-372.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-140710-604-345.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-102527-604-172.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-97854-604-051.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-85105-604-105.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-66977-604-233.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-73276-604-310.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-72814-604-241.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-66981-604-232.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-70758-604-238.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-74111-604-004.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-141223-604-351.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-141172-604-072.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-141200-604-137.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-141173-604-073.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-141189-604-090.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-141190-604-091.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-73281-604-279.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-66645-604-251.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-141212-604-215.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-141221-604-285.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-142495-604-378.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-141166-604-066.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-141184-604-084.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-141185-604-085.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-141167-604-067.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-141205-604-144.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-141206-604-145.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-141178-604-078.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-141179-604-079.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-134962-604-369.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-134961-604-357.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-138477-604-368.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-99692-604-456.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-134957-604-332.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-134958-604-333.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-134960-604-341.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-67044-604-016.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-101690-604-451.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-102042-604-450.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-102161-604-321.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-142824-604-338.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-141202-604-139.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-141195-604-096.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-141199-604-104.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-141201-604-138.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-141196-604-097.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-143025-604-339.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-66030-604-175.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-65271-604-168.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-65269-604-169.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-77224-604-311.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-141174-604-074.aspx?origin=keyword',
 'https://www.dormanproducts.com/p-141175-604-075.aspx?origin=keyword',

In [3]:
df = pd.DataFrame(columns=['Url',
                           'Src',
                           'status'])

df

Empty DataFrame
Columns: [Url, Src, status]
Index: []

In [9]:
headers = UA.get_User_Agent_Requests()
headers

{'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.29 Safari/537.36'}

In [10]:
headers ={
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
}


proxies = {'http': 'http://t19182064816778:9s5s2nv0@f290.kdltps.com:15818',
           'https': 'http://t19182064816778:9s5s2nv0@f290.kdltps.com:15818'}
i = 0

resp = requests.get(list_url[i],headers=headers,proxies=proxies).text
resp

AttributeError: 'str' object has no attribute 'get'

In [12]:
soup = BeautifulSoup(resp,'lxml')

print(soup.prettify())
html = etree.HTML(str(soup))

<!DOCTYPE html>
<html lang="en">
 <head>
  <title>
   HVAC Blend Door Actuator Gear Kit | 926-758 | HVAC Blend Door Gear Kit | Dorman Products
  </title>
  <meta charset="utf-8"/>
  <meta content="no-cache, no-store, must-revalidate" http-equiv="cache-control"/>
  <meta content="no-cache" http-equiv="pragma"/>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <meta content="-1" http-equiv="expires"/>
  <meta content="Dorman Products - 926-758 : HVAC Blend Door Gear Kit. Air not flowing through the dash vents properly? Repair a worn or broken blend door actuator with this replacement HVAC blend door gear kit. Saves time and money by replacing only the worn gear while preserving the rest of the blend door assembly." name="description"/>
  <meta content="926-758,  HVAC, Heater, Blend, Door, Actuator, Gear, Kit, Kits, Gears, Actuators, Blend Door Actuator Gear Kit, Blend Door Motor Gear Kit, HVAC Heater Blend Door Motor Gear Kit" name="keywords"/>
  <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport"/>
  <meta content="no" name="apple-mobile-web-app-capable"/>
  <link href="https://www.dormanproducts.com/p-137962-926-758.aspx" rel="canonical"/>
  <meta content="Dorman Products - 926-758" property="og:title"/>
  <meta content="product" property="og:type"/>
  <meta content="https://www.dormanproducts.com/images/product/icon/926-758-007.JPG" property="og:image"/>
  <meta content="https://www.dormanproducts.com/p-137962-926-758.aspx" property="og:url"/>
  <meta content="HVAC Blend Door Gear Kit" property="og:description"/>
  <link href="https://www.dormanproducts.com/images/product/icon/926-758-007.JPG" rel="image_src"/>
  <!--[if lt IE 9]>
      <script src="/scripts/html5shiv.js"></script>
    <![endif]-->
  <!--[if IE]>
  		<script src="/scripts/html5shiv.js"></script>
	<![endif]-->
  <link href="/content/webfonts.min.css" rel="stylesheet"/>
  <link href="/content/bootstrap.min.css" rel="stylesheet"/>
  <link href="/content/bootstrap-dialog.min.css" rel="stylesheet"/>
  <link href="/content/style.css?d=20220208" rel="stylesheet"/>
  <link href="/content/fontello.min.css" rel="stylesheet"/>
  <link href="/content/yamm.css" rel="stylesheet"/>
  <link href="/content/non_login.css?d=20190905" id="nonloginStyle" rel="stylesheet"/>
  <!--[if lte IE 9]>
        <link href="/content/animations-ie-fix.css" rel="stylesheet" type="text/css">
    <![endif]-->
  <link href="/content/sliderstyle-3.min.css" rel="stylesheet"/>
  <link href="/content/animations.min.css" rel="stylesheet"/>
  <link href="/content/off-canvas.min.css" rel="stylesheet"/>
  <link href="//static.dormanproducts.com/images/website/banner2/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
  <link href="//static.dormanproducts.com/images/website/banner2/apple-touch-icon.png" rel="apple-touch-icon"/>
  <link href="//static.dormanproducts.com/images/website/banner2/apple-touch-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
  <link href="//static.dormanproducts.com/images/website/banner2/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
  <link href="//static.dormanproducts.com/images/website/banner2/apple-touch-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
  <link href="//static.dormanproducts.com/images/website/banner2/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
  <link href="//static.dormanproducts.com/images/website/banner2/apple-touch-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
  <link href="//static.dormanproducts.com/images/website/banner2/apple-touch-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
  <link href="//static.dormanproducts.com/images/website/banner2/apple-touch-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
  <link href="//static.dormanproducts.com/images/website/banner2/apple-touch-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
  <script src="/scripts/head.min.js?d=20190905" type="text/javascript">
  </script>
  <script type="text/javascript">
   <!--
    head.load({ stringresources: "/scripts/StringResources.js?d=20190905" },
        { jquery: "/scripts/jquery.min.js?d=20190905" },
        { bootstrap: "/scripts/bootstrap.min.js?d=20190905" },
        { dialog: "/scripts/bootstrap-dialog.min.js?d=20190905" },
        { validator: "/scripts/validator.min.js?d=20190905" },
        { modernizr: "/scripts/modernizr.min.js?d=20190905" },
        { isotope: "/scripts/isotope.pkgd.min.js?d=20190905" },
        { bootstrapdropdown: "/scripts/jquery.bootstrap-dropdown-hover.min.js?d=20190905" },
        { dormanscript: "/scripts/dorman-scripts.js?d=20210709" },
        { slider: "/scripts/slidermain.js?d=20190905" },
        { css3animate: "/scripts/css3-animate-it.js?d=20190905" },
        { jqcustom: "/scripts/jquery.custom.js?d=20190905" },
        { typeahead: "/scripts/bootstrap3-typeahead.min.js?d=20190905" },
        { checkform: "/scripts/CheckForm.js?d=20220208" },
        { ie10viewport: "/scripts/ie10-viewport-bug-workaround.js?d=20190905" },
        { eventtracking: "/scripts/eventTracking.js?d=20190905" },
        { recentActivities: "/scripts/recentactivites.js?d=20190905" });
    //-->
  </script>
  <script src="/scripts/autodetect.js?d=20190905" type="text/javascript">
  </script>
  <!-- Google Tag Manager -->
  <script>
   (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-5JGR3XL');
  </script>
  <!-- End Google Tag Manager -->
  <!-- Facebook Pixel Code -->
  <script>
   !function (f, b, e, v, n, t, s) {
            if (f.fbq) return; n = f.fbq = function () {
                n.callMethod ?
                    n.callMethod.apply(n, arguments) : n.queue.push(arguments)
            };
            if (!f._fbq) f._fbq = n; n.push = n; n.loaded = !0; n.version = '2.0';
            n.queue = []; t = b.createElement(e); t.async = !0;
            t.src = v; s = b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t, s)
        }(window, document, 'script',
            'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '362412311106864');
        fbq('track', 'PageView');
  </script>
  <!-- End Facebook Pixel Code -->
  <!-- Microsoft ad Conversion Tracking -->
  <script>
   (function (w, d, t, r, u) {
            var f, n, i; w[u] = w[u] || [], f = function () {
                var o = { ti: "137031075" }; o.q = w[u], w[u] = new UET(o), w[u].push("pageLoad")
            }, n = d.createElement(t), n.src = r, n.async = 1, n.onload = n.onreadystatechange = function () {
                var s = this.readyState; s && s !== "loaded" && s !== "complete" || (f(), n.onload = n.onreadystatechange = null)
            }, i = d.getElementsByTagName(t)[0], i.parentNode.insertBefore(n, i)
        })(window, document, "script", " //bat.bing.com/bat.js", "uetq");
  </script>
  <!-- End Microsoft ad Conversion Tracking -->
  <style>
   #divWTBlabels h4 {margin-bottom:0px;}
		#divWTBlabels p {margin-bottom:5px;}
  </style>
  <script>
   var __uzdbm_1 = "2f8f8bbc-f9c5-4774-b58a-1cc44c4b2c86";var __uzdbm_2 = "MjYxNWFhN2YtYnUydi00YjczLWE3NmUtMjBmZDc3OGRlMWU3JDE3MS40MS4xMzEuOQ==";var __uzdbm_3 = "";var __uzdbm_4 = "false";
  </script>
  <script>
   (function(w, d, e, u, c, g, a, b){ w["SSJSConnectorObj"] = {ss_cid : c, domain_info: "auto"}; a = d.createElement(e); a.async = true; a.src = u; b = d.getElementsByTagName(e)[0]; b.parentNode.insertBefore(a, b); })(window,document,"script","https://cdn.perfdrive.com/aperture/aperture.js","bu2x","ssConf");
  </script>
 </head>
 <body data-spy="scroll">
  <noscript>
   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-5JGR3XL" style="display: none; visibility: hidden" width="0">
   </iframe>
  </noscript>
  <noscript>
   <img height="1" src="https://www.facebook.com/tr?id=362412311106864&amp;ev=PageView&amp;noscript=1" style="display: none" width="1"/>
  </noscript>
  <input id="WebsiteSkinID" name="WebsiteSkinID" type="hidden" value="1"/>
  <input id="IsMobile" name="IsMobile" type="hidden" value="0"/>
  <input id="hideskin" name="hideskin" type="hidden" value="0"/>
  <input id="sitewebsubpath" name="sitewebsubpath" type="hidden" value="/"/>
  <input id="IsLoggedInHidden" name="IsLoggedInHidden" type="hidden" value="0"/>
  <input id="IsEnglishLinkActiveHidden" name="IsEnglishLinkActiveHidden" type="hidden" value="Y"/>
  <input id="IsESPLinkActiveHidden" name="IsESPLinkActiveHidden" type="hidden" value="Y"/>
  <input id="englishurlHidden" name="englishurlHidden" type="hidden" value="www.dormanproducts.com"/>
  <input id="spanishurlHidden" name="spanishurlHidden" type="hidden" value="www.dormanproducts.es"/>
  <input id="browserLanguage" name="browserLanguage" type="hidden"/>
  <input id="AccountNumber" name="AccountNumber" type="hidden"/>
  <input id="SearchIndexID" name="SearchIndexID" type="hidden" value="4"/>
  <input id="SearchResultPage" name="SearchResultPage" type="hidden" value="gsearch.aspx"/>
  <input id="showWTBMap" name="showWTBMap" type="hidden"/>
  <input id="showWTBError" name="showWTBError" type="hidden"/>
  <input id="uiCultureLanguage" name="uiCultureLanguage" type="hidden" value="en-US"/>
  <input id="WTBUrlHolder" name="WTBUrlHolder" type="hidden" value="https://wtbmap.dormanproducts.com?d=1"/>
  <input id="WhereToBuyMarketingParams" name="WhereToBuyMarketingParams" type="hidden" value="?amp;wmode=opaque&amp;partNumber=header&amp;brand=header&amp;specialOrder=0&amp;language="/>
  <!-- feedback/questions details -->
  <!-- login maintenace -->
  <!-- login webbanner -->
  <!--Redesign Header-->
  <!-- top banner navigation -->
  <header class="topbannerbg yamm" id="header">
   <div class="container">
    <nav class="row">
     <ul class="topbannernav topnav">
      <!-- language selection -->
      <li class="topbanner-link pull-left border-right border-left language-selection">
       <div aria-expanded="false" class="topbanner-btn" data-toggle="dropdown" role="button">
        <span aria-hidden="true" class="glyphicon glyphicon-globe">
        </span>
        <span class="hidden-xs hidden-sm hidden-md">
         Language:
         <span class="font-wht">
          English
          <span aria-hidden="true" class="icon-down-open-1">
          </span>
         </span>
        </span>
       </div>
       <ul class="topbanner-menu dropdown-menu">
        <script type="text/javascript">
         defaultLanguage_ENG();
        </script>
       </ul>
      </li>
     </ul>
     <ul class="topbannernav topnav topnav-right">
      <!-- show hide price -->
      <!-- new product details -->
      <li class="topbanner-link border-left">
       <a href="/Pages/forms/ideas.aspx">
        <div class="topbanner-btn dorman" data-target="#newproductModal" data-toggle="modal">
         <span aria-hidden="true" class="icon-lamp">
         </span>
         <span class="hidden-xs hidden-sm">
          New Product Idea
         </span>
        </div>
       </a>
      </li>
      <!-- be the first to know -->
      <li class="btftk-dropdown topbanner-link border-left">
       <a href="/Pages/forms/btftk.aspx">
        <div aria-controls="topBTFTK" aria-expanded="false" class="topbanner-btn" data-toggle="modal" role="button">
         <span aria-hidden="true" class="icon-mail-alt">
         </span>
         <span class="hidden-xs hidden-sm">
          Email Newsletters
         </span>
        </div>
       </a>
      </li>
      <!-- Live Chat -->
      <li class="topbanner-link border-left">
       <div class="topbanner-btn" id="hd_chat_link" onclick="return openMessenger('Header', 'Header Navigation');">
       </div>
      </li>
      <!-- recent activities -->
      <li class="topbanner-link border-left">
       <div class="topbanner-btn" id="divMenuRecentActivities" onclick="showRecentActiviesPopupDialog('link_click');">
        <span aria-hidden="true" class="glyphicon glyphicon-time">
        </span>
        <span class="hidden-xs hidden-sm">
         Recent Activities
        </span>
       </div>
      </li>
      <!-- distributor login -->
      <li class="dropdown topbanner-link border-left border-right" id="dist-login">
       <div class="topbanner-btn" onclick="return trackRedirectToPage('signin.aspx','link_click','Login');">
        <span aria-hidden="true" class="glyphicon glyphicon-cog">
        </span>
        <span class="hidden-xs">
         Login
        </span>
       </div>
      </li>
      <!-- distributor login success -->
      <li class="dropdown megamenu-fw topbanner-link border-left border-right bg-orange dist-login-link" id="dist-login-success">
       <div aria-expanded="false" class="topbanner-btn" data-toggle="dropdown" role="button">
        <span class="hidden-xs">
         <span aria-hidden="true" class="glyphicon glyphicon-cog">
         </span>
         :
        </span>
        <span aria-hidden="true" class="icon-basket-1">
        </span>
        <span class="hidden-xxs hidden-xxxs" id="cart-total">
         [] Items
                                |
         <strong>
          $
         </strong>
        </span>
        <span aria-hidden="true" class="icon-down-open-1">
        </span>
       </div>
       <ul class="collapse dropdown-menu topbanner-megamenu dist-logged-menu" id="topDistSuccess">
        <li>
         <div class="yamm-content">
          <div class="row topbanner-submenu">
           <div class="col-xs-6 col-xxs-12">
            <h5 class="dist-welcome">
             Welcome:
            </h5>
            <ul>
             <li class="cust_name">
              <h4>
               <a href="/account.aspx">
               </a>
              </h4>
             </li>
             <li>
              <a href="#">
               <div class="cust_phone">
                Customer Service:
               </div>
               <div class="cust_phone">
               </div>
              </a>
             </li>
             <li>
              <a href="/Pages/products/cores/returns.aspx">
               Core Policy &amp; Procedures
              </a>
             </li>
             <li id="menuSubAccountMaintenance">
              <a href="/dp_DCAdministration.aspx">
               Sub-Account Maintenance
              </a>
             </li>
             <li id="menuRegAccMaintenance">
              <a href="/dp_RegAccAdministration.aspx">
               Regional Account Maintenance
              </a>
             </li>
             <li id="menuProductFeed">
              <a href="/dp_ProductFeed.aspx">
               Product Feed
              </a>
             </li>
             <li id="menuWhereToBuyMaintenance">
              <a href="/dp_WhereToBuyAdministration.aspx">
               Where To Buy Maintenance
              </a>
             </li>
             <li id="menuFKey">
              <a href="/FKey">
               Dorman Products F-Key
              </a>
             </li>
            </ul>
            <hr class="topbanner-ruler hidden-xxs"/>
            <div class="dist-map-area" id="divEMRP">
             <h5>
              Electronic Minimum Advertised Price Policy (eMAP)
             </h5>
             <ul>
              <li>
               <a href="https://static.dormanproducts.com/document/corporate/Electronic-Minimum-Advertised-Price-Policy.pdf" target="_blank">
                eMAP Policy
               </a>
              </li>
             </ul>
            </div>
            <button class="btn btn-orange" onclick="window.location='/signout.aspx';">
             Log out
            </button>
           </div>
           <div class="col-xs-6 col-xxs-12">
            <div class="dist-shopcart">
             <h4>
              Shopping Cart:
             </h4>
             <h5>
              <span class="dist-shopcart-cat">
               Items in Cart:
              </span>
             </h5>
             <h5>
              <span class="dist-shopcart-cat">
               Total in Cart:
              </span>
              $
             </h5>
             <button class="btn btn-orange" onclick="window.location='/shoppingcart.aspx';">
              Checkout
             </button>
            </div>
            <hr class="topbanner-ruler hidden-xxs"/>
            <ul>
             <li>
              <a href="/orderhistorysearch.aspx">
               Order History
              </a>
             </li>
             <li>
              <a href="/expressorderform.aspx">
               Order Form
              </a>
             </li>
             <li id="menuUploadOrders">
              <a href="/dp_UploadOrders.aspx">
               Upload Order
              </a>
             </li>
             <li id="menuUpdateMenus">
              <a href="/dp_Menus.aspx">
               Update Menus
              </a>
             </li>
            </ul>
           </div>
          </div>
         </div>
        </li>
       </ul>
      </li>
     </ul>
    </nav>
   </div>
  </header>
  <!-- top banner navigation end -->
  <!-- menu -->
  <div class="nav-wrapper" id="navWrap">
   <div class="container">
    <nav class="navbar row yamm">
     <a class="navbar-brand" href="/">
      <img alt="Dorman Products" class="navbar-logo img-responsive" src="//static.dormanproducts.com/images/website/homepage/dorman_logo.gif"/>
     </a>
     <div class="navbar-header">
      <button class="navbar-toggle" data-target=".navbar-ex1-collapse" data-toggle="collapse" type="button">
       <span class="sr-only">
       </span>
       <span class="icon-bar">
       </span>
       <span class="icon-bar">
       </span>
       <span class="icon-bar">
       </span>
      </button>
     </div>
     <div class="collapse right navbar-collapse navbar-ex1-collapse">
      <div class="cl-effect-12">
       <ul class="nav navbar-nav pull-right">
        <!--- what's new --->
        <li class="dropdown yamm-fw">
         <a aria-expanded="false" data-toggle="dropdown" href="#" role="button">
          <div class="selected-marker hidden-xs">
          </div>
          What's New
         </a>
         <ul class="nav-megamenu dropdown-menu" id="whats-new">
          <div class="yamm-content">
           <div class="col-sm-8 col-md-6">
            <div class="row">
             <div class="col-sm-6">
              <h4>
               New Top Parts
              </h4>
              <div class="navbar-sublinks" id="divNewTopParts">
               <li>
                <a href="/p--902-3036XD.aspx">
                 Engine Coolant Water Outlet
                </a>
               </li>
               <li>
                <a href="/p--926-816.aspx">
                 Exhaust Flange Repair
                </a>
               </li>
               <li>
                <a href="/p--747-302.aspx">
                 Sliding Door Cable Repair Kits
                </a>
               </li>
               <li>
                <a href="/p--999-500.aspx">
                 Suspension Subframe
                </a>
               </li>
               <li>
                <a href="/p--999-986.aspx">
                 Fuel Tank Heat Shield
                </a>
               </li>
               <li>
                <a href="//static.dormanproducts.com/document/web/must-see-solutions_august-2023.pdf" target="_blank">
                 View All New Products
                </a>
               </li>
              </div>
              <h4>
               New Product Announcements
              </h4>
              <div class="navbar-sublinks" id="divNewProductAnnouncements">
               <li>
                <a href="/Pages/resources/npas/dorman.aspx#aug2023">
                 August

In [7]:
src = html.xpath('//*[@id="imgProductMain"]/@src') 

if len(html.xpath('//input[@id="hidfDetailApp"]/@value')) == 0:
    vehicle_url = ''
else:
    vehicle_url = 'https://www.dormanproducts.com/' + html.xpath('//input[@id="hidfDetailApp"]/@value')[0]

vehicle_url

'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=137962&PartType=HVAC%20Blend%20Door%20Actuator%20Gear%20Kit'

In [8]:
df_temp = pd.DataFrame([{'Url': list_url[i],
                         'Src': src,
                         'status': 'ok'}])

df_temp

,Url,Src,status
0,https://www.dormanproducts.com/p-137962-926-75...,[https://static.dormanproducts.com/images/prod...,ok

In [9]:
html = etree.HTML(str(soup))

oe = ';'.join(html.xpath('//section[@id="productOE"]/descendant::*/th[@scope="row"]/text()'))

oe

'13263335'

In [10]:
html = etree.HTML(str(soup))

oe = ';'.join(html.xpath('//section[@id="productOE"]/descendant::*/th[@scope="row"]/text()'))

oe

'13263335'

In [11]:
df_temp = pd.DataFrame([{'Url': list_url[i],
                         'OE_Numbers': oe,
                         'vehicle_url': vehicle_url,
                         'Src': src,
                         'status': 'ok'}])

df_temp

,Url,OE_Numbers,vehicle_url,Src,status
0,https://www.dormanproducts.com/p-137962-926-75...,13263335,https://www.dormanproducts.com/itemdetailapp.a...,[https://static.dormanproducts.com/images/prod...,ok

In [43]:
list_name = [name.text for name in html.xpath('//section[@id="productSpec"]/descendant::th')]
list_name = [x.strip() for x in list_name if x.strip()]

list_value = [value.text for value in html.xpath('///section[@id="productSpec"]/descendant::td')]

for name, value in zip(list_name, list_value):
    df_temp[name.lower()] = value
df_temp

,Url,OE_Numbers,vehicle_url,Src,status,color:,material:,mounting type:,package contents:,package quantity:,packaging type:,selling package quantity uom:,thickness:,universal or specific fit:
0,https://www.dormanproducts.com/p-137962-926-75...,13263335,https://www.dormanproducts.com/itemdetailapp.a...,[https://static.dormanproducts.com/images/prod...,ok,Black,Nylon,Press On,1 Blend Door Gear Kit,1,Box,Piece,14.75 mm,Specific

In [12]:
list_name = [name.text for name in html.xpath('//section[@id="productSpec"]/descendant::th')]
list_name = [x.strip() for x in list_name if x.strip()]

list_value = [value.text for value in html.xpath('///section[@id="productSpec"]/descendant::td')]
list_value

['Black',
 'Nylon',
 'Press On',
 '1 Blend Door Gear Kit',
 '1',
 'Box',
 'Piece',
 '14.75 mm',
 'Specific']

In [44]:
df = pd.concat([df, df_temp], ignore_index=True).fillna('')

In [45]:
df

,Url,Src,status,OE_Numbers,vehicle_url,color:,material:,mounting type:,package contents:,package quantity:,packaging type:,selling package quantity uom:,thickness:,universal or specific fit:
0,https://www.dormanproducts.com/p-137962-926-75...,[https://static.dormanproducts.com/images/prod...,ok,13263335,https://www.dormanproducts.com/itemdetailapp.a...,Black,Nylon,Press On,1 Blend Door Gear Kit,1,Box,Piece,14.75 mm,Specific