In [1]:
list_user_agent = ['Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.90 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.16 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.5672.63 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.5672.24 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.5615.49 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.5615.28 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.5563.64 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.5563.41 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.5563.19 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.5481.77 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.5481.30 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.5414.74 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.5414.25 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.5359.71 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.5359.22 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.5304.62 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.5304.18 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.5249.61 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.5249.21 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.5195.52 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.5195.19 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.79 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.29 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.20 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.24 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.27 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.15 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36',
                   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.20 Safari/537.36']

In [2]:
import pandas as pd
df_menu = pd.read_excel(r'C:\Users\YangTeng\Desktop\code\result--venv\2.Droman\2(2).Droman.xlsx', header=0)
list_vehicle_url = df_menu['vehicle_url'].to_list()

print('总数量：' + str(len(list_vehicle_url)))
list_vehicle_url

总数量：490

['https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=142600&PartType=HVAC%20Air%20Door%20Actuator%20Kit',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=70297&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=64690&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=65477&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=142539&PartType=HVAC%20Air%20Door%20Actuator%20Kit',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=129361&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=142537&PartType=HVAC%20Air%20Door%20Actuator%20Kit',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=107261&PartType=HVAC%20Blend%20Door%20Actuator%20Gear%20Kit',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=64242&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=76147&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=79755&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=142540&PartType=HVAC%20Air%20Door%20Actuator%20Kit',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=103305&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=142534&PartType=HVAC%20Air%20Door%20Actuator%20Kit',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=64244&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=64233&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=135060&PartType=HVAC%20Blend%20Door%20Repair%20Kit',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=87721&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=76224&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=142541&PartType=HVAC%20Air%20Door%20Actuator%20Kit',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=87706&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=64236&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=137962&PartType=HVAC%20Blend%20Door%20Actuator%20Gear%20Kit',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=142535&PartType=HVAC%20Air%20Door%20Actuator%20Kit',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=142533&PartType=HVAC%20Air%20Door%20Actuator%20Kit',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=130988&PartType=A%2FC%20Vacuum%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=65468&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=71274&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=71275&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=90027&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=76228&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=74516&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=81281&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=101706&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=105571&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=135203&PartType=HVAC%20Blend%20Door%20Repair%20Kit',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=76220&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=70485&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=97687&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=77402&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=142538&PartType=HVAC%20Air%20Door%20Actuator%20Kit',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=97857&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=107572&PartType=HVAC%20Blend%20Door%20Repair%20Kit',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=84138&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=101172&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=66347&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=96549&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=67500&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=75606&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=72826&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=91973&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=97844&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=66483&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=77692&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=97978&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=97856&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=100087&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=98705&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=97841&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=81082&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=102658&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=102043&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=97671&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=81068&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=98630&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=90890&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=76212&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=102775&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=64096&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=101684&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=77362&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=102529&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=77374&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=77226&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=94744&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=66356&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=81866&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=64237&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=125929&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=66367&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=126063&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=100238&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=98416&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=80133&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=99980&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=85964&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=78255&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=82033&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=85962&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=79224&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=142599&PartType=HVAC%20Air%20Door%20Actuator%20Kit',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=98697&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=99952&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=126293&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=84825&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=98635&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=90026&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=101171&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=84106&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=85968&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=97858&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=50932&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=77678&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=142536&PartType=HVAC%20Air%20Door%20Actuator%20Kit',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=101170&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=96555&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=96564&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=94491&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=76146&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=78252&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=98444&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=80117&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=96291&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=99966&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=66333&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=84826&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=97851&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=67319&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=99959&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=97842&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=97688&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=101174&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=104158&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=80240&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=98704&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=66338&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=64094&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=98698&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=80134&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=100239&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=99999&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=98690&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=76318&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=141220&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=96339&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=98736&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=76221&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=99968&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=76207&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=101175&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=75604&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=64691&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=106972&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=79235&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=106828&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=141208&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=78151&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=98723&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=79213&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=129362&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=98445&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=98742&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=143026&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=81076&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=80223&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=101173&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=75614&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=99955&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=96290&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=53635&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=67081&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=99954&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=81077&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=141181&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=90873&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=99960&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=11915&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=98650&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=34050&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=80908&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=97345&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=66365&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=44841&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=91947&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=87734&PartType=HVAC%20Heater%20Water%20Shut-Off%20Valve%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=102442&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=22254&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=20138&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=68422&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=46575&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=45683&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=66366&PartType=HVAC%20Air%20Door%20Actuator',
 'https://www.dormanproducts.com/itemdetailapp.aspx?ProductID=97843&PartType=HVAC%20Air%20Door%20Actuator',

In [3]:
df = pd.DataFrame(columns=['vehicle_url',
                           'Vehicle',
                           'status'])

df

Empty DataFrame
Columns: [vehicle_url, Vehicle, status]
Index: []

In [4]:
from selenium.webdriver import ChromeOptions
import random

import sys
sys.path.append('C:/Users/YangTeng/Desktop/venv/00.module')
import UA
import Proxy

# = = = = = = = = = = = = = = = = = =

from selenium.webdriver import ChromeOptions
option = ChromeOptions()
option.add_extension(Proxy.get_Proxy_Selenium())
option.add_experimental_option('useAutomationExtension', False)
option.add_argument('blink-settings=imagesEnabled=false')
option.add_argument('--disable-blink-features=AutomationControlled')
option.add_argument('--disable-dev-shm-usage')
option.add_argument('--disable-gpu')
option.add_experimental_option('excludeSwitches', ['enable-automation'])
# option.add_argument('--headless')
option.add_argument('--no-sandbox')
option.add_argument(UA.get_User_Agent_Selenium())
option.page_load_strategy = 'eager'

In [5]:
from selenium.webdriver import Chrome
from selenium.webdriver.chrome.service import Service

In [7]:
browser = Chrome(service=Service(r'C:\Users\YangTeng\Desktop\venv\chromedriver.exe'), options=option)

browser.maximize_window()

In [8]:
import time

i = 3

browser.get(list_vehicle_url[i])

time.sleep(5)

In [9]:
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.by import By

In [10]:
page = 0

dict_vehicle = {}
while True:
    print(page)
    wait = WebDriverWait(browser, 60)
    wait.until(EC.presence_of_element_located((By.XPATH, '//tr[@class="detail-app-row"]')))
    list_row = browser.find_elements(by=By.XPATH, value='//tr[@class="detail-app-row"]')
    
    for row in list_row:
        make = row.find_element(by=By.XPATH, value='./td[2]').text.strip()
        model = row.find_element(by=By.XPATH, value='./td[3]').text.strip()
        year = row.find_element(by=By.XPATH, value='./td[1]').text.strip()

        if make not in dict_vehicle:
            dict_vehicle[make] = {model: [year]}
        else:
            if model not in dict_vehicle[make]:
                dict_vehicle[make][model] = [year]
            else:
                dict_vehicle[make][model].append(year)
                
    list_next = browser.find_elements(by=By.XPATH, value='//a[@id="pagingBottom_nextButton"]')
    if len(list_next) == 0:
        break
    else:
        list_next[0].click()
        
    page += 50
    
list_vehicle = []
for make in dict_vehicle:
    for model in dict_vehicle[make]:
        list_year = list(set(dict_vehicle[make][model]))
        if len(list_year) == 1:
            list_vehicle.append(make + ' ' + model + ' ' + list_year[0])
        else:
            list_vehicle.append(make + ' ' + model + ' ' + min(list_year) + '-' + max(list_year))

vehicle = '\n'.join(list_vehicle)

print()
print(vehicle)

0

Jeep Liberty 2005-2007

In [11]:
df_temp = pd.DataFrame([{'vehicle_url': list_vehicle_url[i],
                         'Vehicle': vehicle,
                         'status': 'ok'}])

df = pd.concat([df, df_temp], ignore_index=True).fillna('')

df

,vehicle_url,Vehicle,status
0,https://www.dormanproducts.com/itemdetailapp.a...,Jeep Liberty 2005-2007,ok