In [13]:
import pandas as pd
df_menu = pd.read_excel('C:/Users/YangTeng/Desktop/数据源/10、FourSeasons/txt/blower/menu.xlsx', header=0)
list_part_number = df_menu['Part_Number'].to_list()

print('总数量：' + str(len(list_part_number)))
list_part_number

总数量：384

[58588,
 58587,
 58590,
 58596,
 58593,
 58615,
 58616,
 58619,
 58621,
 58620,
 58592,
 58622,
 58625,
 58631,
 58624,
 58640,
 58613,
 58635,
 58649,
 58643,
 58690,
 58650,
 58703,
 58704,
 58708,
 58705,
 58710,
 58706,
 58660,
 58770,
 58740,
 58779,
 58782,
 58786,
 58785,
 58787,
 58783,
 58789,
 58637,
 58791,
 58638,
 58793,
 58792,
 58711,
 58700,
 58784,
 58797,
 58796,
 58799,
 58798,
 58513,
 58894,
 58897,
 58896,
 58898,
 58964,
 58595,
 58982,
 67309,
 67360,
 67365,
 67381,
 67382,
 67387,
 67393,
 67396,
 67425,
 67426,
 67394,
 67377,
 67443,
 67448,
 58790,
 67445,
 67451,
 67388,
 67450,
 67473,
 67470,
 67488,
 67480,
 67558,
 67633,
 67643,
 67645,
 67554,
 67651,
 67666,
 67635,
 68021,
 68020,
 68022,
 68027,
 68028,
 68025,
 68159,
 68158,
 68161,
 68143,
 68166,
 20298,
 20299,
 20300,
 20301,
 20302,
 20303,
 20304,
 20305,
 20306,
 20307,
 20309,
 20311,
 20312,
 20313,
 20314,
 20315,
 20316,
 20317,
 20318,
 20319,
 20320,
 20321,
 20322,
 20323,
 20324,
 20325,
 20328,
 20331,
 20332,
 20336,
 20338,
 20339,
 20341,
 20342,
 20343,
 20344,
 20345,
 20346,
 20347,
 20348,
 20349,
 20350,
 20351,
 20352,
 20353,
 20354,
 20355,
 20356,
 20357,
 20358,
 20362,
 20363,
 20364,
 20365,
 20366,
 20368,
 20370,
 20371,
 20372,
 20373,
 20374,
 20375,
 20377,
 20378,
 20379,
 20380,
 20381,
 20382,
 20384,
 20385,
 20386,
 20387,
 20388,
 20389,
 20391,
 20392,
 20394,
 20395,
 20396,
 20397,
 20398,
 20399,
 20400,
 20401,
 20402,
 20403,
 20406,
 20407,
 20408,
 20409,
 20410,
 20411,
 20412,
 20413,
 20414,
 20415,
 20416,
 20417,
 20420,
 20421,
 20424,
 20427,
 20428,
 20429,
 20430,
 20431,
 20434,
 20435,
 20436,
 20437,
 20438,
 20439,
 20440,
 20441,
 20442,
 20444,
 20446,
 20447,
 20448,
 20449,
 20450,
 20451,
 20453,
 20454,
 20455,
 20456,
 20457,
 20459,
 20460,
 20461,
 20462,
 20463,
 20464,
 20465,
 20466,
 20467,
 20468,
 20469,
 20470,
 20471,
 20473,
 20475,
 20477,
 20478,
 20479,
 20481,
 20482,
 20483,
 20485,
 20486,
 20488,
 20490,
 20492,
 20495,
 20500,
 20503,
 20504,
 20505,
 20507,
 20510,
 20511,
 20512,
 20515,
 20518,
 20520,
 20521,
 20522,
 20524,
 20525,
 20525,
 20526,
 20527,
 20528,
 20530,
 20535,
 20540,
 20542,
 20544,
 20547,
 20553,
 20554,
 20555,
 20562,
 20564,
 20567,
 20568,
 20570,
 20571,
 20017,
 20041,
 20042,
 20043,
 20044,
 20045,
 20046,
 20061,
 20064,
 20065,
 20068,
 20069,
 20070,
 20072,
 20073,
 20074,
 20075,
 20076,
 20077,
 20079,
 20080,
 20081,
 20083,
 20085,
 20086,
 20087,
 20088,
 20089,
 20090,
 20091,
 20092,
 20093,
 20094,
 20095,
 20096,
 20097,
 20098,
 20099,
 20100,
 20101,
 20102,
 20103,
 20104,
 20107,
 20108,
 20109,
 20113,
 20116,
 20117,
 20118,
 20119,
 20122,
 20124,
 20128,
 20131,
 20133,
 20134,
 20135,
 20136,
 20137,
 20139,
 20140,
 20141,
 20143,
 20144,
 20145,
 20146,
 20147,
 20148,
 20149,
 20150,
 20151,
 20152,
 20153,
 20154,
 20155,
 20156,
 20157,
 20158,
 20159,
 20160,
 20161,
 20162,
 20163,
 20164,
 20165,
 20166,
 20167,
 20168,
 20169,
 20170,
 20171,
 20172,
 20173,
 20174,
 20175]

In [14]:
df = pd.DataFrame(columns=['Part_Number',
                           'Part_Type',
                           'POP',
                           'Per_Car',
                           'Vehicle',
                           'Src',
                           'status'])

df

Empty DataFrame
Columns: [Part_Number, Part_Type, POP, Per_Car, Vehicle, Src, status]
Index: []

In [15]:
import requests
import json
i = 1

resp = requests.get('https://ecatalog.smpcorp.com/v2/fs/api/part/partselect?part=' + str(list_part_number[i]) + '&func=PART').text
info = json.loads(resp)

info

{'pd': {'rowId': 1,
  'site': 'FS',
  'webBase': '58587',
  'brand': 'FS',
  'basePart': '58587',
  'partDesc_en': 'Compressor New /Sanden 5',
  'partLongDesc_en': 'New Sanden/Sankyo SD508 Compressor w/ Clutch',
  'pop': 'F',
  'partComment': None,
  'qtyEach': 1,
  'webColumn_Id': None,
  'categoryName_en': None,
  'vehicleId': None,
  'mfg': None,
  'mfG_Part': None,
  'maxRows': 1,
  'brandLink': None,
  'imageUrl': None},
 'pp': {'buyersGuides': [],
  'partSpecs': [{'attributeCode': '571',
    'attributeValue': 18160,
    'attributeSort': 1,
    'attributeName_en': 'Type',
    'siteValue_en': 'Sanden/Sankyo'},
   {'attributeCode': '329',
    'attributeValue': 18163,
    'attributeSort': 2,
    'attributeName_en': 'Model',
    'siteValue_en': 'SD508'},
   {'attributeCode': '217',
    'attributeValue': 2028,
    'attributeSort': 3,
    'attributeName_en': 'Groove',
    'siteValue_en': '2'},
   {'attributeCode': '1668',
    'attributeValue': 28805,
    'attributeSort': 4,
    'attributeName_en': 'Pulley Diameter MM',
    'siteValue_en': '130.05'},
   {'attributeCode': '71',
    'attributeValue': 651,
    'attributeSort': 5,
    'attributeName_en': 'Coil Voltage',
    'siteValue_en': '12'},
   {'attributeCode': '604',
    'attributeValue': 10122,
    'attributeSort': 6,
    'attributeName_en': 'Compressor Head Type',
    'siteValue_en': 'C'},
   {'attributeCode': '363',
    'attributeValue': 9752,
    'attributeSort': 7,
    'attributeName_en': 'Mount Type',
    'siteValue_en': 'Ear Mount'},
   {'attributeCode': '99',
    'attributeValue': 26757,
    'attributeSort': 8,
    'attributeName_en': 'Connector Type',
    'siteValue_en': 'Bullet'},
   {'attributeCode': '1830',
    'attributeValue': 18705,
    'attributeSort': 9,
    'attributeName_en': 'Oil Quantity',
    'siteValue_en': '3 oz'},
   {'attributeCode': '386',
    'attributeValue': 5311,
    'attributeSort': 10,
    'attributeName_en': 'Oil Type',
    'siteValue_en': 'PAG 100'},
   {'attributeCode': '1831',
    'attributeValue': 29395,
    'attributeSort': 11,
    'attributeName_en': 'Alt Compeditor Model#',
    'siteValue_en': '4525, 9205, 9505, 9505'},
   {'attributeCode': '1832',
    'attributeValue': 16477,
    'attributeSort': 12,
    'attributeName_en': 'Electronic Control Valve',
    'siteValue_en': 'No'},
   {'attributeCode': '473',
    'attributeValue': 3477,
    'attributeSort': 12,
    'attributeName_en': 'Refrigerant Type',
    'siteValue_en': 'R134a'},
   {'attributeCode': '1748',
    'attributeValue': 16177,
    'attributeSort': 13,
    'attributeName_en': 'Pulley Diameter IN',
    'siteValue_en': '5.125'},
   {'attributeCode': '1724',
    'attributeValue': 18584,
    'attributeSort': 14,
    'attributeName_en': 'O-Ring A Number/Desc',
    'siteValue_en': '24111 / Mini York Teflon Seal O-Ring'},
   {'attributeCode': '1725',
    'attributeValue': 2028,
    'attributeSort': 15,
    'attributeName_en': 'O-Ring A Quantity',
    'siteValue_en': '2'},
   {'attributeCode': '1533',
    'attributeValue': 10082,
    'attributeSort': 16,
    'attributeName_en': 'O-Ring B Number/Desc',
    'siteValue_en': 'N/A'},
   {'attributeCode': '1580',
    'attributeValue': 10082,
    'attributeSort': 17,
    'attributeName_en': 'O-Ring B Quantity',
    'siteValue_en': 'N/A'}],
  'imageUrls': [],
  'relatedParts': [],
  'relatedCategories': None,
  'fandB': [{'basePart': '58587',
    'fbId': '8177',
    'fbDesc': 'Our products are engineered and tested to provide years of trouble free operation.  Backed by over 50 years of mobile a/c experience, fix it once and fix it right with Four Seasons.',
    'taB_Type': 'F&B Heading',
    'assetSort': 1,
    'digiSort': 0},
   {'basePart': '58587',
    'fbId': '196003',
    'fbDesc': 'New Compressors meet or exceed OE specifications',
    'taB_Type': 'F&B Details',
    'assetSort': 8,
    'digiSort': 1},
   {'basePart': '58587',
    'fbId': '195999',
    'fbDesc': 'New Compressors are validated for the equivalent of 100,000 miles',
    'taB_Type': 'F&B Details',
    'assetSort': 8,
    'digiSort': 2},
   {'basePart': '58587',
    'fbId': '196000',
    'fbDesc': 'New Compressors come pre-charged with 3 ounces of PAG oil for R134a or R1234yf applications',
    'taB_Type': 'F&B Details',
    'assetSort': 8,
    'digiSort': 3},
   {'basePart': '58587',
    'fbId': '196001',
    'fbDesc': 'New Compressors come with direct fit connectors for ease of installation and to help eliminate splicing',
    'taB_Type': 'F&B Details',
    'assetSort': 8,
    'digiSort': 4},
   {'basePart': '58587',
    'fbId': '196002',
    'fbDesc': 'New Compressors come with the R12/R134A/1234yf required o-rings /sealing washers to install the compressor',
    'taB_Type': 'F&B Details',
    'assetSort': 8,
    'digiSort': 5},
   {'basePart': '58587',
    'fbId': '195998',
    'fbDesc': 'New Compressors are built in a ISO9001:2015 Certified facility. These facilities go through several audits to ensure quality standards in the manufacturing process.',
    'taB_Type': 'F&B Details',
    'assetSort': 8,
    'digiSort': 6}],
  'digiAssests': [{'asset_ID': 2,
    'assetName': 'Installation Instructions',
    'basePart': '58587',
    'fileName': '86953142.pdf',
    'fileURL': 'http://eaccess.smpcorp.com/eCatalogs/Downloads/FS/86953142.pdf',
    'comment_ID': '12117',
    'comment': 'Compressor Installation/Warranty Procedures',
    'assetSort': 2,
    'digiSort': 0,
    'videoImage': None},
   {'asset_ID': 7,
    'assetName': 'Videos',
    'basePart': '58587',
    'fileName': 'Cleaning The System',
    'fileURL': 'https://youtube.com/embed/jHg-QilTCAU',
    'comment_ID': '12093',
    'comment': 'Cleaning The System',
    'assetSort': 7,
    'digiSort': 0,
    'videoImage': None},
   {'asset_ID': 7,
    'assetName': 'Videos',
    'basePart': '58587',
    'fileName': 'Compressor Installation Quick Tip ',
    'fileURL': 'https://youtube.com/embed/p_VcWHRTlfM',
    'comment_ID': '138875',
    'comment': 'Compressor Installation Quick Tip ',
    'assetSort': 7,
    'digiSort': 0,
    'videoImage': None},
   {'asset_ID': 7,
    'assetName': 'Videos',
    'basePart': '58587',
    'fileName': 'Impact of Airflow on HVAC Performance',
    'fileURL': 'https://youtube.com/embed/l-dfJQONdy8',
    'comment_ID': '138880',
    'comment': 'Impact of Airflow on HVAC Performance',
    'assetSort': 7,
    'digiSort': 0,
    'videoImage': None},
   {'asset_ID': 7,
    'assetName': 'Videos',
    'basePart': '58587',
    'fileName': 'SMP Engineering',
    'fileURL': 'http://youtube.com/embed/z33qr7b3MWU',
    'comment_ID': '138882',
    'comment': 'SMP Engineering',
    'assetSort': 7,
    'digiSort': 0,
    'videoImage': None},
   {'asset_ID': 7,
    'assetName': 'Videos',
    'basePart': '58587',
    'fileName': 'SMP Facilities',
    'fileURL': 'https://youtube.com/embed/LMncDliQK_4',
    'comment_ID': '138883',
    'comment': 'SMP Facilities',
    'assetSort': 7,
    'digiSort': 0,
    'videoImage': None},
   {'asset_ID': 7,
    'assetName': 'Videos',
    'basePart': '58587',
    'fileName': 'SMP Facilities (Quick Tour)',
    'fileURL': 'https://youtube.com/embed/mGxHhNBSvjA',
    'comment_ID': '138884',
    'comment': 'SMP Facilities (Quick Tour)',
    'assetSort': 7,
    'digiSort': 0,
    'videoImage': None},
   {'asset_ID': 7,
    'assetName': 'Videos',
    'basePart': '58587',
    'fileName': 'Temp Testing TXV System ',
    'fileURL': 'https://youtube.com/embed/wF37ihNBXq8',
    'comment_ID': '138887',
    'comment': 'Temp Testing TXV System ',
    'assetSort': 7,
    'digiSort': 0,
    'videoImage': None},
   {'asset_ID': 7,
    'assetName': 'Videos',
    'basePart': '58587',
    'fileName': 'Temperature Testing',
    'fileURL': 'https://youtube.com/embed/KZmg4LeVcCo',
    'comment_ID': '138888',
    'comment': 'Temperature Testing',
    'assetSort': 7,
    'digiSort': 0,
    'videoImage': None},
   {'asset_ID': 7,
    'assetName': 'Videos',
    'basePart': '58587',
    'fileName': 'AC Compressor Lubrication Quick Tip\r\n',
    'fileURL': 'https://www.youtube.com/watch?v=DLzPduYVYRE',
    'comment_ID': '260141',
    'comment': 'AC Compressor Lubrication Quick Tip\r\n',
    'assetSort': 7,
    'digiSort': 0,
    'videoImage': None},
   {'asset_ID': 7,
    'assetName': 'Videos',
    'basePart': '58587',
    'fileName': 'AC Compressor Install Tips',
    'fileURL': 'https://www.youtube.com/watch?v=03AIoW-VYdA',
    'comment_ID': '304012',
    'comment': 'AC Compressor Install Tips',
    'assetSort': 7,
    'digiSort': 0,
    'videoImage': None},
   {'asset_ID': 7,
    'assetName': 'Videos',
    'basePart': '58587',
    'fileName': 'Compressor Lubrication Tips',
    'fileURL': 'https://www.youtube.com/watch?v=IBiLacwbaOw',
    'comment_ID': '304014',
    'comment': 'Compressor Lubrication Tips',
    'assetSort': 7,
    'digiSort': 0,
    'videoImage': None},
   {'asset_ID': 7,
    'assetName': 'Videos',
    'basePart': '58587',
    'fileName': 'Compressor Shipping Labels',
    'fileURL': 'https://www.youtube.com/watch?v=XAD5mda5800',
    'comment_ID': '304015',
    'comment': 'Compressor Shipping Labels',
    'assetSort': 7,
    'digiSort': 0,
    'videoImage': None},
   {'asset_ID': 7,
    'assetName': 'Videos',
    'basePart': '58587',
    'fileName': 'SMP Mobile Parts App 3.0',
    'fileURL': 'https://www.youtube.com/watch?v=HvA2lY15M28',
    'comment_ID': '304016',
    'comment': 'SMP Mobile Parts App 3.0',
    'assetSort': 7,
    'digiSort': 0,
    'videoImage': None},
   {'asset_ID': 7,
    'assetName': 'Videos',
    'basePart': '58587',
    'fileName': "Top 10 FAQs: #1: Why can't I replace just the compressor?",
    'fileURL': 'https://www.youtube.com/watch?v=g0SuQAD1ssw',
    'comment_ID': '304017',
    'comment': "Top 10 FAQs: #1: Why can't I replace just the compressor?",
    'assetSort': 7,
    'digiSort': 0,
    'videoImage': None}],
  'categories': [{'basePart': '58587',
    'webLayout_ID': 1900,
    'categoryName_en': 'Compressors - New',
    'prodCategory_ASort': 11500}],
  'crossRef': None,
  'completeRepair': {'serviceParts': [],
   'serviceSpec': [{'serviceName': 'Fuel Filter Flush (Required)'},
    {'serviceName': 'Oil Change (Required)'}]}}}

In [16]:
part_type = info['pp']['categories'][0]['categoryName_en']

part_type

'Compressors - New'

In [17]:
pop = info['pd']['pop']

pop

'F'

In [18]:
per_car = info['pd']['qtyEach']

per_car

1

In [19]:
list_vehicle = [vehicle['buyersGuideDesc'] for vehicle in info['pp']['buyersGuides']]
vehicle = '\n'.join(list_vehicle)

vehicle

''

In [20]:
details = info['pp']['partSpecs']

details

[{'attributeCode': '571',
  'attributeValue': 18160,
  'attributeSort': 1,
  'attributeName_en': 'Type',
  'siteValue_en': 'Sanden/Sankyo'},
 {'attributeCode': '329',
  'attributeValue': 18163,
  'attributeSort': 2,
  'attributeName_en': 'Model',
  'siteValue_en': 'SD508'},
 {'attributeCode': '217',
  'attributeValue': 2028,
  'attributeSort': 3,
  'attributeName_en': 'Groove',
  'siteValue_en': '2'},
 {'attributeCode': '1668',
  'attributeValue': 28805,
  'attributeSort': 4,
  'attributeName_en': 'Pulley Diameter MM',
  'siteValue_en': '130.05'},
 {'attributeCode': '71',
  'attributeValue': 651,
  'attributeSort': 5,
  'attributeName_en': 'Coil Voltage',
  'siteValue_en': '12'},
 {'attributeCode': '604',
  'attributeValue': 10122,
  'attributeSort': 6,
  'attributeName_en': 'Compressor Head Type',
  'siteValue_en': 'C'},
 {'attributeCode': '363',
  'attributeValue': 9752,
  'attributeSort': 7,
  'attributeName_en': 'Mount Type',
  'siteValue_en': 'Ear Mount'},
 {'attributeCode': '99',
  'attributeValue': 26757,
  'attributeSort': 8,
  'attributeName_en': 'Connector Type',
  'siteValue_en': 'Bullet'},
 {'attributeCode': '1830',
  'attributeValue': 18705,
  'attributeSort': 9,
  'attributeName_en': 'Oil Quantity',
  'siteValue_en': '3 oz'},
 {'attributeCode': '386',
  'attributeValue': 5311,
  'attributeSort': 10,
  'attributeName_en': 'Oil Type',
  'siteValue_en': 'PAG 100'},
 {'attributeCode': '1831',
  'attributeValue': 29395,
  'attributeSort': 11,
  'attributeName_en': 'Alt Compeditor Model#',
  'siteValue_en': '4525, 9205, 9505, 9505'},
 {'attributeCode': '1832',
  'attributeValue': 16477,
  'attributeSort': 12,
  'attributeName_en': 'Electronic Control Valve',
  'siteValue_en': 'No'},
 {'attributeCode': '473',
  'attributeValue': 3477,
  'attributeSort': 12,
  'attributeName_en': 'Refrigerant Type',
  'siteValue_en': 'R134a'},
 {'attributeCode': '1748',
  'attributeValue': 16177,
  'attributeSort': 13,
  'attributeName_en': 'Pulley Diameter IN',
  'siteValue_en': '5.125'},
 {'attributeCode': '1724',
  'attributeValue': 18584,
  'attributeSort': 14,
  'attributeName_en': 'O-Ring A Number/Desc',
  'siteValue_en': '24111 / Mini York Teflon Seal O-Ring'},
 {'attributeCode': '1725',
  'attributeValue': 2028,
  'attributeSort': 15,
  'attributeName_en': 'O-Ring A Quantity',
  'siteValue_en': '2'},
 {'attributeCode': '1533',
  'attributeValue': 10082,
  'attributeSort': 16,
  'attributeName_en': 'O-Ring B Number/Desc',
  'siteValue_en': 'N/A'},
 {'attributeCode': '1580',
  'attributeValue': 10082,
  'attributeSort': 17,
  'attributeName_en': 'O-Ring B Quantity',
  'siteValue_en': 'N/A'}]

In [21]:
brand = info['pd']['brand']

brand

'FS'

In [22]:
resp = requests.get('https://ecatalog.smpcorp.com/v2/fs/api/image/getallimages?partNum=' + str(list_part_number[i]) + '&brand=' + brand + '&zoomFactor_sm=75&zoomFactor_md=360&zoomFactor_bg=960').text
info = json.loads(resp)

info

[{'image_Name': 'D4XJtWJBxGSpasXdaqR1Fg%3D%3D',
  'image_SM_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=Pl+SkO/BiZFpHAX5LVIQjT9FNpDfGKFIWs34AmcG1EkFoZj0BakHNJXuRwb48cnBrm+ZHodTWPuhIKBw3J5SZ5iH9+8ykTJFSKEulrQ0hiWTskhDbDVIOt4K7Mm/YEv3m/CH1/uYPCgXGfdCmo4YlLSCFlglY/QZdAtiXuLIU+Di9hPdc4cHpD5q/MVZyiBK',
  'image_MD_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=Pl+SkO/BiZFpHAX5LVIQjT9FNpDfGKFIBku710yGpH+/i0CkSeelGVJhA4N4ioGvbEHUQlckYE7y916PDj4mUplpjLqJxiUyNc0Dfr4BAXPekNlQ51Q7yIznwcghdmhavbavYiSVAdwf+9wZqa98qjQzalYD0S+hXFCrNkIzF/P/ZDIxFBHQdJiQJSOi3Hj/',
  'image_BG_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=Pl+SkO/BiZFpHAX5LVIQjSYF4nkLByFFki+PA/U85oaPkgNenimAle72HZkm08flMYvVb8ruU/a2jlDyZ/9SFhHKSDnV/vfUm++2cf2MyJSTHiO+uZMQDMRJmK/E5kGqgMS+q/NNn547DcAIwETg08UMBA7v+iEY0bjxVYDX/i/b+dvBdWFM0Q=='},
 {'image_Name': 'Wl8pELztlmfVKQCkNFhMog%3D%3D',
  'image_SM_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=Pl+SkO/BiZFpHAX5LVIQjT9FNpDfGKFIWs34AmcG1EkFoZj0BakHNK3D7Caf0gdPi7h30WzXb4LOnVUip04BiJTs5tLYVtf0Jv0YyvK/rWdJmHQGKl7o+TW7k1Hj4TTuy5K/cNQbQ1spu2svsSDQ4m5fEIOJJ1pBAh3VdoXCgIKRAoSvbPVOnROHkC35aSpPiElvruRbAuc=',
  'image_MD_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=Pl+SkO/BiZFpHAX5LVIQjT9FNpDfGKFIBku710yGpH+/i0CkSeelGTLKcRxLwQ+1rm+ZHodTWPuhIKBw3J5SZ5iH9+8ykTJFSKEulrQ0hiWTskhDbDVIOt4K7Mm/YEv3m/CH1/uYPCgXGfdCmo4YlLSCFlglY/QZdAtiXuLIU+Di9hPdc4cHpD5q/MVZyiBK',
  'image_BG_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=Pl+SkO/BiZFpHAX5LVIQjSYF4nkLByFFki+PA/U85ob5JG6L5fB2ll6DrKAJfZjYMoN++3vibKFGVC+8Va8jLaI8gQqRXhksVqg+QadFzZ6AfnnMwvAWvxs/HBA23UPYMJi1dAphBIcr+m7fx4OW9FFddXEVnVkamMa1hEP2D4HAV7mq1ZHAauxDDtSObvr3'},
 {'image_Name': 'Zz5s2oJGp%2FH%2F16DiKxVqRw%3D%3D',
  'image_SM_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=Pl+SkO/BiZFpHAX5LVIQjT9FNpDfGKFIWs34AmcG1EkFoZj0BakHNE9EIzFbSCsdB6ex4HxPMh4yg377e+JsoUZUL7xVryMtojyBCpFeGSxWqD5Bp0XNnoB+eczC8Ba/Gz8cEDbdQ9gwmLV0CmEEhyv6bt/Hg5b0UV11cRWdWRqYxrWEQ/YPgcBXuarVkcBq7EMO1I5u+vc=',
  'image_MD_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=Pl+SkO/BiZFpHAX5LVIQjT9FNpDfGKFIBku710yGpH+/i0CkSeelGdbsDOQ7mvjQ7vYdmSbTx+Uxi9Vvyu5T9raOUPJn/1IWEcpIOdX+99Sb77Zx/YzIlJMeI765kxAMxEmYr8TmQaqAxL6r802fnjsNwAjARODTxQwEDu/6IRjRuPFVgNf+L9v528F1YUzR',
  'image_BG_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=Pl+SkO/BiZFpHAX5LVIQjSYF4nkLByFFki+PA/U85obMBJcGAxLYr/FN3woIsCq7bEHUQlckYE7y916PDj4mUplpjLqJxiUyNc0Dfr4BAXPekNlQ51Q7yIznwcghdmhavbavYiSVAdwf+9wZqa98qjQzalYD0S+hXFCrNkIzF/P/ZDIxFBHQdJiQJSOi3Hj/'},
 {'image_Name': 'Zz5s2oJGp%2FGD6QTWD6TjFA%3D%3D',
  'image_SM_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=Pl+SkO/BiZFpHAX5LVIQjT9FNpDfGKFIWs34AmcG1EkFoZj0BakHNE9EIzFbSCsdpTAt1e6h9wYyg377e+JsoUZUL7xVryMtojyBCpFeGSxWqD5Bp0XNnoB+eczC8Ba/Gz8cEDbdQ9gwmLV0CmEEhyv6bt/Hg5b0UV11cRWdWRqYxrWEQ/YPgcBXuarVkcBq7EMO1I5u+vc=',
  'image_MD_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=Pl+SkO/BiZFpHAX5LVIQjT9FNpDfGKFIBku710yGpH+/i0CkSeelGcgLlsH3ZGvI7vYdmSbTx+Uxi9Vvyu5T9raOUPJn/1IWEcpIOdX+99Sb77Zx/YzIlJMeI765kxAMxEmYr8TmQaqAxL6r802fnjsNwAjARODTxQwEDu/6IRjRuPFVgNf+L9v528F1YUzR',
  'image_BG_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=Pl+SkO/BiZFpHAX5LVIQjSYF4nkLByFFki+PA/U85obMBJcGAxLYryTW8dFA66nUbEHUQlckYE7y916PDj4mUplpjLqJxiUyNc0Dfr4BAXPekNlQ51Q7yIznwcghdmhavbavYiSVAdwf+9wZqa98qjQzalYD0S+hXFCrNkIzF/P/ZDIxFBHQdJiQJSOi3Hj/'},
 {'image_Name': 'UwWxZb7L0OAM%2FuXX%2FprS9Q%3D%3D',
  'image_SM_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=Pl+SkO/BiZFpHAX5LVIQjT9FNpDfGKFIWs34AmcG1EkFoZj0BakHNK0yGAR/Lb/L5rLkiyHdwiDOnVUip04BiJTs5tLYVtf0Jv0YyvK/rWdJmHQGKl7o+TW7k1Hj4TTuy5K/cNQbQ1spu2svsSDQ4m5fEIOJJ1pBAh3VdoXCgIKRAoSvbPVOnROHkC35aSpPiElvruRbAuc=',
  'image_MD_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=Pl+SkO/BiZFpHAX5LVIQjT9FNpDfGKFIBku710yGpH+/i0CkSeelGYLmtPeWudBHrm+ZHodTWPuhIKBw3J5SZ5iH9+8ykTJFSKEulrQ0hiWTskhDbDVIOt4K7Mm/YEv3m/CH1/uYPCgXGfdCmo4YlLSCFlglY/QZdAtiXuLIU+Di9hPdc4cHpD5q/MVZyiBK',
  'image_BG_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=Pl+SkO/BiZFpHAX5LVIQjSYF4nkLByFFki+PA/U85ob3YeE4U0Edn+kBDhZrewGmMoN++3vibKFGVC+8Va8jLaI8gQqRXhksVqg+QadFzZ6AfnnMwvAWvxs/HBA23UPYMJi1dAphBIcr+m7fx4OW9FFddXEVnVkamMa1hEP2D4HAV7mq1ZHAauxDDtSObvr3'},
 {'image_Name': 'Y64DMgMBNY7OKVCDgULJDg%3D%3D',
  'image_SM_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=Pl+SkO/BiZFpHAX5LVIQjT9FNpDfGKFIWs34AmcG1EkFoZj0BakHNH10kgwZ/p9fpTSKn1/x0z0yg377e+JsoUZUL7xVryMtojyBCpFeGSxWqD5Bp0XNnoB+eczC8Ba/Gz8cEDbdQ9gwmLV0CmEEhyv6bt/Hg5b0UV11cRWdWRqYxrWEQ/YPgcBXuarVkcBq7EMO1I5u+vc=',
  'image_MD_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=Pl+SkO/BiZFpHAX5LVIQjT9FNpDfGKFIBku710yGpH+/i0CkSeelGXF3Mbk2UOOf7vYdmSbTx+Uxi9Vvyu5T9raOUPJn/1IWEcpIOdX+99Sb77Zx/YzIlJMeI765kxAMxEmYr8TmQaqAxL6r802fnjsNwAjARODTxQwEDu/6IRjRuPFVgNf+L9v528F1YUzR',
  'image_BG_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=Pl+SkO/BiZFpHAX5LVIQjSYF4nkLByFFki+PA/U85oYjSzd/2r90zi6xicFUkyzzbEHUQlckYE7y916PDj4mUplpjLqJxiUyNc0Dfr4BAXPekNlQ51Q7yIznwcghdmhavbavYiSVAdwf+9wZqa98qjQzalYD0S+hXFCrNkIzF/P/ZDIxFBHQdJiQJSOi3Hj/'},
 {'image_Name': 'Gc9kULyMdyKfnzhfxtEJHg%3D%3D',
  'image_SM_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=Pl+SkO/BiZFpHAX5LVIQjT9FNpDfGKFIWs34AmcG1EkFoZj0BakHNAnPz/T2gOKhpTSKn1/x0z0yg377e+JsoUZUL7xVryMtojyBCpFeGSxWqD5Bp0XNnoB+eczC8Ba/Gz8cEDbdQ9gwmLV0CmEEhyv6bt/Hg5b0UV11cRWdWRqYxrWEQ/YPgcBXuarVkcBq7EMO1I5u+vc=',
  'image_MD_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=Pl+SkO/BiZFpHAX5LVIQjT9FNpDfGKFIBku710yGpH+/i0CkSeelGRQO/6SmVAVv7vYdmSbTx+Uxi9Vvyu5T9raOUPJn/1IWEcpIOdX+99Sb77Zx/YzIlJMeI765kxAMxEmYr8TmQaqAxL6r802fnjsNwAjARODTxQwEDu/6IRjRuPFVgNf+L9v528F1YUzR',
  'image_BG_Url': 'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=Pl+SkO/BiZFpHAX5LVIQjSYF4nkLByFFki+PA/U85oZrbeQvkkFfMy6xicFUkyzzbEHUQlckYE7y916PDj4mUplpjLqJxiUyNc0Dfr4BAXPekNlQ51Q7yIznwcghdmhavbavYiSVAdwf+9wZqa98qjQzalYD0S+hXFCrNkIzF/P/ZDIxFBHQdJiQJSOi3Hj/'}]

In [23]:
if len(info) == 0:
    src = ''
else:
    src = info[0]['image_BG_Url']

src

'https://extapi.smpcorp.com/ihgs/imagehandlergs.ashx?p1=Pl+SkO/BiZFpHAX5LVIQjSYF4nkLByFFki+PA/U85oaPkgNenimAle72HZkm08flMYvVb8ruU/a2jlDyZ/9SFhHKSDnV/vfUm++2cf2MyJSTHiO+uZMQDMRJmK/E5kGqgMS+q/NNn547DcAIwETg08UMBA7v+iEY0bjxVYDX/i/b+dvBdWFM0Q=='

In [24]:
df_temp = pd.DataFrame([{'Part_Number': list_part_number[i],
                         'Part_Type': part_type,
                         'POP': pop,
                         'Per_Car': per_car,
                         'Vehicle': vehicle,
                         'Src': src,
                         'status': 'ok'}])

df_temp

,Part_Number,Part_Type,POP,Per_Car,Vehicle,Src,status
0,58587,Compressors - New,F,1,,https://extapi.smpcorp.com/ihgs/imagehandlergs...,ok

In [25]:
for name_value in details:
    df_temp[name_value['attributeName_en'].lower()] = name_value['siteValue_en']
    
df = pd.concat([df, df_temp], ignore_index=True).fillna('')

df

,Part_Number,Part_Type,POP,Per_Car,Vehicle,Src,status,type,model,groove,...,oil quantity,oil type,alt compeditor model#,electronic control valve,refrigerant type,pulley diameter in,o-ring a number/desc,o-ring a quantity,o-ring b number/desc,o-ring b quantity
0,58587,Compressors - New,F,1,,https://extapi.smpcorp.com/ihgs/imagehandlergs...,ok,Sanden/Sankyo,SD508,2,...,3 oz,PAG 100,"4525, 9205, 9505, 9505",No,R134a,5.125,24111 / Mini York Teflon Seal O-Ring,2,N/A,N/A