In [2]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
from lxml import etree

ua = pd.read_excel(r'C:\Users\YangTeng\Downloads\爬虫\UAC\menu.xlsx', header=0)
# ua_no = ua['No']
# ua_no
ua_Part_Number = ua['Part_Number'] 
ua_Part_Number

0        15 20061
1        15 20062
2        15 20162
3       15 20228Z
4       15 20234Z
          ...
2870      YCC 603
2871      YCC 604
2872      YCC 607
2873      YCC 613
2874      YCC 625
Name: Part_Number, Length: 2875, dtype: object

In [4]:
ua_url = ua['OE链接']
ua_url

0       https://uacparts.com/Catalog/CrossReference?__...
1       https://uacparts.com/Catalog/CrossReference?__...
2       https://uacparts.com/Catalog/CrossReference?__...
3       https://uacparts.com/Catalog/CrossReference?__...
4       https://uacparts.com/Catalog/CrossReference?__...
                              ...
2870    https://uacparts.com/Catalog/CrossReference?__...
2871    https://uacparts.com/Catalog/CrossReference?__...
2872    https://uacparts.com/Catalog/CrossReference?__...
2873    https://uacparts.com/Catalog/CrossReference?__...
2874    https://uacparts.com/Catalog/CrossReference?__...
Name: OE链接, Length: 2875, dtype: object

In [32]:
df = pd.DataFrame(columns=['Part_Number',
                           'OE',
                           'status'])

df

Empty DataFrame
Columns: [Part_Number, OE, status]
Index: []

In [40]:
for j in range(2500,2875):
#     print(j)

    url = ua_url[j]
    
    resp = requests.get(url).text
    soup = BeautifulSoup(resp, 'lxml')
    html = etree.HTML(str(soup))
    
    df_temp = pd.DataFrame([{'Part_Number',
                             'OE',
                             'status'}])
    
    list = html.xpath('//tr[@class="awe-row"]/td')
#     print(list[1].text)
#     print(len(list))

    list_name = [name.text for name in html.xpath('//tr[@class="awe-row"]/td[1]')]
    list_name
    list_value = [name.text for name in html.xpath('//tr[@class="awe-row"]/td[2]')]
    list_value
    
#     print(list_name)
    
    dict_band = {}
    for i in range(len(list_name)):

        if list_name[i] not in dict_band:
            dict_band[list_name[i]] = [list_value[i]]
        else:
            dict_band[list_name[i]].append(list_value[i])
#         print(dict_band)
    
    list_OE = []
    list_OE.append(dict_band)
    print(j)
    print(list_OE)
    
#     list_fourseason=[]
#     for i in range(len(list_name)):
        
#         if list_name[i]=='Four Seasons':
            
#             list_fourseason.append(list_value[i])
            
            
    df_temp = pd.DataFrame([{'Part_Number': ua_Part_Number[j],
                 'OE':list_OE ,
                 'status': 'ok'}])
    df = pd.concat([df, df_temp], ignore_index=True).fillna('')
    
list_fourseason
df

2500
[{'Airpro': ['204529'], 'CARLISLE': ['3014241'], 'MEI': ['56642'], 'Omega': ['2010086'], 'Sanden': ['4529', '6642'], 'Trad Automotive': ['C2257'], 'TTAC': ['3004116']}]
2501
[{'CARLISLE': ['3014250', '3014251'], 'Omega': ['2006649', '2006649AM'], 'Ranshu': ['14SD6649NC', '14SD6649NEW'], 'Sanden': ['6649'], 'Trad Automotive': ['C2977']}]
2502
[{'CARLISLE': ['3014250', '3014251'], 'Omega': ['2006649', '2006649AM'], 'Ranshu': ['14SD6649NC', '14SD6649NEW'], 'Sanden': ['6649'], 'Trad Automotive': ['C2977']}]
2503
[{'CARLISLE': ['3014260'], 'Claas': ['6258771'], 'Omega': ['2010066'], 'Sanden': ['4531', '6651'], 'Sunair': ['CO2304CA'], 'TruckAir': ['033444']}]
2504
[{'CARLISLE': ['3014271'], 'Sanden': ['6657'], 'Trad Automotive': ['C2258']}]
2505
[{'CARLISLE': ['3014281'], 'Omega': ['2010048'], 'Sanden': ['6658'], 'Trad Automotive': ['C2259']}]
2506
[{'Airpro': ['204510'], 'Bergstrom': ['525692'], 'CARLISLE': ['3012241', '3014290'], 'Compressor Works': ['618591'], 'Deutz-Allis': ['72239750'], 'Fendt': ['D45080062'], 'Ford New Holland': ['86508521'], 'Freightliner': ['304052', 'ABPN83304052', 'SKI6664'], 'Frigette': ['204865'], 'Global Parts Distributors': ['5511566', '6511566', '7511566'], 'Kenworth': ['4510SAN', 'LE1035', 'LE1135'], 'Kysor': ['1402028'], 'Mack': ['4510SAN'], 'MEI': ['54510', '5785'], 'NAPA': ['967088', 'TEM967088'], 'Omega': ['2006626', '2010074', '2010186', '2010186AM', '2010186S', '2018024', '2018024AM'], 'Panafrio': ['2013331'], 'Ranshu': ['14SD4509', '14SD4509NC', '14SD4509NEW', '14SD4510', '14SD4510NEW', '14SD6664', '14SD6664NEW'], 'Red Dot': ['75R8382'], 'Sanden': ['4509', '4510', '6626', '6664', '6668'], 'Sunair': ['CO2045CA'], 'Trad Automotive': ['C1156', 'C1919', 'C2597'], 'Visteon': ['010183'], 'Volvo': ['11104512', '4510SAN', '85100888'], 'Western Star': ['4510SAN']}]
2507
[{'AC Delco': ['1521821'], 'Airpro': ['204506', '204507'], 'CARLISLE': ['3012221', '3014300'], 'Compressor Works': ['618666'], 'Four Seasons': ['57666', '58666'], 'Frigette': ['204866'], 'Global Parts Distributors': ['5511579', '5512733', '6511579', '6512733', '7511579', '7512733', '7811579'], 'Kenworth': ['6665SAN'], 'MEI': ['5774'], 'Omega': ['2010183', '2010183AM', '2014093', '2016627'], 'Ranshu': ['14SD4741', '14SD4741NEW'], 'Red Dot': ['75R8384'], 'Sanden': ['4506', '4507', '6627', '6665'], 'Sunair': ['CO2046CA'], 'Trad Automotive': ['C1157'], 'TTAC': ['3005075'], 'Visteon': ['010179'], 'Volvo': ['1593151']}]
2508
[{'Airpro': ['204527'], 'CARLISLE': ['3014310'], 'MEI': ['5291W5203'], 'Sanden': ['4527', '6667']}]
2509
[{'AC Delco': ['1521817'], 'Airpro': ['204515'], 'CARLISLE': ['3012261', '3014320'], 'Compressor Works': ['618646'], 'Four Seasons': ['57646', '58646'], 'Global Parts Distributors': ['5511577', '6511577', '7511577'], 'Kenworth': ['LE1240'], 'Mack': ['206RD49AM'], 'MEI': ['5715'], 'NAPA': ['967085', 'TEM967085'], 'Peterbilt': ['4675SAN'], 'Sanden': ['4515', '6673'], 'Sunair': ['CO2243CA'], 'Trad Automotive': ['C2160'], 'TTAC': ['3004213'], 'Visteon': ['010187']}]
2510
[{'Airpro': ['204530'], 'Alliance': ['ABPN83304032', 'ABPN83304182'], 'Bergstrom': ['525696'], 'CARLISLE': ['3014330'], 'Ford': ['E9HZ19703A'], 'Freightliner': ['304032', 'ABPN83304032'], 'International': ['ZGG705199'], 'Kysor': ['1401014', '1401332'], 'MEI': ['5714'], 'Omega': ['2010085'], 'Paccar': ['4530SAN', '9514SAN'], 'Peterbilt': ['4530SAN'], 'Ranshu': ['14SD4530', '14SD4530C', '14SD4530NC', '14SD4530NEW'], 'Red Dot': ['75R83162', '75R8322', '75R8342', 'RD599850'], 'Sanden': ['4530', '6674'], 'Trad Automotive': ['C2624'], 'TruckAir': ['033420'], 'TTAC': ['3004207'], 'Volvo': ['176351', '176354', '85100889'], 'Western Star': ['611043412']}]
2511
[{'Airpro': ['204530'], 'Alliance': ['ABPN83304032', 'ABPN83304182'], 'Bergstrom': ['525696'], 'Ford': ['E9HZ19703A'], 'Freightliner': ['304032', 'ABPN83304032'], 'International': ['ZGG705199'], 'Kysor': ['1401014', '1401332'], 'MEI': ['5714'], 'Omega': ['2010085'], 'Paccar': ['4530SAN', '9514SAN'], 'Peterbilt': ['4530SAN'], 'Ranshu': ['14SD4530NC'], 'Red Dot': ['75R83162', '75R8322', '75R8342', 'RD599850'], 'Sanden': ['4530', '6674'], 'Trad Automotive': ['C2624'], 'TruckAir': ['033420'], 'TTAC': ['3004207'], 'Volvo': ['176351', '176354', '85100889'], 'Western Star': ['611043412']}]
2512
[{'CARLISLE': ['3014340'], 'Sanden': ['4523', '6675']}]
2513
[{'AC Delco': ['1521796'], 'Airpro': ['204673'], 'CARLISLE': ['3014350'], 'Compressor Works': ['618587'], 'Four Seasons': ['57587', '58587'], 'Global Parts Distributors': ['5511563', '6511563', '7511563'], 'NAPA': ['967145', 'TEM967145'], 'Omega': ['2004525'], 'Sanden': ['4525', '6677', '6678']}]
2514
[{'Airpro': ['208396'], 'Austin Baker': ['10364891'], 'CARLISLE': ['3014360'], 'Global Parts Distributors': ['7812658'], 'MEI': ['5194W5205', '5294W5201'], 'Sanden': ['4532', '6679', '8396']}]
2515
[{'CARLISLE': ['3014370'], 'Ranshu': ['14SD4528', '14SD4528NC'], 'Sanden': ['4528', '6681'], 'Steiger': ['351224T91'], 'Sunair': ['CO2056CA'], 'Trad Automotive': ['C2478']}]
2516
[{'Four Seasons': ['58646'], 'Omega': ['2009983'], 'Ranshu': ['14SD4528NC', '14SD4528NCPOL', 'TL3004206'], 'Sanden': ['4528', '6681']}]
2517
[{'CARLISLE': ['3014380'], 'Sanden': ['6687'], 'Trad Automotive': ['C315']}]
2518
[{'CARLISLE': ['3014390'], 'Omega': ['2006697', '2006697AM'], 'Ranshu': ['14SD6697', '14SD6697NC'], 'Sanden': ['6697']}]
2519
[{'CARLISLE': ['3014400'], 'I.C.E': ['2521122']}]
2520
[{'AC Delco': ['1521775', '1522096'], 'CARLISLE': ['3014410'], 'Compressor Works': ['618513'], 'Four Seasons': ['57513', '58513'], 'I.C.E': ['2521129'], 'NAPA': ['254012', '274012', 'TEM254012', 'TEM274012'], 'Omega': ['2010230']}]
2521
[{'CARLISLE': ['3014420'], 'I.C.E': ['2521131'], 'Omega': ['2010228'], 'Seltec': ['48825075'], 'Valeo': ['10325075']}]
2522
[{'CARLISLE': ['3014430'], 'Omega': ['2044371'], 'Valeo': ['10354371']}]
2523
[{'AP Air Inc.': ['509372', '5093723'], 'Austin Baker': ['10364451'], 'CARLISLE': ['3014440', '3014441'], 'Four Seasons': ['167511', '168511'], 'Global Parts Distributors': ['5512896', '6512896', '7512896'], 'Massey Ferguson': ['771974'], 'MEI': ['57170', 'SD7170'], 'NAPA': ['971018', 'TEM971018'], 'Omega': ['2010072', '2010072AM'], 'Sanden': ['7170'], 'Sunair': ['CO2101CA'], 'Trad Automotive': ['C1989'], 'TTAC': ['3004588']}]
2524
[{'AP Air Inc.': ['509372', '5093723'], 'Austin Baker': ['10364451'], 'CARLISLE': ['3014440', '3014441'], 'Four Seasons': ['167511', '168511'], 'Global Parts Distributors': ['5512896', '6512896', '7512896'], 'Massey Ferguson': ['771974'], 'MEI': ['57170', 'SD7170'], 'NAPA': ['971018', 'TEM971018'], 'Omega': ['2010072', '2010072AM'], 'Sanden': ['7170'], 'Sunair': ['CO2101CA'], 'Trad Automotive': ['C1989'], 'TTAC': ['3004588']}]
2525
[{'CARLISLE': ['3014450'], 'Global Parts Distributors': ['5512776', '6512776', '7512776'], 'Omega': ['2007172', '2007172AM'], 'Sanden': ['7172']}]
2526
[{'Austin Baker': ['10363231'], 'CARLISLE': ['3014460', '3014461'], 'Four Seasons': ['167515', '168515'], 'Global Parts Distributors': ['5512769', '6512769', '7512769', '7812769'], 'NAPA': ['971024', 'TEM971024'], 'Omega': ['2010061', '2010061AM'], 'Ranshu': ['14SD7176', '14SD7176NC', '14SD7176NEW'], 'Sanden': ['7176'], 'Trad Automotive': ['C1700']}]
2527
[{'Austin Baker': ['10363231'], 'CARLISLE': ['3014460', '3014461'], 'Four Seasons': ['167515', '168515'], 'Global Parts Distributors': ['5512769', '6512769', '7512769', '7812769'], 'NAPA': ['971024', 'TEM971024'], 'Omega': ['2010061', '2010061AM'], 'Ranshu': ['14SD7176', '14SD7176NC', '14SD7176NEW'], 'Sanden': ['7176'], 'Trad Automotive': ['C1700']}]
2528
[{'CARLISLE': ['3014470'], 'Delphi Automotive Systems': ['TSP0155420'], 'Fiat': ['571274200'], 'Sanden': ['7181']}]
2529
[{'Airpro': ['207200'], 'CARLISLE': ['3014482'], 'Global Parts Distributors': ['5511786', '6511786', '7511786'], 'Ranshu': ['142627', '142627C', '142627NC'], 'Ready-Aire/Proliance': ['2204'], 'Sanden': ['7200'], 'Trad Automotive': ['C991R']}]
2530
[{'CARLISLE': ['3014490'], 'Sanden': ['7207']}]
2531
[{'Airpro': ['207210'], 'Austin Baker': ['10307860', '10345781'], 'CARLISLE': ['3014500'], 'Ford': ['E8BZ19703B'], 'NAPA': ['254434', 'TEM254434'], 'Sanden': ['7210'], 'Trad Automotive': ['C826']}]

2532
[{'AC Delco': ['1522066'], 'CARLISLE': ['3014510'], 'Four Seasons': ['77581', '78581'], 'Sanden': ['7213'], 'Trad Automotive': ['C2960']}]
2533
[{'Airpro': ['239016'], 'CARLISLE': ['3014520'], 'Sanden': ['7225'], 'Trad Automotive': ['C899R']}]
2534
[{'CARLISLE': ['3014530'], 'Sanden': ['7227']}]
2535
[{'Four Seasons': ['58575'], 'Global Parts Distributors': ['5511778', '7511778'], 'Mazda': ['UE3861450', 'UE3861K00'], 'Omega': ['2010010R'], 'Ranshu': ['14SD7227C', '14SD7227NC', '14SD7227NEW']}]
2536
[{'Airpro': ['217229'], 'CARLISLE': ['3014540'], 'Four Seasons': ['57574', '57575', '58574', '58575'], 'Global Parts Distributors': ['5511956', '6511956', '7511956'], 'Mazda': ['UE3861K00'], 'Omega': ['2007229', '2010026R'], 'Ranshu': ['142558', '142558NC', '14SD7227', '14SD7227C'], 'Ready-Aire/Proliance': ['2188'], 'Sanden': ['7229'], 'Trad Automotive': ['C1447', 'C899']}]
2537
[{'AC Delco': ['1522030'], 'CARLISLE': ['3014550'], 'Four Seasons': ['67599', '68599'], 'Global Parts Distributors': ['5511775', '6511775', '7511775'], 'Mazda': ['000067D01A7P', 'UE5461450'], 'NAPA': ['254377', 'TEM254377'], 'Omega': ['2007240', '2007240R'], 'Ranshu': ['142489', '142489NC', '14SD7240', '14SD7240C'], 'Sanden': ['7240'], 'Trad Automotive': ['C782', 'C782R']}]
2538
[{'Airpro': ['207246'], 'CARLISLE': ['3014560'], 'Global Parts Distributors': ['5511240', '6511240', '7511240'], 'Sanden': ['7246'], 'Trad Automotive': ['C872']}]
2539
[{'CARLISLE': ['3014571'], 'Ranshu': ['14SD7303NEW'], 'Sanden': ['7303'], 'Trad Automotive': ['C2260']}]
2540
[{'CARLISLE': ['3014581'], 'Four Seasons': ['157570', '158570'], 'Freightliner': ['SKI4404'], 'Global Parts Distributors': ['5512827', '6512827', '7512827'], 'NAPA': ['979058', 'TEM979058'], 'Omega': ['2007304'], 'Sanden': ['4455', '7304'], 'Sunair': ['CO2291CA'], 'Trad Automotive': ['C2261'], 'TTAC': ['3004440']}]
2541
[{'AFI': ['0383'], 'Airpro': ['207312'], 'Austin Baker': ['10364471'], 'CARLISLE': ['3014590', '3014591'], 'Freightliner': ['ABPN83304101'], 'Frigette': ['204871'], 'Global Parts Distributors': ['5511296', '6511296', '7511296'], 'Mack': ['4379RD511217'], 'Omega': ['2010189', '2010189AM'], 'Ranshu': ['14SD7312', '14SD7312NC', '14SD7312NEW'], 'Sanden': ['4456', '7312'], 'Sunair': ['CO2047CA'], 'Trad Automotive': ['C1161'], 'TTAC': ['3004443']}]
2542
[{'Airpro': ['207320'], 'CARLISLE': ['3014601'], 'Global Parts Distributors': ['5511244', '6511244', '7511244'], 'Omega': ['2010190'], 'Ranshu': ['14SD7320', '14SD7320NC'], 'Sanden': ['4454', '7320'], 'Trad Automotive': ['C1162'], 'TTAC': ['3004442']}]
2543
[{'Airpro': ['207321'], 'CARLISLE': ['3014610'], 'Global Parts Distributors': ['5511243', '6511243', '7511243'], 'Omega': ['2010191'], 'Sanden': ['7321'], 'Trad Automotive': ['C1467']}]
2544
[{'Agco': ['LC91V00001F1', 'TDKR1151300S', 'TDKR151320S', 'TDKR151340S'], 'Global Parts Distributors': ['6512679', '7812679'], 'MEI': ['57351', 'SD7351'], 'Omega': ['2007351', '2007351AM'], 'Ranshu': ['14SD7351', '14SD7351C', '14SD7351NC', '14SD7351NEW'], 'Sanden': ['7351', '7359'], 'TRUCK AC': ['3005363'], 'TruckAir': ['033532']}]
2545
[{'AFI': ['0733'], 'CARLISLE': ['3014621'], 'Four Seasons': ['157580', '158580'], 'Global Parts Distributors': ['5512799', '6512799', '7512799'], 'MEI': ['57360'], 'Omega': ['2007360', '2007360AM'], 'Ranshu': ['14SD7360'], 'Sanden': ['7360', 'LC91V001F7'], 'Sunair': ['CO2236CA'], 'Trad Automotive': ['C2514'], 'TTAC': ['3005341']}]
2546
[{'AC Delco': ['1522067', '1522104'], 'Airpro': ['207409'], 'CARLISLE': ['3014631'], 'Ford': ['E5UZ19703A'], 'Four Seasons': ['57630', '58630', '77582', '78582'], 'Global Parts Distributors': ['5511293', '6511293', '7511293'], 'Hodyon': ['367409NA'], 'MEI': ['5909'], 'NAPA': ['254038', '254437', 'TEM254038', 'TEM254437'], 'Ranshu': ['14SD7409', '14SD7409C', '14SD7409NC', '14SD7409NEW'], 'Ready-Aire/Proliance': ['2197N'], 'Sanden': ['7409'], 'Trad Automotive': ['C820']}]
2547
[{'AC Delco': ['1520510', '1520713', '1521341'], 'Advance Auto Parts': ['DW57581'], 'Airpro': ['204628', '207416'], 'Austin Baker': ['10302731', '10303660', '10303661', '10309300'], 'CARLISLE': ['3014641'], 'Compressor Works': ['618581'], 'Ford': ['2UZ19V703', 'E9DZ19V703AARM'], 'Four Seasons': ['57581', '58581'], 'Global Parts Distributors': ['5511286', '5511561', '6511286', '6511561', '7511286', '7511561'], 'MEI': ['5716', '5916'], 'NAPA': ['253125', '273125', 'TEM253125', 'TEM273125'], 'Omega': ['2010137', '2010192', '2010192AM', 'K1491001'], 'Oreilly Auto Parts': ['57581'], 'Ranshu': ['142298', '14SD7416C', '14SD7416NC', '14SD7416NEW', '14SD7484', '14SD7484NC', '14SD8105', '14SD8105NC'], 'Ready-Aire/Proliance': ['2198', '2198N'], 'Sanden': ['4628', '7416', '7501', '8105'], 'Spectra Premium': ['0658581', '658581'], 'Trad Automotive': ['C1701', 'C824'], 'Visteon': ['000544', '010218', '010401']}]
2548
[{'Audi/Volkswagen': ['357820803A', '357820803C'], 'CARLISLE': ['3014652'], 'Four Seasons': ['97590', '98590'], 'Global Parts Distributors': ['5511951', '6511951', '7511951'], 'Ranshu': ['142825', '142825C'], 'Ready-Aire/Proliance': ['2255'], 'Sanden': ['7425'], 'Trad Automotive': ['C1667', 'C1667R']}]
2549
[{'AC Delco': ['1520596'], 'Austin Baker': ['10345190'], 'Four Seasons': ['57563', '58563'], 'Frigette': ['204642'], 'Hyundai/Kia': ['9770121251'], 'NAPA': ['254063', 'TEM254063'], 'Ranshu': ['142642', '142642C'], 'Ready-Aire/Proliance': ['2224'], 'Sanden': ['7429'], 'Tech Choice Parts': ['30135'], 'Visteon': ['000550', '018563']}]
2550
[{'CARLISLE': ['3014660'], 'Sanden': ['7444'], 'Trad Automotive': ['C825']}]
2551
[{'AC Delco': ['1522069'], 'CARLISLE': ['3014670'], 'Four Seasons': ['77591', '78591'], 'NAPA': ['254447', 'TEM254447'], 'Omega': ['2007445R', '2010164AM'], 'Ranshu': ['142707', '142707C', '142707NC'], 'Ready-Aire/Proliance': ['2036'], 'Sanden': ['7445'], 'Trad Automotive': ['C1070R', 'C1071'], 'Visteon': ['000552']}]
2552
[{'AC Delco': ['1522069'], 'Four Seasons': ['77591', '78591'], 'NAPA': ['254447', 'TEM254447'], 'Omega': ['2007445R', '2010164AM'], 'Ranshu': ['142707', '142707C', '142707NC'], 'Ready-Aire/Proliance': ['2036'], 'Sanden': ['7445'], 'Trad Automotive': ['C1070R', 'C1071'], 'Visteon': ['000552']}]
2553
[{'AC Delco': ['1521010', '1521013', '1521262'], 'Austin Baker': ['10309020', '10364481'], 'CARLISLE': ['3014680'], 'Compressor Works': ['638868'], 'Delphi Diavia': ['TSP0155159'], 'Four Seasons': ['77589', '78589'], 'Global Parts Distributors': ['5511650', '5511768', '5511773', '6511650', '6511768', '7511650', '7511768'], 'Jaguar': ['CCC4929'], 'NAPA': ['254445', '275753', 'TEM254445', 'TEM275753'], 'Omega': ['2009999', '2010519R'], 'Sanden': ['7463', '7494', '7543'], 'Trad Automotive': ['C1097R', 'C1098', 'C1098R']}]
2554
[{'CARLISLE': ['3014692'], 'Four Seasons': ['57560', '58560'], 'Global Parts Distributors': ['5511784', '6511784', '7511784'], 'Hyundai/Kia': ['9770124A00'], 'NAPA': ['254061', 'TEM254061'], 'Ready-Aire/Proliance': ['2209'], 'Trad Automotive': ['C1012R'], 'Visteon': ['000555']}]
2555
[{'AC Delco': ['1522068'], 'CARLISLE': ['3014700'], 'Four Seasons': ['77583', '78583'], 'NAPA': ['254438', 'TEM254438'], 'Sanden': ['7470']}]
2556
[{'CARLISLE': ['3014710'], 'Sanden': ['7499'], 'Trad Automotive': ['C2594']}]
2557
[{'CARLISLE': ['3014720'], 'Sanden': ['7534']}]
2558
[{'AC Delco': ['1520595', '1521012'], 'Airpro': ['207557'], 'Austin Baker': ['10307490'], 'CARLISLE': ['3014732'], 'Four Seasons': ['57562', '58562'], 'Frigette': ['204548'], 'Global Parts Distributors': ['5511556', '6511556', '7511556'], 'NAPA': ['254041', 'TEM254041'], 'Omega': ['2007557', '2010637R'], 'Ranshu': ['142548', '142548C'], 'Ready-Aire/Proliance': ['2200', '2231', '2231N'], 'Sanden': ['7557'], 'Tech Choice Parts': ['30743'], 'Trad Automotive': ['C660', 'C660R', 'C938', 'C938R'], 'Visteon': ['000561', '000562']}]
2559
[{'CARLISLE': ['3014740'], 'Omega': ['2007641'], 'Sanden': ['7641'], 'Trad Automotive': ['C2916']}]
2560
[{'CARLISLE': ['3014750'], 'Ranshu': ['14SD4147NC'], 'Sanden': ['4147', '4321', '7681AU']}]
2561
[{'AC Delco': ['1520799', '1521105', '1521255'], 'Advance Auto Parts': ['DW57632'], 'Airpro': ['207701'], 'Austin Baker': ['10303830', '10303831'], 'CARLISLE': ['3014761'], 'Chrysler': ['56004354'], 'Compressor Works': ['618632'], 'Four Seasons': ['57632', '58632'], 'Frigette': ['204903'], 'Hodyon': ['367701NA'], 'NAPA': ['254042', '276597', 'TEM254042', 'TEM276597'], 'Omega': ['2007701', '2007701AM'], 'Oreilly Auto Parts': ['57632'], 'Ranshu': ['14SD7701', '14SD7701NC', '14SD7701NEW'], 'Ready-Aire/Proliance': ['2211', '2211N'], 'Sanden': ['7701'], 'Spectra Premium': ['0610011'], 'Trad Automotive': ['C1194', 'C1194R'], 'Visteon': ['000565']}]

2562
[{'AC Delco': ['1521036', '1521920'], 'Airpro': ['207730'], 'Austin Baker': ['10306041'], 'CARLISLE': ['3014771'], 'Chrysler': ['56004657', 'R7091003'], 'Compressor Works': ['637594'], 'Four Seasons': ['77594', '78594'], 'Global Parts Distributors': ['5511652', '6511652', '7511652'], 'NAPA': ['254459', '274459', 'TEM254459', 'TEM274459'], 'Omega': ['2010027', '2010027AM'], 'Oreilly Auto Parts': ['77594'], 'Ranshu': ['142706', '142706C'], 'Ready-Aire/Proliance': ['2234N'], 'Sanden': ['7702'], 'Trad Automotive': ['C1069'], 'Visteon': ['000735']}]
2563
[{'Airpro': ['204641', '207712'], 'Austin Baker': ['10351041'], 'CARLISLE': ['3014781'], 'Caterpillar': ['2329274'], 'Freightliner': ['304323'], 'Frigette': ['204856'], 'Global Parts Distributors': ['5511574', '6511574', '7511574'], 'Mack': ['5102940'], 'MEI': ['5741', '5913'], 'Omega': ['2010093'], 'Ranshu': ['14SD7712', '14SD7712NEW'], 'Sanden': ['4641', '4649', '7712'], 'Sunair': ['CO2018CAB'], 'Trad Automotive': ['C2467', 'C871'], 'TTAC': ['3004559']}]
2564
[{'CARLISLE': ['3014790'], 'Omega': ['2007715'], 'Sanden': ['7715'], 'Trad Automotive': ['C1684']}]
2565
[{'CARLISLE': ['3014800'], 'Sanden': ['7730']}]
2566
[{'AC Delco': ['1520354', '152818'], 'Airpro': ['207803'], 'AP Air Inc.': ['509568'], 'Austin Baker': ['10345380', '10345381'], 'CARLISLE': ['3014811'], 'Compressor Works': ['638594'], 'Four Seasons': ['67594', '68594'], 'Freightliner': ['ABPN83304652'], 'General Motors': ['15020478', '15680077'], 'Global Parts Distributors': ['5511392', '6511392', '7511392', '7811392'], 'Kysor': ['1401202'], 'MEI': ['5704'], 'NAPA': ['254015', '274515', 'TEM254015', 'TEM274515'], 'Navistar': ['ZGG705020'], 'Omega': ['2010688', '2010688AM', '2010688R'], 'Oreilly Auto Parts': ['67594'], 'Ranshu': ['14SD7803', '14SD7803NEW'], 'Ready-Aire/Proliance': ['2434N'], 'Sanden': ['7803'], 'Sunair': ['CO2202CA'], 'Trad Automotive': ['C3151', 'C452', 'C452R'], 'TruckAir': ['031843'], 'TTAC': ['3004645'], 'Visteon': ['000568']}]
2567
[{'Airpro': ['207402', '207819'], 'Alliance': ['ABPN83304042', 'ABPN83304922'], 'Bergstrom': ['525698'], 'CARLISLE': ['3014821'], 'Compressor Works': ['618552'], 'Four Seasons': ['57552', '58552'], 'Freightliner': ['ABPN83304042'], 'Kenworth': ['LE1290'], 'Kysor': ['1401135', '402069'], 'MEI': ['5702', '5902'], 'Omega': ['2010151'], 'Peterbilt': ['LE1290'], 'Ranshu': ['14SD7819', '14SD7819NC'], 'Ready-Aire/Proliance': ['2196N'], 'Red Dot': ['75R8442', 'RD573730'], 'Sanden': ['7402', '7819'], 'Sunair': ['CO2134CA'], 'Trad Automotive': ['C108'], 'TTAC': ['3004545'], 'Volvo': ['176353']}]
2568
[{'AC Delco': ['1521259', '1521802'], 'Airpro': ['207821'], 'Audi/Volkswagen': ['701820807A'], 'CARLISLE': ['3014830'], 'Compressor Works': ['618595'], 'Four Seasons': ['57595', '58595'], 'Frigette': ['204826'], 'Global Parts Distributors': ['5511940', '6511940', '7511940'], 'NAPA': ['254077', '272386', 'TEM254077', 'TEM272386'], 'Omega': ['2007820'], 'Ranshu': ['142826', '142826NC'], 'Ready-Aire/Proliance': ['2225', '2225N'], 'Sanden': ['7820', '7821'], 'Tech Choice Parts': ['30641'], 'Trad Automotive': ['C1144', 'C1144R'], 'Visteon': ['000571']}]
2569
[{'AC Delco': ['1521893'], 'Airpro': ['207822'], 'Austin Baker': ['10362281'], 'CARLISLE': ['3014841'], 'Compressor Works': ['637578'], 'Four Seasons': ['67578', '68578'], 'Freightliner': ['2243374000'], 'Frigette': ['2041065'], 'MEI': ['5748'], 'NAPA': ['967048', 'TEM967048'], 'Omega': ['2010152'], 'Ranshu': ['14SD7822', '14SD7822NC', '14SD7822NEW'], 'Sanden': ['7822', '8022'], 'Sunair': ['CO2137CA'], 'Trad Automotive': ['C2265'], 'TTAC': ['3004548']}]
2570
[{'CARLISLE': ['3014850'], 'Sanden': ['7844']}]
2571
[{'CARLISLE': ['3014860'], 'Global Parts Distributors': ['5511299', '6511299', '7511299'], 'Omega': ['2007930'], 'Sanden': ['4264', '7846'], 'Trad Automotive': ['C2388']}]
2572
[{'Austin Baker': ['10347160'], 'CARLISLE': ['3014870'], 'Sanden': ['7865'], 'Trad Automotive': ['C2299']}]
2573
[{'CARLISLE': ['3014881'], 'Omega': ['2007882AM'], 'Sanden': ['7882'], 'Trad Automotive': ['C2266']}]
2574
[{'AC Delco': ['1520875'], 'AFI': ['0467'], 'Austin Baker': ['10345400', '10345401'], 'CARLISLE': ['3014891'], 'Compressor Works': ['638860'], 'Four Seasons': ['67574', '68574'], 'Global Parts Distributors': ['5511612', '5511710', '6511612', '6511710', '7511612', '7511710'], 'NAPA': ['254354', '275535', 'TEM254354', 'TEM275535'], 'Omega': ['2007935', '2007935R', '2010942', '2011222', '2011222AM'], 'Ranshu': ['143021', '143021C', '143021NC'], 'Sanden': ['7935'], 'Trad Automotive': ['C1587', 'C1587R'], 'Valeo': ['10000182'], 'Visteon': ['000575'], 'Volvo': ['360008197', '68410281']}]
2575
[{'AC Delco': ['1520875'], 'AFI': ['0467'], 'Austin Baker': ['10345400', '10345401'], 'CARLISLE': ['3014891'], 'Compressor Works': ['638860'], 'Four Seasons': ['67574', '68574'], 'Global Parts Distributors': ['5511612', '5511710', '6511612', '6511710', '7511612', '7511710'], 'NAPA': ['254354', '275535', 'TEM254354', 'TEM275535'], 'Omega': ['2007935', '2007935R', '2010942', '2011222', '2011222AM'], 'Ranshu': ['143021', '143021C', '143021NC'], 'Sanden': ['7935'], 'Trad Automotive': ['C1587', 'C1587R'], 'Valeo': ['10000182'], 'Visteon': ['000575'], 'Volvo': ['360008197', '68410281']}]
2576
[{'CARLISLE': ['3014900'], 'Sanden': ['7972'], 'TTAC': ['3005158'], 'Volvo': ['11007857']}]
2577
[{'CARLISLE': ['3014910'], 'Sanden': ['7996']}]
2578
[{'AFI': ['0053', '0514'], 'Austin Baker': ['10364571', '10364671'], 'CARLISLE': ['3014920', '3015011'], 'MEI': ['5752A'], 'Omega': ['2008017', '2008126', '2018061', '2018061AM'], 'Sanden': ['4271', '7866', '8017', '8061', '8126'], 'Sunair': ['CO2097CA'], 'Trad Automotive': ['C2414', 'C2493', 'C2912'], 'TTAC': ['3005158A'], 'Volvo': ['110073145', '8FK351126221']}]
2579
[{'Austin Baker': ['10364581'], 'CARLISLE': ['3014931'], 'Omega': ['2004272'], 'Ranshu': ['14SD4272', '14SD4272C', '14SD4272NC', '14SD4272NEW'], 'Sanden': ['4272', '8023', '8227']}]
2580
[{'Austin Baker': ['10364611'], 'CARLISLE': ['3014941'], 'Sanden': ['8027'], 'TTAC': ['3004514']}]
2581
[{'CARLISLE': ['3014951'], 'Sanden': ['4154', '4597U', '8028']}]
2582
[{'CARLISLE': ['3014960'], 'Omega': ['2008034'], 'Sanden': ['7887', '8034']}]
2583
[{'AFI': ['0441'], 'AP Air Inc.': ['598520'], 'Behr': ['8FK351132171'], 'CARLISLE': ['3014970', '3014971'], 'Delphi Automotive Systems': ['TSP0155181'], 'Four Seasons': ['157594', '158594'], 'MEI': ['58112'], 'NAPA': ['979996', 'TEM979996'], 'Omega': ['2008044', '2008044AM'], 'Ranshu': ['14SD8044', '14SD8044NC'], 'Sanden': ['6028', '8044', '8176'], 'Sunair': ['CO2094CA'], 'Trad Automotive': ['C2480'], 'TTAC': ['3005138', '3005374'], 'Valeo': ['813017'], 'Volvo': ['11104251', '20538307', '21184142', '7420538307', '8113628', '8119628', '8191892', '85000315']}]
2584
[{'AFI': ['0841'], 'Austin Baker': ['10364641'], 'CARLISLE': ['3014980', '3014981'], 'Four Seasons': ['157582', '158582'], 'MEI': ['58045'], 'Omega': ['2008045', '2008045AM'], 'Ranshu': ['14SD6035', '14SD6035C', '14SD6035NC', '14SD6035NEW', '14SD8045', '14SD8045NC'], 'Sanden': ['6035', '8045'], 'Sunair': ['CO2128CA'], 'Trad Automotive': ['C1903'], 'TTAC': ['3005380'], 'Volvo': ['11104419']}]
2585
[{'AFI': ['0841'], 'Austin Baker': ['10364641'], 'CARLISLE': ['3014980', '3014981'], 'Four Seasons': ['157582', '158582'], 'MEI': ['58045'], 'Omega': ['2008045', '2008045AM'], 'Ranshu': ['14SD6035', '14SD6035C', '14SD6035NC', '14SD6035NEW', '14SD8045', '14SD8045NC'], 'Sanden': ['6035', '8045'], 'Sunair': ['CO2128CA'], 'Trad Automotive': ['C1903'], 'TTAC': ['3005380'], 'Volvo': ['11104419']}]
2586
[{'DAF': ['1251063', '1264800', '1444295', '1638737'], 'Omega': ['2008051AM'], 'Sunair': ['CO2168CA']}]
2587
[{'AC Delco': ['1520890', '1521298'], 'Austin Baker': ['10309480', '10345260', '10345791'], 'CARLISLE': ['3014991'], 'Compressor Works': ['638861'], 'Four Seasons': ['67557', '67558', '68557', '68558'], 'Global Parts Distributors': ['5511770', '5511967', '5512063', '5512138', '6511770', '6511967', '6512063', '6512138', '7511770', '7511967', '7512063', '7512138'], 'NAPA': ['254268', '254269', 'TEM254268', 'TEM254269'], 'Omega': ['2007943', '2008052'], 'Ranshu': ['144564', '144564C'], 'Ready-Aire/Proliance': ['2254'], 'Saab': ['4319240', '4632055', '4868659'], 'Sanden': ['7943', '8052'], 'Tech Choice Parts': ['30615'], 'Trad Automotive': ['C1123R', 'C1124R', 'C716'], 'Visteon': ['001105']}]

2588
[{'Austin Baker': ['10364661'], 'CARLISLE': ['3015000'], 'Liebehrr': ['5700334'], 'Ranshu': ['14SD8053', '14SD8053NC', '14SD8053NEW'], 'Sanden': ['8053'], 'Sunair': ['CO2129CA'], 'Trad Automotive': ['C2494']}]
2589
[{'AFI': ['0053', '0514'], 'Austin Baker': ['10364571', '10364671'], 'CARLISLE': ['3015011'], 'MEI': ['5752A'], 'Omega': ['2008017', '2008126', '2018061', '2018061AM'], 'Sanden': ['4271', '7866', '8017', '8061', '8126'], 'Sunair': ['CO2097CA'], 'Trad Automotive': ['C2414', 'C2493', 'C2912'], 'TTAC': ['3005158A'], 'Volvo': ['110073145', '8FK351126221']}]
2590
[{'CARLISLE': ['3015020', '3015021'], 'Omega': ['2018067', '2018067AM'], 'Ranshu': ['14SD8067NC', '14SD8067NEW'], 'Sanden': ['6024', '8067'], 'Scania': ['10575186']}]
2591
[{'CARLISLE': ['3015020', '3015021'], 'Omega': ['2018067', '2018067AM'], 'Ranshu': ['14SD8067NC', '14SD8067NEW'], 'Sanden': ['6024', '8067'], 'Scania': ['10575186']}]
2592
[{'CARLISLE': ['3015030'], 'Four Seasons': ['157596', '158596'], 'Global Parts Distributors': ['6513026'], 'NAPA': ['979997', 'TEM979997'], 'Omega': ['2004271', '2008069'], 'Ranshu': ['14SD8069', '14SD8069NC'], 'Sanden': ['7860', '8069'], 'Santech': ['2004271'], 'Sunair': ['CO2127CA'], 'Trad Automotive': ['C2492'], 'Volvo': ['11007314', '11058974']}]
2593
[{'CARLISLE': ['3015040', '3015041'], 'Omega': ['2018085'], 'Sanden': ['8085'], 'Trad Automotive': ['C2482']}]
2594
[{'AFI': ['0440'], 'Agco': ['3712528M2'], 'Austin Baker': ['10346751', '10362981'], 'CARLISLE': ['3015050', '3015051'], 'Global Parts Distributors': ['5512613', '6512613', '7512613'], 'Hesston': ['504078610'], 'Massey Ferguson': ['3712528M2', '3763384M91', '3782613M', '3782613M2'], 'MEI': ['5308'], 'Omega': ['2007952', '2007952AM'], 'Ranshu': ['14SD8088NC'], 'Sanden': ['7952', '8088', 'SD8088'], 'Sunair': ['CO2060CA'], 'Trad Automotive': ['C2296'], 'TTAC': ['3004603']}]
2595
[{'AFI': ['0440'], 'Agco': ['3712528M2'], 'Austin Baker': ['10346751', '10362981'], 'CARLISLE': ['3015050', '3015051'], 'Global Parts Distributors': ['5512613', '6512613', '7512613'], 'Hesston': ['504078610'], 'Massey Ferguson': ['3712528M2', '3763384M91', '3782613M', '3782613M2'], 'MEI': ['5308'], 'Omega': ['2007952', '2007952AM'], 'Ranshu': ['14SD8088NC'], 'Sanden': ['7952', '8088', 'SD8088'], 'Sunair': ['CO2060CA'], 'Trad Automotive': ['C2296'], 'TTAC': ['3004603']}]
2596
[{'Omega': ['2008091'], 'Ranshu': ['14SD8091', '14SD8091C', '14SD8091NC', '14SD8091NEW'], 'Sanden': ['8091']}]
2597
[{'Austin Baker': ['10364751'], 'Global Parts Distributors': ['6512922'], 'Omega': ['2018112', '2018112AM'], 'Sanden': ['8112'], 'Sunair': ['CO2130CA']}]
2598
[{'Austin Baker': ['10364751'], 'Global Parts Distributors': ['6512922'], 'Omega': ['2018112', '2018112AM'], 'Sanden': ['8112'], 'Sunair': ['CO2130CA']}]
2599
[{'Austin Baker': ['10364751'], 'CARLISLE': ['3015060'], 'Omega': ['2018112', '2018112AM'], 'Sanden': ['8112'], 'Sunair': ['CO2130CA'], 'TTAC': ['3005137']}]
2600
[{'CARLISLE': ['3015071'], 'Omega': ['2008117AM'], 'Ranshu': ['14SD6008NC', '14SD8117NC', '14SD8117NEW'], 'Sanden': ['8117']}]
2601
[{'CARLISLE': ['3015080'], 'Sanden': ['8139'], 'Trad Automotive': ['C3244']}]
2602
[{'AFI': ['0490'], 'CARLISLE': ['3015090', '3015091'], 'CNH': ['8500795'], 'Four Seasons': ['157574', '158574'], 'Global Parts Distributors': ['6513074'], 'MEI': ['58090'], 'NAPA': ['979098', 'TEM979098'], 'Omega': ['2008144', '2008144AM'], 'Ranshu': ['14SD8144', '14SD8144NC'], 'Sanden': ['8090', '8144'], 'Sunair': ['CO2100CA'], 'Trad Automotive': ['C2483', 'C2617'], 'TTAC': ['3005220']}]
2603
[{}]
2604
[{'AFI': ['0490'], 'CARLISLE': ['3015090', '3015091'], 'CNH': ['8500795'], 'Four Seasons': ['157574', '158574'], 'Global Parts Distributors': ['6513074'], 'MEI': ['58090'], 'NAPA': ['979098', 'TEM979098'], 'Omega': ['2008144', '2008144AM'], 'Ranshu': ['14SD8144', '14SD8144NC'], 'Sanden': ['8090', '8144'], 'Sunair': ['CO2100CA'], 'Trad Automotive': ['C2483', 'C2617'], 'TTAC': ['3005220']}]
2605
[{'CARLISLE': ['3015101'], 'Four Seasons': ['157595', '158595'], 'Global Parts Distributors': ['5512773', '6512773', '7512773'], 'Massey Ferguson': ['3789035M1', '3789053M1', '4789035M1'], 'MEI': ['58147'], 'Omega': ['2008147', '2008147AM'], 'Ranshu': ['14SD8147', '14SD8147NEW'], 'Sanden': ['8147'], 'Sunair': ['C2266CA'], 'Trad Automotive': ['C2794', 'C2794SR'], 'TTAC': ['3004601']}]
2606
[{'CARLISLE': ['3015111'], 'Ford': ['878029120'], 'Four Seasons': ['167514', '168514'], 'Global Parts Distributors': ['5512751', '6512751', '7512751'], 'I.H.': ['87802912'], 'MEI': ['58148'], 'Omega': ['2008148', '2008148AM'], 'Ranshu': ['14SD8148', '14SD8148NC', '14SD8148NEW', 'TL3004741'], 'Sanden': ['6021', '8148'], 'Sunair': ['CO2053CA'], 'Trad Automotive': ['C2477']}]
2607
[{'CARLISLE': ['3015120'], 'Global Parts Distributors': ['5512750', '6512750', '7512750'], 'Omega': ['2008151'], 'Sanden': ['8151']}]
2608
[{'Global Parts Distributors': ['7812927'], 'Omega': ['2008152'], 'Ranshu': ['14SD8152', '14SD8152NC'], 'Sanden': ['8152'], 'Trad Automotive': ['C2228']}]
2609
[{'CARLISLE': ['3015130'], 'Omega': ['2008173'], 'Sanden': ['8173']}]
2610
[{'AFI': ['0298'], 'CARLISLE': ['3015141'], 'Global Parts Distributors': ['5512801', '6512801', '7512801'], 'Omega': ['2008174'], 'Ranshu': ['14SD8174', '14SD8174NC'], 'Trad Automotive': ['C2734']}]
2611
[{'AFI': ['0298'], 'CARLISLE': ['3015141'], 'Global Parts Distributors': ['5512801', '6512801', '7512801'], 'Omega': ['2008174'], 'Ranshu': ['14SD8174', '14SD8174NC'], 'Trad Automotive': ['C2734']}]
2612
[{'CARLISLE': ['3015150'], 'Ranshu': ['14SD8182', '14SD8182NC'], 'Sanden': ['8182']}]
2613
[{'CARLISLE': ['3015160'], 'Sanden': ['8202']}]
2614
[{'CARLISLE': ['3015170', '3015171'], 'Global Parts Distributors': ['5513105', '6513105', '7513105'], 'JCB': ['320', '8562'], 'Omega': ['2008203'], 'Ranshu': ['14SD8203', '14SD8203NC'], 'Sanden': ['8203'], 'Sunair': ['CO2242CA'], 'Trad Automotive': ['C2801']}]
2615
[{'CARLISLE': ['3015180'], 'Sanden': ['8215']}]
2616
[{'Behr-Hella Service': ['8FK351126021'], 'CARLISLE': ['3015200'], 'Omega': ['2008025'], 'Sanden': ['7864', '8228']}]
2617
[{'CARLISLE': ['3015211'], 'DAF': ['1685170', '1815581'], 'Omega': ['2008231', '2008231AM'], 'Ranshu': ['14SD8231NC', '14SD8231NEW'], 'Sanden': ['8231'], 'Sunair': ['CO2169CA'], 'Trad Automotive': ['C2968']}]
2618
[{'CARLISLE': ['3015221'], 'Omega': ['2008242'], 'Ranshu': ['148242', '148242NC'], 'Sanden': ['8242'], 'Trad Automotive': ['C2291'], 'TTAC': ['3005383'], 'Volvo': ['11412631']}]
2619
[{'AP Air Inc.': ['5096154'], 'Austin Baker': ['10364851'], 'CARLISLE': ['3015230', '3015231'], 'Omega': ['2008243'], 'Sanden': ['8243'], 'Trad Automotive': ['C2368'], 'TTAC': ['3005382'], 'Volvo': ['11412632']}]
2620
[{'AP Air Inc.': ['5096154'], 'Austin Baker': ['10364851'], 'CARLISLE': ['3015230', '3015231'], 'Omega': ['2008243'], 'Sanden': ['8243'], 'Trad Automotive': ['C2368'], 'TTAC': ['3005382'], 'Volvo': ['11412632']}]
2621
[{'AFI': ['0849'], 'CARLISLE': ['3015240', '3015241'], 'Omega': ['2008244'], 'Ranshu': ['14SD8244', '14SD8244NC'], 'Sanden': ['8244'], 'Trad Automotive': ['C2797']}]
2622
[{'AFI': ['0162'], 'CARLISLE': ['3015250', '3015251'], 'Omega': ['2008252'], 'Ranshu': ['14SD4271', '14SD4271NC', '14SD4271NEW'], 'Sanden': ['8252']}]
2623
[{'AFI': ['0162'], 'CARLISLE': ['3015250', '3015251'], 'Omega': ['2008252'], 'Ranshu': ['14SD4271', '14SD4271NC', '14SD4271NEW'], 'Sanden': ['8252']}]
2624
[{'AFI': ['0062'], 'CARLISLE': ['3015260', '3015261'], 'Omega': ['2008253'], 'Ranshu': ['14SD4664C'], 'Sanden': ['8253']}]
2625
[{'AFI': ['0062'], 'CARLISLE': ['3015260', '3015261'], 'Omega': ['2008253'], 'Ranshu': ['14SD4664C'], 'Sanden': ['8253']}]
2626
[{'CARLISLE': ['3015270'], 'Omega': ['2008256', '2008256VT'], 'Sanden': ['8256', '8256VT']}]
2627
[{'CARLISLE': ['3015280'], 'Omega': ['2008263AM'], 'Renault': ['5010605474'], 'Sanden': ['8216', '8263'], 'Volvo': ['85000724']}]
2628
[{'CARLISLE': ['3015290'], 'Ranshu': ['14SD8279', '14SD8279NC', '14SD8279NEW'], 'Sanden': ['8279']}]
2629
[{'CARLISLE': ['3015300'], 'Sanden': ['8290']}]
2630
[{'AP Air Inc.': ['5096624'], 'CARLISLE': ['3015310', '3015311'], 'Omega': ['2008295'], 'Ranshu': ['14SD8295C', '14SD8295NC', '14SD8295NEW'], 'Sanden': ['8275', '8295'], 'Scania': ['1531196', '15504811', '1888032']}]

2631
[{'AP Air Inc.': ['5096624'], 'CARLISLE': ['3015310', '3015311'], 'Omega': ['2008295'], 'Ranshu': ['14SD8295C', '14SD8295NC', '14SD8295NEW'], 'Sanden': ['8275', '8295'], 'Scania': ['1531196', '15504811', '1888032']}]
2632
[{'Omega': ['2008296'], 'Sanden': ['8296']}]
2633
[{'Behr-Hella Service': ['8FK351002491'], 'CARLISLE': ['3015320'], 'MAN': ['51779707018'], 'Sanden': ['8298']}]
2634
[{'AC Delco': ['1521930', '152211'], 'CARLISLE': ['3015330'], 'Four Seasons': ['57035'], 'NAPA': ['967010', '975510', 'TEM967010', 'TEM975510'], 'Ranshu': ['14SD8353'], 'Sanden': ['8353'], 'Trad Automotive': ['C815'], 'Visteon': ['000687', '010230']}]
2635
[{'AC Delco': ['1521792'], 'Agco': ['4363723'], 'Airpro': ['208387'], 'Austin Baker': ['10302641', '10364881'], 'CARLISLE': ['3015340'], 'Compressor Works': ['618561'], 'Four Seasons': ['57561', '58561'], 'NAPA': ['967148', 'TEM967148'], 'Omega': ['2010142AM'], 'Sanden': ['8387'], 'Sunair': ['CO2054CA'], 'Trad Automotive': ['C2172'], 'Versatile': ['33634'], 'White': ['72504984']}]
2636
[{'AC Delco': ['1521782'], 'Airpro': ['208399'], 'CARLISLE': ['3015350'], 'Four Seasons': ['58541'], 'MEI': ['5999'], 'NAPA': ['274186', 'TEM274186'], 'Sanden': ['8399']}]
2637
[{'CARLISLE': ['3015361'], 'Compressor Works': ['639677'], 'Four Seasons': ['97571', '98571'], 'Global Parts Distributors': ['5512898', '6512898', '7512898'], 'Omega': ['2021892', '2021892R'], 'Ranshu': ['140689', '140689NC'], 'Saab': ['12792669'], 'Sanden': ['8628'], 'Trad Automotive': ['C1865']}]
2638
[{'CARLISLE': ['3015361'], 'Compressor Works': ['639677'], 'Four Seasons': ['97571', '98571'], 'Global Parts Distributors': ['5512898', '6512898', '7512898'], 'Omega': ['2021892', '2021892R'], 'Ranshu': ['140689', '140689NC'], 'Saab': ['12792669'], 'Sanden': ['8628'], 'Trad Automotive': ['C1865']}]
2639
[{'AC Delco': ['1522156'], 'Austin Baker': ['10366201'], 'CARLISLE': ['3015371'], 'Compressor Works': ['639518'], 'Four Seasons': ['97556', '98556'], 'General Motors': ['20772560', '20772570', '25836142'], 'Global Parts Distributors': ['5512560', '5512648', '6512560', '6512648', '7512560', '7512648'], 'NAPA': ['252366', '275750', 'TEM252366', 'TEM275750'], 'Omega': ['2008705', '2022156'], 'Ranshu': ['140407', '140407NC', '1422156'], 'Sanden': ['8702', '8705'], 'Trad Automotive': ['C2189', 'C2189R', 'C2511']}]
2640
[{'Omega': ['2008925'], 'Ranshu': ['14SD8925', '14SD8925NC'], 'Sanden': ['8925']}]
2641
[{'AP Air Inc.': ['509399', '5093993'], 'Global Parts Distributors': ['5512882', '6512882', '7512882'], 'Sanden': ['8926']}]
2642
[{'AP Air Inc.': ['509399', '5093993'], 'Global Parts Distributors': ['5512882', '6512882', '7512882'], 'Ranshu': ['14SD8926NC'], 'Sanden': ['8926']}]
2643
[{'CARLISLE': ['3015380'], 'Caterpillar': ['2298994'], 'Komatsu': ['423S624330'], 'MEI': ['58944'], 'Omega': ['2018948'], 'Ranshu': ['14SD8948', '14SD8948NC', '14SD8948NEW'], 'Sanden': ['8948']}]
2644
[{'CARLISLE': ['3015390'], 'Sanden': ['9016']}]
2645
[{'AC Delco': ['1521909'], 'Airpro': ['209026'], 'Alliance': ['ABPN83304079', 'ABPN83304242', 'ABPN8330479'], 'Austin Baker': ['10364921'], 'Bergstrom': ['525998'], 'CARLISLE': ['3015400'], 'Caterpillar': ['3301105'], 'Compressor Works': ['638550'], 'Coolstar': ['3301105'], 'Ford New Holland': ['450805'], 'I.H.': ['3405689R1', '80450805'], 'Kenworth': ['9026SAN'], 'Mack': ['85309026', '9026'], 'MEI': ['5926'], 'NAPA': ['967211', 'TEM967211'], 'Navistar': ['ZGG705018'], 'New Holland': ['89508380'], 'Omega': ['2010114', '206RD411AM'], 'Peterbilt': ['LE1225'], 'Red Dot': ['75R82242'], 'Sanden': ['9026'], 'Sunair': ['CO2214CA'], 'Trad Automotive': ['C1774'], 'TruckAir': ['033015']}]
2646
[{'AC Delco': ['1521783'], 'Airpro': ['209056'], 'CARLISLE': ['3015410'], 'Compressor Works': ['618541', '618542'], 'Four Seasons': ['57542', '58542'], 'Global Parts Distributors': ['5511547', '6511547', '7511547'], 'NAPA': ['274187', 'TEM274187'], 'Omega': ['2010100'], 'Ranshu': ['14SD9056', '14SD9056NC'], 'Sanden': ['9056'], 'Trad Automotive': ['C828']}]
2647
[{'Airpro': ['209096'], 'AP Air Inc.': ['509394'], 'CARLISLE': ['3015420'], 'Sanden': ['9096']}]
2648
[{'AC Delco': ['1521746'], 'Airpro': ['239104'], 'Alliance': ['ABPN83304202'], 'AP Air Inc.': ['509410'], 'Bergstrom': ['525853'], 'CARLISLE': ['3015431'], 'Compressor Works': ['618035'], 'Four Seasons': ['58035'], 'Freightliner': ['SKI9103'], 'Frigette': ['204207'], 'International': ['9103SAN'], 'Kenworth': ['9103SAN'], 'Kysor': ['1401006'], 'Mack': ['206RD45A', '206RD47A', '9103SAN'], 'Massey Ferguson': ['D45070015'], 'MEI': ['5903'], 'Omega': ['2010105', '2010105AM'], 'Peterbilt': ['206R45A'], 'Ranshu': ['14SD9103', '14SD9103C', '14SD9103NC', '14SD9103NEW'], 'Ready-Aire/Proliance': ['2174N'], 'Red Dot': ['75R8262'], 'Sanden': ['9103', '9104', '9203', '9677'], 'Steiger': ['602921T94'], 'Sunair': ['CO2057CA'], 'Trad Automotive': ['C803'], 'TTAC': ['3004101'], 'Versatile': ['63456'], 'Volvo': ['9103SAN'], 'Western Star': ['9103SAN']}]
2649
[{'AC Delco': ['1521785'], 'Airpro': ['209114'], 'Austin Baker': ['10345471'], 'CARLISLE': ['3015441'], 'Compressor Works': ['618546'], 'Four Seasons': ['58546'], 'Global Parts Distributors': ['5511548', '6511548', '7511548'], 'NAPA': ['967188', 'TEM967188'], 'Omega': ['2010169'], 'Ranshu': ['14SD9114C', '14SD9114NC', '14SD9114NEW', 'TL3004114'], 'Sanden': ['9114', '9136'], 'Sunair': ['CO2176CA'], 'Trad Automotive': ['C832', 'C832R'], 'TTAC': ['3004114'], 'Visteon': ['010231']}]
2650
[{'AC Delco': ['1521329'], 'Airpro': ['209120'], 'Alliance': ['ABPN83303272', 'ABPN83304684'], 'AP Air Inc.': ['509411'], 'Bergstrom': ['525854'], 'CARLISLE': ['3015451'], 'Carrier': ['501200A'], 'Case IH': ['9694'], 'Caterpillar': ['3301228'], 'Compressor Works': ['618507'], 'Coolstar': ['3301228'], 'Four Seasons': ['57507', '58507'], 'Freightliner': ['ABPN83304272', 'SKI9120'], 'Frigette': ['204454'], 'Global Parts Distributors': ['5511544', '6511544', '7511544'], 'I.H.': ['A177068'], 'International': ['544929C1', '9120'], 'Kenworth': ['5742', '5742SAN', 'LE1000'], 'Kysor': ['1401010'], 'Mack': ['206RD45', '206RD45AM', '206RD48AM'], 'Massey Ferguson': ['1690711M1'], 'MEI': ['5920'], 'NAPA': ['274024', 'TEM274024'], 'Omega': ['2010115', '2010115AM'], 'Peterbilt': ['1803536', '9120', '9120SAN', 'LE1000', 'LE1055'], 'Ranshu': ['14SD5742', '14SD5742NEW', '14SD9120', '14SD9120C', '14SD9120NC', '14SD9120NEW'], 'Red Dot': ['75R8212', 'RD554430P'], 'Sanden': ['4393', '5742', '5745', '9120'], 'Seltec': ['48826011'], 'Sterling': ['E93Z19703B'], 'Sunair': ['CO2041CA'], 'Trad Automotive': ['C2268'], 'TruckAir': ['033008', '033070'], 'TTAC': ['3004183', '3004422'], 'Visteon': ['010233'], 'Volvo': ['3918270'], 'Western Star': ['027029595']}]
2651
[{'CARLISLE': ['3015460'], 'Sanden': ['9140']}]
2652
[{'Four Seasons': ['57564', '58564'], 'I.H.': ['85812045'], 'Landini': ['3386861M1'], 'Omega': ['2009149AM'], 'Sanden': ['9149'], 'Sunair': ['CO2049CA'], 'Trad Automotive': ['C2473']}]
2653
[{'AC Delco': ['1521794', '1522103', '152212'], 'CARLISLE': ['3015470'], 'Compressor Works': ['618568'], 'Four Seasons': ['57568', '57622', '58568'], 'NAPA': ['254006', '274146', 'TEM254006', 'TEM274146'], 'Sanden': ['9173']}]
2654
[{'AC Delco': ['1522098'], 'Airpro': ['209263'], 'Austin Baker': ['10302900'], 'CARLISLE': ['3015480'], 'Compressor Works': ['618547'], 'Four Seasons': ['57547', '58547'], 'Hesston': ['5116929'], 'NAPA': ['254032', '967192', 'TEM254032', 'TEM967192'], 'Omega': ['2010164'], 'Ranshu': ['14SD9263', '14SD9263NC'], 'Sanden': ['9263'], 'Sunair': ['CO2061CA'], 'Trad Automotive': ['C1695'], 'Visteon': ['010245']}]
2655
[{'Airpro': ['209283'], 'CARLISLE': ['3015490'], 'Sanden': ['9283'], 'Trad Automotive': ['C810']}]
2656
[{'AC Delco': ['1520592', '1520712', '1521778', '1521787'], 'Alliance': ['ABPN83307812'], 'American Motors': ['J3741284'], 'AP Air Inc.': ['509402'], 'Austin Baker': ['10302660'], 'Bergstrom': ['304022', '525689', '525732'], 'CARLISLE': ['3015501'], 'Chrysler': ['4798258'], 'Compressor Works': ['618551', '639519'], 'Deutz-Allis': ['7807944'], 'Ford': ['E7GZ19703B'], 'Four Seasons': ['57551', '58551'], 'Freightliner': ['ABPN83304832', 'MBTA6811310201'], 'Frigette': ['204249'], 'General Motors': ['15557973'], 'Global Air Inc.': ['CO2501'], 'Global Cool Cars': ['0938Z0115'], 'Global Parts Distributors': ['5511550', '6511550', '7511550'], 'Hesston': ['SFD013769'], 'Mack': ['206RD410A'], 'MEI': ['5985'], 'NAPA': ['254001', '274195', 'TEM254001', 'TEM274195'], 'Omega': ['2010106', '2010157', '2010232', '2046100'], 'Panafrio': ['2014365'], 'Peterbilt': ['9285SAN'], 'Ranshu': ['14SD9285', '14SD9285N'], 'Ready-Aire/Proliance': ['2165', '2165N'], 'Red Dot': ['75R8292'], 'Sanden': ['9285', '9515'], 'Spectra Premium': ['0658551'], 'Sunair': ['CO2062CA'], 'Trad Automotive': ['C1074', 'C814'], 'TruckAir': ['033005'], 'TTAC': ['3004182'], 'Visteon': ['000595', '010240'], 'Volvo': ['3916160', '3918271', '611040004', '611040017', '611040023', '611040028', '61104017']}]

2657
[{'AC Delco': ['1521261'], 'Audi/Volkswagen': ['176820804A'], 'Austin Baker': ['10307360', '10307361'], 'CARLISLE': ['3015510'], 'Compressor Works': ['618113'], 'Four Seasons': ['57113', '58113'], 'Frigette': ['204571'], 'Global Parts Distributors': ['5511664', '6511664', '7511664'], 'Omega': ['2010047', '2010047R'], 'Ready-Aire/Proliance': ['2151', '2151N'], 'Sanden': ['9288', '9533'], 'Tech Choice Parts': ['30218'], 'Trad Automotive': ['C1150', 'C1150R', 'C967', 'C967R'], 'Visteon': ['000596', '015113']}]
2658
[{'CARLISLE': ['3015520'], 'Omega': ['2010104'], 'Sanden': ['9513'], 'Trad Automotive': ['C808']}]
2659
[{'AC Delco': ['1521813'], 'AP Air Inc.': ['509420'], 'Austin Baker': ['10347191'], 'CARLISLE': ['3015530'], 'Compressor Works': ['618638'], 'Four Seasons': ['57638', '58638'], 'Freightliner': ['ABPN83304002'], 'Global Parts Distributors': ['5511575', '6511575', '7511575'], 'NAPA': ['961157', 'TEM961157'], 'Omega': ['2010096'], 'Peterbilt': ['9514SAN'], 'Sanden': ['9514'], 'Trad Automotive': ['C1986'], 'Visteon': ['010244']}]
2660
[{'AC Delco': ['1521110', '1521798'], 'Alliance': ['ABPN83304462'], 'Austin Baker': ['10301731'], 'Bergstrom': ['525759', '525915'], 'CARLISLE': ['3015541'], 'Carrier': ['512029'], 'Caterpillar': ['3301106'], 'Compressor Works': ['618589'], 'Coolstar': ['3301106'], 'Four Seasons': ['57589'], 'Freightliner': ['304152', 'ABPN83304152', 'SKI9537'], 'Frigette': ['204253'], 'Global Air Inc.': ['CO2502'], 'Global Cool Cars': ['0938Z0114'], 'Global Parts Distributors': ['5511565', '6511565', '7511565'], 'Hesston': ['259379'], 'International': ['1682425C92'], 'Kysor': ['1401015', '1401017', '402792'], 'MEI': ['5937'], 'NAPA': ['274144', 'TEM274144'], 'Navistar': ['1682425C92', '1684560C92'], 'Omega': ['2010107', '2010107AM', '2010107R'], 'Peterbilt': ['9537SAN', 'LE1090'], 'Ranshu': ['14SD9537'], 'Ready-Aire/Proliance': ['2168N'], 'Red Dot': ['75R8272', '75R8272DS', 'RD556960', 'RD556960DS', 'RD556960P'], 'Sanden': ['9537'], 'Sunair': ['CO2216CA'], 'Trad Automotive': ['C816'], 'TruckAir': ['023172', '033084'], 'TTAC': ['3004186'], 'Visteon': ['010246'], 'Volvo': ['3918287']}]
2661
[{'AC Delco': ['1521797'], 'CARLISLE': ['3015550'], 'Compressor Works': ['618588'], 'Four Seasons': ['57588', '58588'], 'Frigette': ['204363'], 'Global Parts Distributors': ['5511564', '6511564', '7511564'], 'NAPA': ['967026', 'TEM967026'], 'Omega': ['2010127'], 'Sanden': ['9563'], 'Trad Automotive': ['C841']}]
2662
[{'CARLISLE': ['3015560'], 'Sanden': ['9580']}]
2663
[{'CARLISLE': ['3015570']}]
2664
[{'CARLISLE': ['3015580'], 'Sanden': ['9663']}]
2665
[{'CARLISLE': ['3015590'], 'MEI': ['5989'], 'Sanden': ['9669']}]
2666
[{'AC Delco': ['1521790'], 'CARLISLE': ['3015600'], 'Compressor Works': ['618557'], 'Four Seasons': ['57557', '58557'], 'Global Parts Distributors': ['5511554', '6511554', '7511554'], 'Massey Ferguson': ['1688310M1'], 'NAPA': ['967027', 'TEM967027'], 'Omega': ['2010055'], 'Ranshu': ['14SD9689', '14SD9689NC'], 'Sanden': ['9689'], 'Sunair': ['CO2063CA'], 'Trad Automotive': ['C834'], 'Visteon': ['010249']}]
2667
[{'AC Delco': ['1520597'], 'Acura/Honda': ['38800PM5A02', '38800PM9A11'], 'Austin Baker': ['10309220', '10309221'], 'Four Seasons': ['57570', '58570'], 'Frigette': ['2041490'], 'Global Parts Distributors': ['5511558', '6511558', '7511558'], 'NAPA': ['254064', 'TEM254064'], 'Omega': ['2010743', '2010743R'], 'Ranshu': ['142470', '142470C', '142470NC', '142470NEW'], 'Ready-Aire/Proliance': ['2207'], 'Sanden': ['9774', '9786'], 'Trad Automotive': ['C884', 'C884R'], 'Visteon': ['000617']}]
2668
[{'AFI': ['0544', '0664', '0855', '0893'], 'Austin Baker': ['10361841'], 'CARLISLE': ['3015611'], 'Compressor Works': ['639386'], 'Denso Automotive Systems': ['4472606410', '4710900'], 'Ford': ['7T4Z19703A', '8T4Z19703A', 'BT4Z19703A'], 'Four Seasons': ['157314', '158314'], 'Global Parts Distributors': ['5512379', '5512998', '6512379', '6512998', '7512379', '7512998'], 'Motorcraft': ['YCC226', 'YCC230', 'YCC259'], 'NAPA': ['255683', '275804', 'TEM255683', 'TEM275804'], 'Omega': ['2011044', '2011044AM', '2011044R'], 'Ranshu': ['140426', '140426C', '140426NC', '140851', '140851FD', '140851NC', '140851NEW'], 'Spectra Premium': ['0610328'], 'Tech Choice Parts': ['23625'], 'Trad Automotive': ['C1765', 'C1765R', 'C2582']}]
2669
[{'Austin Baker': ['10363651'], 'CARLISLE': ['3015621'], 'Compressor Works': ['638727'], 'Ford': ['8C2Z19703AA', '8C2Z19703CA', 'AU2Z19V703AJ'], 'Four Seasons': ['168197', '67197', '68197'], 'Global Parts Distributors': ['5512687', '6512687', '7512687'], 'MEI': ['51202'], 'Motorcraft': ['YC2538', 'YCC289', 'YCC315'], 'NAPA': ['255772', '275815', 'TEM255772', 'TEM275815'], 'Omega': ['2011047', '2011047AM'], 'Ranshu': ['140538', '140538FD', '140538NC'], 'Trad Automotive': ['C2102', 'C2102R']}]
2670
[{'AFI': ['0856', '545'], 'CARLISLE': ['3015631'], 'Compressor Works': ['648311'], 'Denso Automotive Systems': ['4472809440'], 'Ford': ['68201076', 'BB5319D629DA', 'BB5319D629DB', 'BB5319D629DC', 'BB5Z19703A', 'BB5Z19703B', 'DB5Z19703A', 'EB5319D629AA', 'EB5Z19703B'], 'Four Seasons': ['97332', '98332'], 'Global Parts Distributors': ['5512991', '6512991', '7512991'], 'Motorcraft': ['YCC269', 'YCC299', 'YCC310', 'YCC358'], 'NAPA': ['276047', 'TEM276047'], 'Omega': ['2022163', '2022163AM'], 'Ranshu': ['140878', '140878C', '140878NC', '140879', '140879C', '140879FD', '140879NC', '140879NEW'], 'Spectra Premium': ['0610304'], 'Trad Automotive': ['C2585', 'C2585R', 'C2741R']}]
2671
[{'Acura/Honda': ['38810R1AA01'], 'AFI': ['0894'], 'CARLISLE': ['3015641'], 'Compressor Works': ['639605'], 'Four Seasons': ['97584', '98584'], 'Global Parts Distributors': ['5512982', '6512982', '7512982'], 'NAPA': ['256168', '276238', 'TEM256168', 'TEM276238'], 'Omega': ['2003770', '2003770AM'], 'Ranshu': ['141260', '141260NC', '141260NEW'], 'Sanden': ['3770'], 'Spectra Premium': ['0610360'], 'Trad Automotive': ['C2535', 'C2535R']}]
2672
[{'Acura/Honda': ['38810R1AA01'], 'AFI': ['0894'], 'Compressor Works': ['639605'], 'Four Seasons': ['97584', '98584'], 'Global Parts Distributors': ['5512982', '6512982', '7512982'], 'NAPA': ['256168', '276238', 'TEM256168', 'TEM276238'], 'Omega': ['2003770', '2003770AM'], 'Ranshu': ['141260', '141260NC'], 'Sanden': ['3770'], 'Trad Automotive': ['C2535', 'C2535R']}]
2673
[{'Behr-Hella Service': ['8FK351272181'], 'CARLISLE': ['3015651'], 'Ford': ['AP3119D629BA', 'AP3119D629BB', 'AV1119D629AA', 'AV1119D629AB', 'AV1119D629AC', 'AV1119D629BA', 'AV1119D629BB', 'AV1Z19703B', 'AV1Z19703C', 'AV1Z19703K'], 'Four Seasons': ['178398'], 'Global Parts Distributors': ['5513101', '6513101', '7513101'], 'Motorcraft': ['YCC354', 'YCC384', 'YCC445'], 'Omega': ['2022532AM'], 'Ranshu': ['141121', '141121C', '141121NC', '141121NEW'], 'Trad Automotive': ['C2877']}]
2674
[{'Chrysler': ['5181968AB']}]
2675
[{'Chrysler': ['5264745']}]
2676
[{'Chrysler': ['53001438']}]
2677
[{'Chrysler': ['55036679']}]
2678
[{'Chrysler': ['68289890AB'], 'Four Seasons': ['178342']}]
2679
[{'Chrysler': ['68376684AD', '68376684AE']}]
2680
[{'Chrysler': ['68439253AA']}]
2681
[{'Chrysler': ['68481137AA', '68481137AB']}]
2682
[{}]
2683
[{}]
2684
[{'Ford': ['JX6Z19703H', 'JX6Z19703L', 'JX6Z19703M'], 'Motorcraft': ['YCC590']}]
2685
[{'Ford': ['LX6Z19703U']}]
2686
[{'Ford': ['ML3Z19703B', 'ML3Z19703G']}]
2687
[{'Ford': ['NL1Z19703A']}]
2688
[{'Fiat': ['68439272AA']}]
2689
[{'General Motors': ['12567478']}]
2690
[{'General Motors': ['12569286']}]
2691
[{'General Motors': ['13271263']}]
2692
[{'AC Delco': ['1522418'], 'Four Seasons': ['68570'], 'General Motors': ['39067791', '39133197', '39139989', '39176466', '39176469', '8819A9970'], 'Omega': ['2011718'], 'Ranshu': ['141418C', '141418NEW'], 'Sanden': ['3197', '3197U', '6466', '6466U', '6469', '7791', '7791U']}]
2693
[{'AC Delco': ['1522350'], 'Four Seasons': ['168364'], 'General Motors': ['42483362', '94551798'], 'NAPA': ['TEM276304'], 'Ranshu': ['1422350C', '1422350GM', '1422350NC']}]
2694
[{'General Motors': ['42502600', '42628294']}]
2695
[{'Four Seasons': ['98497'], 'General Motors': ['42733186', '60004587'], 'Ranshu': ['1410008GM']}]
2696
[{'Four Seasons': ['98497'], 'General Motors': ['42733191']}]
2697
[{'General Motors': ['84021290']}]

2698
[{'AC Delco': ['1522388'], 'Four Seasons': ['198328'], 'General Motors': ['84134706', '84208256', '86807267'], 'Global Parts Distributors': ['7513443'], 'Omega': ['2011779'], 'Ranshu': ['1422388C', '1422388GM']}]
2699
[{'AC Delco': ['1522398'], 'General Motors': ['84308415', '84334591'], 'Ranshu': ['1422398', '1422398C', '1422398GM']}]
2700
[{'General Motors': ['84253504', '84338629', '86792440']}]
2701
[{'General Motors': ['84441372']}]
2702
[{'General Motors': ['84488491']}]
2703
[{'General Motors': ['84516974'], 'Ranshu': ['141965C'], 'Trad Automotive': ['C3536']}]
2704
[{'General Motors': ['84610777']}]
2705
[{'General Motors': ['84650874']}]
2706
[{'General Motors': ['84664206', '84849912', '86789847']}]
2707
[{'General Motors': ['84664213']}]
2708
[{'General Motors': ['2636514', '84635616', '84666664']}]
2709
[{'General Motors': ['84726380']}]
2710
[{'AC Delco': ['1522345'], 'CARLISLE': ['3024271'], 'Four Seasons': ['168398'], 'General Motors': ['23422345', '84309304', '84802769', '86792423'], 'Ranshu': ['1422345GM'], 'Trad Automotive': ['C14']}]
2711
[{'General Motors': ['84849910']}]
2712
[{'General Motors': ['84856232']}]
2713
[{}]
2714
[{}]
2715
[{'General Motors': ['97386417']}]
2716
[{'Acura/Honda': ['388005RDA01']}]
2717
[{'Acura/Honda': ['388005WJA01', '388005WJA02']}]
2718
[{'Acura/Honda': ['388006C2A02']}]
2719
[{'Acura/Honda': ['388006L2A01'], 'Global Parts Distributors': ['7513402']}]
2720
[{'Acura/Honda': ['3881051MA21', '3881051MA22']}]
2721
[{'Acura/Honda': ['3881058RG01']}]
2722
[{'Acura/Honda': ['388105WMA11']}]
2723
[{'Acura/Honda': ['3881064AA02']}]
2724
[{'Acura/Honda': ['3881064SA01']}]
2725
[{'Acura/Honda': ['388106A0A01'], 'Denso Automotive Systems': ['4472502040'], 'Four Seasons': ['178320'], 'Global Parts Distributors': ['6513356', '7513356'], 'Omega': ['2011749'], 'Ranshu': ['141588', '141588C', '141588NC'], 'Trad Automotive': ['C3367']}]
2726
[{'Hyundai/Kia': ['977013T500']}]
2727
[{'Hyundai/Kia': ['97701A7200']}]
2728
[{'Hyundai/Kia': ['97701A7300']}]
2729
[{'Hyundai/Kia': ['97701AA100']}]
2730
[{'Hyundai/Kia': ['97701AA250']}]
2731
[{'Hyundai/Kia': ['97701B1200']}]
2732
[{'GENESIS': ['97701B1400']}]
2733
[{'Global Parts Distributors': ['7513404'], 'Hyundai/Kia': ['97701C2500']}]
2734
[{'GENESIS': ['97701D2400']}]
2735
[{'Hyundai/Kia': ['97701D2550']}]
2736
[{'Hyundai/Kia': ['97701D2650']}]
2737
[{'Four Seasons': ['198374'], 'Hyundai/Kia': ['97701D3750']}]
2738
[{'Hyundai/Kia': ['97701E6100']}]
2739
[{'Hyundai/Kia': ['97701F3300']}]
2740
[{'Hyundai/Kia': ['97701F6100']}]
2741
[{'Hyundai/Kia': ['97701G3000']}]
2742
[{'Hyundai/Kia': ['97701G3100']}]
2743
[{'Hyundai/Kia': ['97701G3300']}]
2744
[{'Hyundai/Kia': ['97701G4300']}]
2745
[{'Hyundai/Kia': ['97701J3090']}]
2746
[{'Hyundai/Kia': ['97701J3490']}]
2747
[{'Hyundai/Kia': ['97701J6100']}]
2748
[{'Hyundai/Kia': ['97701K2150']}]
2749
[{'Hyundai/Kia': ['97701K4000']}]
2750
[{'Hyundai/Kia': ['97701K9000']}]
2751
[{'Hyundai/Kia': ['97701L0000']}]
2752
[{'Hyundai/Kia': ['97701L1800']}]
2753
[{'Hyundai/Kia': ['97701L2350']}]
2754
[{'Hyundai/Kia': ['97701M5000']}]
2755
[{'Hyundai/Kia': ['97701N9600']}]
2756
[{'Hyundai/Kia': ['97701P2500', '97701P2500RU']}]
2757
[{'Four Seasons': ['198363'], 'Hyundai/Kia': ['97701S2700']}]
2758
[{'Hyundai/Kia': ['97701S8500']}]
2759
[{'Hyundai/Kia': ['97729P0000']}]
2760
[{'Hyundai/Kia': ['97729P4000']}]
2761
[{'Hyundai/Kia': ['97729L5000', '977E1L5000'], 'Trad Automotive': ['C3183']}]
2762
[{'Nissan/Infiniti': ['926005NA2A']}]
2763
[{'Nissan/Infiniti': ['926009NC0A', '926009NC0B']}]
2764
[{'Nissan/Infiniti': ['926101CB0A']}]
2765
[{'John Deere': ['19H1930']}]
2766
[{'John Deere': ['19M8007']}]
2767
[{'John Deere': ['57M7267']}]
2768
[{'AP Air Inc.': ['4511179'], 'John Deere': ['AL78780'], 'Omega': ['3510043']}]
2769
[{'John Deere': ['R71196']}]
2770
[{'John Deere': ['RE69715']}]
2771
[{'Hyundai/Kia': ['977013T300']}]
2772
[{'Hyundai/Kia': ['97701A5001', '97701A7500']}]
2773
[{'Hyundai/Kia': ['97701C6900']}]
2774
[{'Hyundai/Kia': ['97701C6910']}]
2775
[{'Hyundai/Kia': ['97701C6960']}]
2776
[{'Four Seasons': ['198397'], 'Hyundai/Kia': ['97701D3950']}]
2777
[{'Hyundai/Kia': ['97701D5600']}]
2778
[{'Hyundai/Kia': ['97701F6600']}]
2779
[{'Hyundai/Kia': ['97701A6502', '97701G4100']}]
2780
[{'Hyundai/Kia': ['97701J6000']}]
2781
[{'Hyundai/Kia': ['97701K0000'], 'Ranshu': ['141722C', '141722NC']}]
2782
[{'Hyundai/Kia': ['97701M6550']}]
2783
[{'Hyundai/Kia': ['97701M7100']}]
2784
[{'Hyundai/Kia': ['97701M7150']}]
2785
[{'Hyundai/Kia': ['97729K4000']}]
2786
[{'Toyota/Lexus': ['8831024191']}]
2787
[{'Toyota/Lexus': ['8846060560']}]
2788
[{'Land Rover': ['LR112585']}]
2789
[{'CARLISLE': ['3022951'], 'Compressor Works': ['638938'], 'Four Seasons': ['97491', '98491'], 'Global Parts Distributors': ['5512965', '6512965', '7512965'], 'Mitsubishi': ['7812A215', '7813A197', '7813A211', '7813A212', '7813A349', '7813A350', '7813A370', '7813A399', '7813A401', '7813A416', '7813A418', '7813A480', '7813A618', '7813A648', '7813A737', '7813A788', '7813A803', '7813A835', '7813A855', '7813A857', '7813A871', '7813A969', '7813A978', '7813B090', 'AKS200A208A', 'AKS200A402', 'AKS200A402B', 'AKS200A407B', 'AKS200A411C', 'AKS200A413B', 'AKS200A413C', 'AKT200A410C', 'AKT200A411C', 'AKT200A424C', 'AKV200A205AS', 'AKV200A403C', 'AKV200A408C', 'AKV200A410C', 'AKV200A414C', 'AKV200A419CS', 'AKV200A421C', 'AKV200A433CS', 'AKV200A434C', 'AKV200A437C', 'AKV200A853A', 'AKV201A409G', 'BODY:7813A212', 'BODY:7813A229', 'BODY:7813A350', 'BODY:7813A365', 'BODY:7813A402', 'BODY:7813A419', 'BODY:7813A824', 'BODY:7813A989', 'BODY:AKS200A402C', 'BODY:AKS200A407C'], 'NAPA': ['255321', 'TEM255321'], 'Omega': ['2022153', '2022153AM', '2022153R'], 'Ranshu': ['140802', '140802C', '140802NC', '140802NEW', '140802RC'], 'Trad Automotive': ['C2158', 'C2158R']}]
2790
[{'Mitsubishi': ['7813A784']}]
2791
[{'Mitsubishi': ['7813A801', 'AKV200A419J']}]
2792
[{'Mitsubishi': ['7813A815']}]
2793
[{'Mitsubishi': ['7813A873']}]
2794
[{'Mitsubishi': ['7813A969']}]
2795
[{'Mitsubishi': ['7813A972']}]
2796
[{'Mitsubishi': ['7813A977']}]
2797
[{'Mitsubishi': ['7813A928', '7813A991']}]
2798
[{'Mitsubishi': ['7813B071']}]
2799
[{}]
2800
[{}]
2801
[{}]
2802
[{}]
2803
[{}]
2804
[{}]
2805
[{}]
2806
[{}]
2807
[{}]
2808
[{}]
2809
[{'AC Delco': ['1521234'], 'Atco': ['902038'], 'Austin Baker': ['10309490'], 'CARLISLE': ['3014011'], 'Compressor Works': ['639870'], 'Denso Automotive Systems': ['4710233'], 'Four Seasons': ['57338', '58338'], 'Global Parts Distributors': ['5511816', '6511816', '7511816'], 'Mercedes Benz': ['0002302511', '1161310001'], 'NAPA': ['254184', '274173', 'TEM254184', 'TEM274173'], 'Omega': ['2021617', '2021617R'], 'Ranshu': ['142675', '142675C', '142675NC'], 'Ready-Aire/Proliance': ['1811'], 'Tech Choice Parts': ['25140'], 'Trad Automotive': ['C1208', 'C1208R'], 'Visteon': ['000207']}]
2810
[{'Mercedes Benz': ['0022307211', '002230721180', '002230721187', '9068302401', '906830240180', '906830240187', 'A0022307211', 'A002230721180', 'A002230721187', 'A9068302401', 'A906830240180', 'A906830240187'], 'NRF': ['32214G'], 'Ranshu': ['145010', '145010C', '145010NC', '145010NEW'], 'Valeo': ['813157']}]
2811
[{'Mazda': ['BDGF61450', 'BDGH61450']}]
2812
[{'Mazda': ['BHAA61450']}]
2813
[{'Mazda': ['KB8E61450']}]
2814
[{'Nissan/Infiniti': ['926004AY0A', '926004AY0B', '926004AY1B']}]
2815
[{'Four Seasons': ['198585'], 'Nissan/Infiniti': ['926004BA1A']}]
2816
[{'Nissan/Infiniti': ['926006GK0A']}]
2817
[{'Nissan/Infiniti': ['926006MA0A']}]
2818
[{'Nissan/Infiniti': ['926006SA0C']}]
2819
[{'Nissan/Infiniti': ['926009BT0B']}]
2820
[{'Nissan/Infiniti': ['926009BV0A']}]
2821
[{'Nissan/Infiniti': ['926009FV3B']}]
2822
[{'Nissan/Infiniti': ['926009FV5A']}]
2823
[{'Nissan/Infiniti': ['926009SM0A']}]
2824
[{'Nissan/Infiniti': ['92600JF01B']}]
2825
[{'Subaru': ['73111AL020']}]
2826
[{'Subaru': ['73111AN01A']}]
2827
[{'Subaru': ['73111FL140']}]
2828
[{'Subaru': ['73111FL14A']}]
2829
[{'Subaru': ['73111FL150']}]
2830
[{'Tesla': ['106336900H']}]
2831
[{'Tesla': ['108819800P']}]
2832
[{'Ranshu': ['140715', '140715C', '140715NC', '140715NEW', '140715NIP'], 'Toyota/Lexus': ['8831008083'], 'Trad Automotive': ['C2571']}]

2833
[{'Toyota/Lexus': ['8831033330']}]
2834
[{'Toyota/Lexus': ['8831035A60', '8832028210', '883202821084', '8832035450', '883203545084', '8832035600', '8832060580', 'CLUTCH:8841060450']}]
2835
[{'AFI': ['274'], 'Austin Baker': ['10362480', '10362481'], 'CARLISLE': ['3017751'], 'Compressor Works': ['639839'], 'Denso Automotive Systems': ['4710622', '4711622'], 'Four Seasons': ['157318', '158318'], 'Global Parts Distributors': ['5512467', '6512467', '7512467'], 'NAPA': ['255283', '275834', 'TEM255283', 'TEM275834'], 'Omega': ['2022035', '2022035AM', '2022035R', '2025083'], 'Panafrio': ['2013645'], 'Ranshu': ['140343', '140343C', '140343NC', '140343NEW', '140343NIP', '140658', '140658C'], 'Spectra Premium': ['0610330'], 'Tech Choice Parts': ['22492'], 'Toyota/Lexus': ['883105248', '8831052480', '8831052481'], 'Trad Automotive': ['C1887', 'C1887R', 'C2780R']}]
2836
[{'Global Parts Distributors': ['6513403', '7513403'], 'Ranshu': ['141152', '141152NC'], 'Toyota/Lexus': ['88310F4010', '88310F4050'], 'Trad Automotive': ['C3519']}]
2837
[{'Toyota/Lexus': ['88310WAA02']}]
2838
[{}]
2839
[{'Toyota/Lexus': ['883201224084']}]
2840
[{'Toyota/Lexus': ['8832060680']}]
2841
[{'Toyota/Lexus': ['8832060B80', 'CLUTCH:884100C140']}]
2842
[{'Global Parts Distributors': ['7513065'], 'Omega': ['2022172'], 'Ranshu': ['140465', '140465C', '140465NC'], 'Toyota/Lexus': ['8837033020'], 'Trad Automotive': ['C2790', 'C2790R']}]
2843
[{'Toyota/Lexus': ['8837042040']}]
2844
[{'Toyota/Lexus': ['8837048170']}]
2845
[{'Toyota/Lexus': ['8837062010']}]
2846
[{'Toyota/Lexus': ['8837062021']}]
2847
[{'Toyota/Lexus': ['8843108010']}]
2848
[{'Volvo': ['36010353']}]
2849
[{'Audi/Volkswagen': ['5QE816803E', '5QE816803G']}]
2850
[{'Ford': ['E8AZ19703C'], 'Motorcraft': ['YC153', 'YC57']}]
2851
[{'Ford': ['XW4Z19703CA'], 'Motorcraft': ['YC2479']}]
2852
[{'Compressor Works': ['639790'], 'Ford': ['AR3Z19703A'], 'Four Seasons': ['98454'], 'Global Parts Distributors': ['5512954', '6512954', '7512954'], 'Motorcraft': ['YC2552'], 'Omega': ['2022113'], 'Ranshu': ['144470', '144470C', '144470NC', '144470NEW'], 'Trad Automotive': ['C2663']}]
2853
[{'Ford': ['BR3Z19703C'], 'Motorcraft': ['YC2560']}]
2854
[{'Ford': ['F1FZ19703A', 'F1FZ19703J'], 'Global Parts Distributors': ['5513206', '6513206', '7513206'], 'Motorcraft': ['YCC396'], 'Omega': ['2020825'], 'Ranshu': ['141232', '141232C', '141232NC'], 'Santech': ['2020825']}]
2855
[{'Ford': ['GV6Z19703U'], 'Motorcraft': ['YCC436'], 'Ranshu': ['141480', '141480C', '141480FD', '141480NC']}]
2856
[{'Behr-Hella Service': ['8FK351272181'], 'CARLISLE': ['3015651'], 'Ford': ['AP3119D629BA', 'AP3119D629BB', 'AV1119D629AA', 'AV1119D629AB', 'AV1119D629AC', 'AV1119D629BA', 'AV1119D629BB', 'AV1Z19703B', 'AV1Z19703C', 'AV1Z19703K'], 'Four Seasons': ['178398'], 'Global Parts Distributors': ['5513101', '6513101', '7513101'], 'Motorcraft': ['YCC354', 'YCC384', 'YCC445'], 'Omega': ['2022532AM'], 'Ranshu': ['141121', '141121C', '141121NC', '141121NEW'], 'Trad Automotive': ['C2877']}]
2857
[{'Ford': ['DV6Z19703A', 'DV6Z19703F'], 'Global Parts Distributors': ['7513437'], 'Motorcraft': ['YCC397', 'YCC474'], 'Omega': ['2022295'], 'Ranshu': ['141489C', '141489FD', '141489NC'], 'Trad Automotive': ['C3253']}]
2858
[{'Ford': ['GR3B19D629EB', 'GR3B19D629EC', 'GR3B19D629ED', 'GR3B19D629EE', 'GR3B19D629EF', 'GR3B19D629EG', 'GR3B19D629EH', 'GR3Z19703A', 'GR3Z19703D', 'GR3Z19703E'], 'Four Seasons': ['158661'], 'Motorcraft': ['YCC388', 'YCC442', 'YCC478']}]
2859
[{'Ford': ['KV6Z19703A'], 'Motorcraft': ['YCC516'], 'Trad Automotive': ['C130']}]
2860
[{'Ford': ['K2GZ19703A'], 'Four Seasons': ['168336'], 'Motorcraft': ['YCC526'], 'Omega': ['2011050'], 'Ranshu': ['141755C', '141755FD', '141755NC'], 'Trad Automotive': ['C103']}]
2861
[{'Ford': ['K2GZ19703B'], 'Four Seasons': ['168337'], 'Global Parts Distributors': ['7513413'], 'Motorcraft': ['YCC527'], 'Omega': ['2022299'], 'Ranshu': ['141756C', '141756FD', '141756NC'], 'Trad Automotive': ['C140']}]
2862
[{'Ford': ['L1MH19D629AB', 'L1MZ19703AB'], 'Motorcraft': ['YCC564'], 'Ranshu': ['141845C', '141845NC']}]
2863
[{'Ford': ['L1MZ19703EB', 'L1MZ19703F'], 'Four Seasons': ['178356'], 'Motorcraft': ['YCC566', 'YCC617']}]
2864
[{'Ford': ['LX6Z19703AB'], 'Motorcraft': ['YCC576']}]
2865
[{'Ford': ['JL3Z19703DB', 'JL3Z19703DC', 'JL3Z19703DD'], 'Four Seasons': ['198329'], 'Global Parts Distributors': ['7513416'], 'Motorcraft': ['YCC461', 'YCC581', 'YCC621'], 'Ranshu': ['141750C', '141750FD']}]
2866
[{'Ford': ['ML3Z19703D'], 'Motorcraft': ['YCC586']}]
2867
[{'Ford': ['JX6Z19703H', 'JX6Z19703L', 'JX6Z19703M'], 'Motorcraft': ['YCC590']}]
2868
[{'Ford': ['L1MZ19703CD'], 'Motorcraft': ['YCC598']}]
2869
[{'Ford': ['L1MZ19703DD'], 'Motorcraft': ['YCC599']}]
2870
[{'Ford': ['LC3Z19703BC'], 'Motorcraft': ['YCC603']}]
2871
[{'Ford': ['LK4Z19703A', 'LK4Z19703B'], 'Motorcraft': ['YCC575', 'YCC604']}]
2872
[{'Ford': ['ML3Z19703F'], 'Motorcraft': ['YCC607']}]
2873
[{'Ford': ['LC3H19D629AE', 'LC3H19D629AF', 'LC3H19D629AG', 'LC3H19D629AH', 'LC3Z19703AE', 'LC3Z19703C', 'LC3Z19703G'], 'Motorcraft': ['YCC602', 'YCC613', 'YCC629', 'YCC636']}]
2874
[{'Ford': ['ML3Z19703E', 'ML3Z19703J'], 'Motorcraft': ['YCC606', 'YCC625']}]

     Part_Number                                                 OE status
0       15 20061  [{'AC Delco': ['1520061'], 'Austin Baker': ['1...     ok
1       15 20062  [{'AC Delco': ['1520062'], 'Delphi Automotive ...     ok
2       15 20162  [{'AC Delco': ['1520162'], 'General Motors': [...     ok
3      15 20228Z  [{'AC Delco': ['1520006', '1520228', '1520228Z...     ok
4      15 20234Z  [{'AC Delco': ['1520234', '1520263', '1521958'...     ok
...          ...                                                ...    ...
2870     YCC 603  [{'Ford': ['LC3Z19703BC'], 'Motorcraft': ['YCC...     ok
2871     YCC 604  [{'Ford': ['LK4Z19703A', 'LK4Z19703B'], 'Motor...     ok
2872     YCC 607  [{'Ford': ['ML3Z19703F'], 'Motorcraft': ['YCC6...     ok
2873     YCC 613  [{'Ford': ['LC3H19D629AE', 'LC3H19D629AF', 'LC...     ok
2874     YCC 625  [{'Ford': ['ML3Z19703E', 'ML3Z19703J'], 'Motor...     ok

[2875 rows x 3 columns]

In [41]:
df.to_excel(r'C:\Users\YangTeng\Desktop\UAC-OE\全.xlsx', index=False)