In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
from lxml import etree

ua = pd.read_excel(r'C:\Users\YangTeng\Desktop\UAC-Compressor Assembly\menu.xlsx', header=0)
# ua_no = ua['No']
# ua_no
ua_Part_Number = ua['Part_Number'] 
ua_Part_Number

0        15 20061
1        15 20062
2        15 20162
3       15 20228Z
4       15 20234Z
          ...
2870      YCC 603
2871      YCC 604
2872      YCC 607
2873      YCC 613
2874      YCC 625
Name: Part_Number, Length: 2875, dtype: object

In [2]:
ua_url = ua['SPEC-Url']
ua_url

0       https://uacparts.com/Catalog/Specs?__aweconid=...
1       https://uacparts.com/Catalog/Specs?__aweconid=...
2       https://uacparts.com/Catalog/Specs?__aweconid=...
3       https://uacparts.com/Catalog/Specs?__aweconid=...
4       https://uacparts.com/Catalog/Specs?__aweconid=...
                              ...
2870    https://uacparts.com/Catalog/Specs?__aweconid=...
2871    https://uacparts.com/Catalog/Specs?__aweconid=...
2872    https://uacparts.com/Catalog/Specs?__aweconid=...
2873    https://uacparts.com/Catalog/Specs?__aweconid=...
2874    https://uacparts.com/Catalog/Specs?__aweconid=...
Name: SPEC-Url, Length: 2875, dtype: object

In [18]:
df = pd.DataFrame(columns=['Part_Number',
#                            'OE',
                           'status'])

df

Empty DataFrame
Columns: [Part_Number, status]
Index: []

In [30]:
for j in range(2389,2875):
#     print(j)

    url = ua_url[j]
    
    resp = requests.get(url).text
    soup = BeautifulSoup(resp, 'lxml')
    html = etree.HTML(str(soup))
    
    df_temp = pd.DataFrame([{'Part_Number',
                             'OE',
                             'status'}])
    
    list = html.xpath('//tr[@class="awe-row"]/td')
#     print(list[1].text)
#     print(len(list))

    df_temp = pd.DataFrame([{'Part_Number': ua_Part_Number[j],
#                  'OE':list_OE ,
                 'status': 'ok'}])
    
    list_name = [name.text for name in html.xpath('//tr[@class="awe-row"]/td[1]')]
    list_name
    list_value = [name.text for name in html.xpath('//tr[@class="awe-row"]/td[2]')]
    list_value
    
    for z in range(len(list_name)):
        name = list_name[z]
        value = list_value[z]
        df_temp[name.lower()] = value
            

    print(j,ua_Part_Number[j])
    
    print(df_temp) 
    
    df = pd.concat([df, df_temp], ignore_index=True).fillna('')
    
df

2389 CO 4883C
  Part_Number status grooves voltage clocking cylinder head  \
0    CO 4883C     ok       6      12       12            JD

  pulley diameter (mm) discharge port (mm) suction port (mm) gauge line (mm)  \
0                  125                  12                14              46

  compressor mount diode (y/ n) control valve (y/ n)
0           Direct            Y                    N
2390 CO 4885
  Part_Number status     connector type cylinder head pulley diameter (mm)  \
0     CO 4885     ok  2 wire Male Spade           MJA                  130

  compressor mount
0           Direct
2391 CO 4885C
  Part_Number status     connector type cylinder head pulley diameter (mm)  \
0    CO 4885C     ok  2 wire Male Spade           MJA                  130

  compressor mount
0           Direct
2392 CO 4890
  Part_Number status
0     CO 4890     ok
2393 CO 4893
  Part_Number status refrigerant pulley diameter (mm) gauge line (mm)  \
0     CO 4893     ok       R134A                  132              40

  compressor mount
0              Ear
2394 CO 4896C
  Part_Number status rotation refrigerant cylinder head gauge line (mm)  \
0    CO 4896C     ok       CW       R134A            JD              40

  compressor mount
0              Ear
2395 CO 4897
  Part_Number status grooves refrigerant cylinder head
0     CO 4897     ok       6       R134A           KCA
2396 CO 4910
  Part_Number status grooves refrigerant pulley diameter (mm) compressor mount
0     CO 4910     ok       6       R134A                  106           Direct
2397 CO 4910AC
  Part_Number status grooves refrigerant pulley diameter (mm) compressor mount
0   CO 4910AC     ok       6       R134A                  106           Direct
2398 CO 4911AC
  Part_Number status grooves rotation voltage pulley diameter (mm)  \
0   CO 4911AC     ok       4       CW      12                  101

  discharge port (mm) suction port (mm) gauge line (mm) diode (y/ n)  \
0                  30                34              62            N

  control valve (y/ n)
0                    N
2399 CO 4914
  Part_Number status grooves compressor type mounting distance (mm)  \
0     CO 4914     ok     PV6    Wobble Plate                   82.2

  pulley diameter (mm) discharge port (mm) suction port (mm)
0                  109                15.5              18.3
2400 CO 4914AC
  Part_Number status grooves voltage clocking mounting distance (mm)  \
0   CO 4914AC     ok       6      12       12                     82

  pulley diameter (mm) discharge port (mm) suction port (mm)
0                  109                15.5                18
2401 CO 4916AC
  Part_Number status
0   CO 4916AC     ok
2402 CO 4917AC
  Part_Number status grooves
0   CO 4917AC     ok       6
2403 CO 4918AC
  Part_Number status grooves
0   CO 4918AC     ok       7
2404 CO 4919
  Part_Number status
0     CO 4919     ok
2405 CO 4919AC
  Part_Number status grooves
0   CO 4919AC     ok       7
2406 CO 4920
  Part_Number status
0     CO 4920     ok
2407 CO 4920AC
  Part_Number status grooves voltage pulley diameter (mm) gauge line (mm)  \
0   CO 4920AC     ok       7      12                  106              54

  compressor mount diode (y/ n) control valve (y/ n)
0           Direct            N                    N
2408 CO 4928
  Part_Number status
0     CO 4928     ok
2409 CO 4933
  Part_Number status
0     CO 4933     ok
2410 CO 4934
  Part_Number status
0     CO 4934     ok
2411 CO 4939
  Part_Number status
0     CO 4939     ok
2412 CO 4940
  Part_Number status grooves pulley diameter (mm)
0     CO 4940     ok       6                  115
2413 CO 4945
  Part_Number status grooves compressor mount
0     CO 4945     ok       7           Direct
2414 CO 4969AC
  Part_Number status grooves refrigerant pulley diameter (mm) compressor mount
0   CO 4969AC     ok       6       R134A                  111           Direct
2415 CO 4975AC
  Part_Number status grooves pulley diameter (mm)
0   CO 4975AC     ok       6                  101
2416 CO 4976AC
  Part_Number status grooves pulley diameter (mm)
0   CO 4976AC     ok       6                  100
2417 CO 4979AC
  Part_Number status grooves refrigerant pulley diameter (mm) compressor mount
0   CO 4979AC     ok       7       R134A                   95           Direct
2418 CO 4987
  Part_Number status grooves pulley diameter (mm) compressor mount
0     CO 4987     ok       4                   95           Direct
2419 CO 4987AC
  Part_Number status grooves pulley diameter (mm) compressor mount
0   CO 4987AC     ok       4                   95           Direct
2420 CO 4993
  Part_Number status grooves refrigerant pulley diameter (mm) compressor mount
0     CO 4993     ok       4       R134A                  106           Direct
2421 CO 49976TK
  Part_Number status
0  CO 49976TK     ok
2422 CO 49977TK
  Part_Number status
0  CO 49977TK     ok
2423 CO 49978TK
  Part_Number status
0  CO 49978TK     ok
2424 CO 5017S
  Part_Number status grooves compressor mount
0    CO 5017S     ok       4              Ear
2425 CO 5046S
  Part_Number status compressor mount
0    CO 5046S     ok              Ear
2426 CO 5072C
  Part_Number status refrigerant gauge line (mm) compressor mount
0    CO 5072C     ok       R134A              37              Ear
2427 CO 5073
  Part_Number status refrigerant voltage gauge line (mm) compressor mount
0     CO 5073     ok       R134A      24              37              Ear
2428 CO 5073C
  Part_Number status voltage compressor mount
0    CO 5073C     ok      24              Ear
2429 CO 5074
  Part_Number status refrigerant pulley diameter (mm) compressor mount
0     CO 5074     ok       R134A                  120              Ear
2430 CO 5076
  Part_Number status refrigerant gauge line (mm) compressor mount
0     CO 5076     ok       R134A              37              Ear
2431 CO 5077O
  Part_Number status
0    CO 5077O     ok
2432 CO 5104C
  Part_Number status grooves voltage clocking pulley diameter (mm)  \
0    CO 5104C     ok       2      12       12                  125

  discharge port (mm) suction port (mm) gauge line (mm) compressor mount  \
0                  13                15              36              Ear

  control valve (y/ n)
0                    N
2433 CO 5111Y
  Part_Number status
0    CO 5111Y     ok
2434 CO 5301
  Part_Number status voltage
0     CO 5301     ok      24
2435 CO 5311Z
  Part_Number status
0    CO 5311Z     ok
2436 CO 5352
  Part_Number status voltage pulley diameter (mm)
0     CO 5352     ok      24                  132
2437 CO 5354
  Part_Number status pulley diameter (mm) compressor mount
0     CO 5354     ok                  132              Ear
2438 CO 5355
  Part_Number status voltage pulley diameter (mm) compressor mount
0     CO 5355     ok      24                  132              Ear
2439 CO 54039V
  Part_Number status grooves
0   CO 54039V     ok       6
2440 CO 5415
  Part_Number status
0     CO 5415     ok
2441 CO 5417KT
  Part_Number status pulley diameter (mm) compressor mount
0   CO 5417KT     ok                  119           Direct
2442 CO 5424C
  Part_Number status pulley diameter (mm) discharge port (mm)
0    CO 5424C     ok                  132                  16
2443 CO 5436Y
  Part_Number status
0    CO 5436Y     ok
2444 CO 55019V
  Part_Number status grooves pulley diameter (mm)
0   CO 55019V     ok       6                  120
2445 CO 55418V
  Part_Number status
0   CO 55418V     ok
2446 CO 56288V
  Part_Number status voltage pulley diameter (mm) compressor mount
0   CO 56288V     ok      24                  119           Direct
2447 CO 56419V
  Part_Number status compressor mount
0   CO 56419V     ok              Ear
2448 CO 56429V
  Part_Number status voltage hub type compressor mount
0   CO 56429V     ok      24    3 Eye              Ear
2449 CO 56466V
  Part_Number status voltage pulley diameter (mm) compressor mount
0   CO 56466V     ok      24                  119           Direct
2450 CO 5706Y
  Part_Number status
0    CO 5706Y     ok
2451 CO 5708Y
  Part_Number status compressor mount
0    CO 5708Y     ok              Ear
2452 CO 5746Y
  Part_Number status
0    CO 5746Y     ok

2453 CO 5748S
  Part_Number status
0    CO 5748S     ok
2454 CO 5790S
  Part_Number status grooves compressor mount
0    CO 5790S     ok       6              Ear
2455 CO 5791Y
  Part_Number status grooves
0    CO 5791Y     ok       6
2456 CO 58110RW
  Part_Number status compressor mount
0  CO 58110RW     ok          Tangent
2457 CO 58110ZI
  Part_Number status compressor mount
0  CO 58110ZI     ok          Tangent
2458 CO 58111C
  Part_Number status grooves
0   CO 58111C     ok       6
2459 CO 58112C
  Part_Number status grooves
0   CO 58112C     ok       1
2460 CO 58113C
  Part_Number status grooves
0   CO 58113C     ok       6
2461 CO 58114C
  Part_Number status grooves rotation voltage clocking pulley diameter (mm)  \
0   CO 58114C     ok       1       CW      12       12                  147

  discharge port (mm) suction port (mm) gauge line (mm) compressor mount  \
0                  16                16              66           Direct

  diode (y/ n) control valve (y/ n)
0            N                    N
2462 CO 6003C
  Part_Number status displacement grooves      voltage pulley diameter (mm)  \
0    CO 6003C     ok       177 cc      A1  12 No Diode                  132

  discharge port (mm) suction port (mm) gauge line (mm) compressor mount  \
0                  15                16              66          Tangent

  control valve (y/ n)
0                    N
2463 CO 6003DZ
  Part_Number status grooves
0   CO 6003DZ     ok       1
2464 CO 6005SRY
  Part_Number status
0  CO 6005SRY     ok
2465 CO 6012
  Part_Number status
0     CO 6012     ok
2466 CO 6013RY
  Part_Number status
0   CO 6013RY     ok
2467 CO 6020C
  Part_Number status grooves voltage pulley diameter (mm) discharge port (mm)  \
0    CO 6020C     ok      10      12                  119                  14

  suction port (mm) gauge line (mm) compressor mount diode (y/ n)  \
0              16.5              27             Boss            N

  control valve (y/ n)
0                    N
2468 CO 6022Y
  Part_Number status pulley diameter (mm) compressor mount
0    CO 6022Y     ok                  119              Ear
2469 CO 6023
  Part_Number status grooves voltage pulley diameter (mm)
0     CO 6023     ok       4      24                  112
2470 CO 6033Z
  Part_Number status
0    CO 6033Z     ok
2471 CO 6034
  Part_Number status voltage pulley diameter (mm)
0     CO 6034     ok      24                  130
2472 CO 6035
  Part_Number status
0     CO 6035     ok
2473 CO 6035RW
  Part_Number status
0   CO 6035RW     ok
2474 CO 6036
  Part_Number status
0     CO 6036     ok
2475 CO 6048RW
  Part_Number status
0   CO 6048RW     ok
2476 CO 6090RD
  Part_Number status
0   CO 6090RD     ok
2477 CO 6093
  Part_Number status voltage
0     CO 6093     ok      24
2478 CO 6094RW
  Part_Number status grooves pulley diameter (mm)
0   CO 6094RW     ok       6                  121
2479 CO 6095C
  Part_Number status grooves voltage pulley diameter (mm)
0    CO 6095C     ok      12      24                  126
2480 CO 6106
  Part_Number status grooves voltage
0     CO 6106     ok      10      24
2481 CO 6118RW
  Part_Number status
0   CO 6118RW     ok
2482 CO 6130DC
  Part_Number status grooves voltage pulley diameter (mm) gauge line (mm)  \
0   CO 6130DC     ok       1      12                  117              45

  compressor mount diode (y/ n) control valve (y/ n)
0              Ear            N                    N
2483 CO 6130DZ
  Part_Number status grooves gauge line (mm)
0   CO 6130DZ     ok       1              46
2484 CO 6160RW
  Part_Number status
0   CO 6160RW     ok
2485 CO 6173C
  Part_Number status grooves voltage pulley diameter (mm) discharge port (mm)  \
0    CO 6173C     ok       8      12                  149                  11

  suction port (mm) gauge line (mm) diode (y/ n)
0                15              40            Y
2486 CO 6178RW
  Part_Number status
0   CO 6178RW     ok
2487 CO 6184RW
  Part_Number status
0   CO 6184RW     ok
2488 CO 6201
  Part_Number status grooves voltage pulley diameter (mm)
0     CO 6201     ok       6      12                  125
2489 CO 6321
  Part_Number status
0     CO 6321     ok
2490 CO 6323
  Part_Number status grooves voltage cylinder head pulley diameter (mm)  \
0     CO 6323     ok       6      12            FL                  119

  gauge line (mm) compressor mount
0              47              Ear
2491 CO 6328
  Part_Number status grooves voltage cylinder head pulley diameter (mm)
0     CO 6328     ok       8      12            FL                  119
2492 CO 6328O
  Part_Number status grooves voltage cylinder head pulley diameter (mm)
0    CO 6328O     ok       8      12            FL                  119
2493 CO 6332S
  Part_Number status
0    CO 6332S     ok
2494 CO 6357
  Part_Number status
0     CO 6357     ok
2495 CO 6628
  Part_Number status grooves refrigerant pulley diameter (mm) gauge line (mm)  \
0     CO 6628     ok       7       R134A                  119              36

  compressor mount
0              Ear
2496 CO 6629
  Part_Number status grooves voltage pulley diameter (mm)
0     CO 6629     ok       7      12                  119
2497 CO 6631C
  Part_Number status grooves voltage pulley diameter (mm) discharge port (mm)  \
0    CO 6631C     ok      A2      12                  132                14.5

  suction port (mm) gauge line (mm) compressor mount control valve (y/ n)
0              14.5              24              Ear                   No
2498 CO 6632C
  Part_Number status voltage pulley diameter (mm) gauge line (mm)  \
0    CO 6632C     ok      24                  132              40

  compressor mount
0              Ear
2499 CO 6634
  Part_Number status refrigerant voltage pulley diameter (mm) gauge line (mm)  \
0     CO 6634     ok       R134A      24                  132              40

  compressor mount
0              Ear
2500 CO 6642C
  Part_Number status refrigerant pulley diameter (mm) compressor mount
0    CO 6642C     ok       R134A                  132              Ear
2501 CO 6649
  Part_Number status
0     CO 6649     ok
2502 CO 6649C
  Part_Number status grooves voltage gauge line (mm)
0    CO 6649C     ok      10      24              35
2503 CO 6651
  Part_Number status refrigerant pulley diameter (mm) gauge line (mm)  \
0     CO 6651     ok       R134A                  152              40

  compressor mount
0              Ear
2504 CO 6657C
  Part_Number status
0    CO 6657C     ok
2505 CO 6658C
  Part_Number status
0    CO 6658C     ok
2506 CO 6664
  Part_Number status voltage pulley diameter (mm) gauge line (mm)  \
0     CO 6664     ok      12                  132              40

  compressor mount
0              Ear
2507 CO 6665
  Part_Number status voltage pulley diameter (mm)
0     CO 6665     ok      24                  132
2508 CO 6667
  Part_Number status refrigerant voltage pulley diameter (mm) gauge line (mm)  \
0     CO 6667     ok       R134A      24                  132              40

  compressor mount
0              Ear
2509 CO 6673
  Part_Number status
0     CO 6673     ok
2510 CO 6674
  Part_Number status grooves refrigerant compressor mount
0     CO 6674     ok       1       R134A              Ear
2511 CO 6674Z
  Part_Number status grooves refrigerant pulley diameter (mm) compressor mount
0    CO 6674Z     ok       1       R134A                  122              Ear
2512 CO 6675
  Part_Number status grooves refrigerant pulley diameter (mm) compressor mount
0     CO 6675     ok       6       R134A                  119              Ear
2513 CO 6677
  Part_Number status refrigerant pulley diameter (mm) gauge line (mm)  \
0     CO 6677     ok       R134A                  132              40

  compressor mount
0              Ear
2514 CO 6679
  Part_Number status refrigerant voltage pulley diameter (mm) gauge line (mm)  \
0     CO 6679     ok       R134A      24                  152              40

  compressor mount
0              Ear
2515 CO 6681
  Part_Number status grooves refrigerant pulley diameter (mm) gauge line (mm)  \
0     CO 6681     ok       1       R134A                  152              34

  compressor mount
0              Ear

2516 CO 6681Y
  Part_Number status
0    CO 6681Y     ok
2517 CO 6687
  Part_Number status
0     CO 6687     ok
2518 CO 6697
  Part_Number status rotation refrigerant voltage compressor mount
0     CO 6697     ok      CCW       R134A      24              Ear
2519 CO 7058V
  Part_Number status
0    CO 7058V     ok
2520 CO 7064V
  Part_Number status
0    CO 7064V     ok
2521 CO 7076V
  Part_Number status
0    CO 7076V     ok
2522 CO 7077V
  Part_Number status voltage compressor mount
0    CO 7077V     ok      24              Ear
2523 CO 7170
  Part_Number status
0     CO 7170     ok
2524 CO 7170C
  Part_Number status grooves voltage clocking pulley diameter (mm)  \
0    CO 7170C     ok       2      12       12                  115

  discharge port (mm) suction port (mm) gauge line (mm) control valve (y/ n)
0                12.5                15              36                    N
2525 CO 7172S
  Part_Number status grooves rotation refrigerant
0    CO 7172S     ok       6       CW       R134A
2526 CO 7176
  Part_Number status
0     CO 7176     ok
2527 CO 7176C
  Part_Number status grooves pulley diameter (mm) gauge line (mm)
0    CO 7176C     ok       6                  112              23
2528 CO 7181
  Part_Number status grooves pulley diameter (mm)
0     CO 7181     ok       4                  112
2529 CO 7200RD
  Part_Number status
0   CO 7200RD     ok
2530 CO 7207Y
  Part_Number status
0    CO 7207Y     ok
2531 CO 7210Y
  Part_Number status
0    CO 7210Y     ok
2532 CO 7213Y
  Part_Number status
0    CO 7213Y     ok
2533 CO 7225S
  Part_Number status
0    CO 7225S     ok
2534 CO 7227
  Part_Number status
0     CO 7227     ok
2535 CO 7229F
  Part_Number status
0    CO 7229F     ok
2536 CO 7229Y
  Part_Number status
0    CO 7229Y     ok
2537 CO 7240S
  Part_Number status
0    CO 7240S     ok
2538 CO 7246Y
  Part_Number status
0    CO 7246Y     ok
2539 CO 7303C
  Part_Number status
0    CO 7303C     ok
2540 CO 7304C
  Part_Number status grooves refrigerant pulley diameter (mm) gauge line (mm)  \
0    CO 7304C     ok       6       R134A                  119              38

  compressor mount
0              Ear
2541 CO 7312C
  Part_Number status grooves voltage clocking pulley diameter (mm)  \
0    CO 7312C     ok       2      12       12                  125

  discharge port (mm) suction port (mm) gauge line (mm) compressor mount  \
0              3/4-16            7/8-14              38              Ear

  control valve (y/ n)
0                    N
2542 CO 7320C
  Part_Number status refrigerant pulley diameter (mm) gauge line (mm)  \
0    CO 7320C     ok       R134A                  120              44

  compressor mount
0           Direct
2543 CO 7321
  Part_Number status refrigerant gauge line (mm) compressor mount
0     CO 7321     ok       R134A              50           Direct
2544 CO 7351
  Part_Number status grooves rotation voltage pulley diameter (mm)  \
0     CO 7351     ok       1       CW      24                  146

  compressor mount
0           Direct
2545 CO 7360C
  Part_Number status voltage
0    CO 7360C     ok      24
2546 CO 7409C
  Part_Number status grooves voltage compressor type clocking  \
0    CO 7409C     ok      A2      12    Wobble Plate       12

  pulley diameter (mm) discharge port (mm) suction port (mm) gauge line (mm)  \
0                  125              3/4-16            7/8-14              40

  control valve (y/ n)
0                   No
2547 CO 7416C
  Part_Number status grooves pulley diameter (mm) gauge line (mm)
0    CO 7416C     ok       6                  119              62
2548 CO 7425RY
  Part_Number status
0   CO 7425RY     ok
2549 CO 7429RZ
  Part_Number status
0   CO 7429RZ     ok
2550 CO 7444Y
  Part_Number status
0    CO 7444Y     ok
2551 CO 7445S
  Part_Number status
0    CO 7445S     ok
2552 CO 7445Y
  Part_Number status
0    CO 7445Y     ok
2553 CO 7463Y
  Part_Number status
0    CO 7463Y     ok
2554 CO 7466RD
  Part_Number status
0   CO 7466RD     ok
2555 CO 7470S
  Part_Number status
0    CO 7470S     ok
2556 CO 7499Y
  Part_Number status refrigerant gauge line (mm) compressor mount
0    CO 7499Y     ok       R134A              40              Ear
2557 CO 7534Y
  Part_Number status
0    CO 7534Y     ok
2558 CO 7557RY
  Part_Number status
0   CO 7557RY     ok
2559 CO 7641S
  Part_Number status pulley diameter (mm)
0    CO 7641S     ok                  132
2560 CO 7681
  Part_Number status
0     CO 7681     ok
2561 CO 7701C
  Part_Number status grooves voltage clocking pulley diameter (mm)  \
0    CO 7701C     ok       6      12       12                  119

  gauge line (mm) compressor mount control valve (y/ n)
0              55          Tangent                    N
2562 CO 7702C
  Part_Number status grooves voltage pulley diameter (mm) discharge port (mm)  \
0    CO 7702C     ok       8      12                  118          3/4-16 STD

  suction port (mm) gauge line (mm) diode (y/ n) control valve (y/ n)
0          7/8 - 14              57            N                    N
2563 CO 7712C
  Part_Number status grooves voltage compressor type clocking  \
0    CO 7712C     ok       6      12    Wobble Plate       12

  pulley diameter (mm) discharge port (mm) suction port (mm) gauge line (mm)  \
0                  124                1-14              1-14              54

  compressor mount control valve (y/ n)
0          Tangent                   No
2564 CO 7715Y
  Part_Number status
0    CO 7715Y     ok
2565 CO 7730S
  Part_Number status
0    CO 7730S     ok
2566 CO 7803C
  Part_Number status refrigerant gauge line (mm) compressor mount
0    CO 7803C     ok       R134A              40              Ear
2567 CO 7819C
  Part_Number status grooves voltage pulley diameter (mm) gauge line (mm)  \
0    CO 7819C     ok       2      12                  124              24

  compressor mount diode (y/ n) control valve (y/ n)
0              Ear            N                    N
2568 CO 7820
  Part_Number status grooves pulley diameter (mm) belt width (mm)  \
0     CO 7820     ok       6                  120              22

  compressor mount
0              Ear
2569 CO 7822C
  Part_Number status refrigerant pulley diameter (mm) compressor mount
0    CO 7822C     ok       R134A                  119              Ear
2570 CO 7844S
  Part_Number status
0    CO 7844S     ok
2571 CO 7846
  Part_Number status grooves refrigerant pulley diameter (mm) compressor mount
0     CO 7846     ok       6       R134A                  119              Ear
2572 CO 7865S
  Part_Number status
0    CO 7865S     ok
2573 CO 7882C
  Part_Number status
0    CO 7882C     ok
2574 CO 7935
  Part_Number status grooves clocking compressor mount
0     CO 7935     ok       6        3              Ear
2575 CO 7935C
  Part_Number status grooves clocking compressor mount
0    CO 7935C     ok       6        3              Ear
2576 CO 7972S
  Part_Number status
0    CO 7972S     ok
2577 CO 7996Y
  Part_Number status
0    CO 7996Y     ok
2578 CO 8017
  Part_Number status
0     CO 8017     ok
2579 CO 8023C
  Part_Number status grooves voltage pulley diameter (mm) discharge port (mm)  \
0    CO 8023C     ok       2      12                  132                  12

  suction port (mm) gauge line (mm)
0              14.5              24
2580 CO 8027C
  Part_Number status pulley diameter (mm)
0    CO 8027C     ok                  119
2581 CO 8028C
  Part_Number status pulley diameter (mm)
0    CO 8028C     ok                  119
2582 CO 8034
  Part_Number status
0     CO 8034     ok
2583 CO 8044C
  Part_Number status voltage pulley diameter (mm) gauge line (mm)
0    CO 8044C     ok      24                  132              44
2584 CO 8045
  Part_Number status voltage pulley diameter (mm) gauge line (mm)
0     CO 8045     ok      24                  132              24
2585 CO 8045C
  Part_Number status voltage pulley diameter (mm) gauge line (mm)
0    CO 8045C     ok      24                  132              24
2586 CO 8051Y
  Part_Number status
0    CO 8051Y     ok
2587 CO 8052C
  Part_Number status grooves refrigerant pulley diameter (mm) gauge line (mm)  \
0    CO 8052C     ok       6       R134A                  133              55

  compressor mount
0           Direct

2588 CO 8053S
  Part_Number status
0    CO 8053S     ok
2589 CO 8061C
  Part_Number status grooves voltage pulley diameter (mm) gauge line (mm)  \
0    CO 8061C     ok       2      24                  132              40

  compressor mount
0              Ear
2590 CO 8067
  Part_Number status voltage pulley diameter (mm)
0     CO 8067     ok      24                  119
2591 CO 8067C
  Part_Number status voltage pulley diameter (mm)
0    CO 8067C     ok      24                  119
2592 CO 8069
  Part_Number status refrigerant voltage pulley diameter (mm) compressor mount
0     CO 8069     ok       R134A      24                  132              Ear
2593 CO 8085C
  Part_Number status voltage pulley diameter (mm) compressor mount
0    CO 8085C     ok      24                  119              Ear
2594 CO 8088
  Part_Number status pulley diameter (mm) compressor mount
0     CO 8088     ok                  140              Ear
2595 CO 8088C
  Part_Number status pulley diameter (mm) compressor mount
0    CO 8088C     ok                  140              Ear
2596 CO 8091
  Part_Number status
0     CO 8091     ok
2597 CO 8112O
  Part_Number status grooves voltage cylinder head pulley diameter (mm)  \
0    CO 8112O     ok       8      24            WZ                  132

  gauge line (mm) compressor mount
0              44           Direct
2598 CO 8112OI
  Part_Number status grooves voltage cylinder head pulley diameter (mm)  \
0   CO 8112OI     ok       8      24            WZ                  132

  gauge line (mm) compressor mount
0              44           Direct
2599 CO 8112S
  Part_Number status rotation voltage pulley diameter (mm) compressor mount
0    CO 8112S     ok       CW      24                  132           Direct
2600 CO 8117C
  Part_Number status grooves voltage pulley diameter (mm) compressor mount  \
0    CO 8117C     ok       8      24                  119              Ear

  control valve (y/ n)
0                    N
2601 CO 8139S
  Part_Number status
0    CO 8139S     ok
2602 CO 8144
  Part_Number status voltage pulley diameter (mm)
0     CO 8144     ok      12                  119
2603 CO 8144-24Y
   Part_Number status voltage
0  CO 8144-24Y     ok      24
2604 CO 8144C
  Part_Number status voltage pulley diameter (mm)
0    CO 8144C     ok      24                  119
2605 CO 8147C
  Part_Number status grooves pulley diameter (mm)
0    CO 8147C     ok       4                  112
2606 CO 8148C
  Part_Number status grooves voltage pulley diameter (mm)  \
0    CO 8148C     ok       4      12                  112

  suction port diameter (mm)
0                         17
2607 CO 8151S
  Part_Number status
0    CO 8151S     ok
2608 CO 8152Z
  Part_Number status
0    CO 8152Z     ok
2609 CO 8173
  Part_Number status grooves rotation pulley diameter (mm)
0     CO 8173     ok       4       CW                  119
2610 CO 8174
  Part_Number status grooves pulley diameter (mm) gauge line (mm)
0     CO 8174     ok       1                  158              50
2611 CO 8174C
  Part_Number status grooves pulley diameter (mm) gauge line (mm)
0    CO 8174C     ok       1                  158              50
2612 CO 8182
  Part_Number status grooves voltage pulley diameter (mm)
0     CO 8182     ok       1      24                  132
2613 CO 8202
  Part_Number status voltage pulley diameter (mm)
0     CO 8202     ok      24                  120
2614 CO 8203C
  Part_Number status rotation clocking pulley diameter (mm)
0    CO 8203C     ok       CW       10                  119
2615 CO 8215
  Part_Number status pulley diameter (mm)
0     CO 8215     ok                  120
2616 CO 8228
  Part_Number status
0     CO 8228     ok
2617 CO 8231C
  Part_Number status grooves voltage pulley diameter (mm)
0    CO 8231C     ok       7      24                  140
2618 CO 8242C
  Part_Number status voltage
0    CO 8242C     ok      24
2619 CO 8243
  Part_Number status
0     CO 8243     ok
2620 CO 8243C
  Part_Number status
0    CO 8243C     ok
2621 CO 8244C
  Part_Number status grooves pulley diameter (mm) suction port diameter (mm)  \
0    CO 8244C     ok       6                  119                         16

  discharge port (mm)
0                  16
2622 CO 8252
  Part_Number status grooves voltage pulley diameter (mm) compressor mount
0     CO 8252     ok       2      24                  132              Ear
2623 CO 8252C
  Part_Number status grooves voltage pulley diameter (mm) gauge line (mm)  \
0    CO 8252C     ok       2      24                  132              40

  compressor mount diode (y/ n)
0              Ear            N
2624 CO 8253
  Part_Number status grooves voltage pulley diameter (mm) compressor mount
0     CO 8253     ok       2      12                  132              Ear
2625 CO 8253C
  Part_Number status grooves voltage pulley diameter (mm) discharge port (mm)  \
0    CO 8253C     ok       2      12                  132                  14

  suction port (mm) gauge line (mm) compressor mount diode (y/ n)
0                16              40              Ear            N
2626 CO 8256
  Part_Number status
0     CO 8256     ok
2627 CO 8263
  Part_Number status grooves voltage pulley diameter (mm)
0     CO 8263     ok      10      24                  120
2628 CO 8279
  Part_Number status grooves pulley diameter (mm)
0     CO 8279     ok       4                  112
2629 CO 8290
  Part_Number status grooves voltage pulley diameter (mm)
0     CO 8290     ok       8      24                  121
2630 CO 8295
  Part_Number status grooves voltage mounting distance (mm)  \
0     CO 8295     ok      10      24                     68

  pulley diameter (mm)
0                  119
2631 CO 8295C
  Part_Number status grooves voltage clocking pulley diameter (mm)  \
0    CO 8295C     ok      10      24       12                  119

  discharge port (mm) suction port (mm) gauge line (mm) diode (y/ n)  \
0                  12                18              48            N

  control valve (y/ n)
0                    N
2632 CO 8296O
  Part_Number status grooves voltage cylinder head pulley diameter (mm)  \
0    CO 8296O     ok       2      24            GV                  132

  compressor mount
0              Ear
2633 CO 8298
  Part_Number status grooves voltage pulley diameter (mm)
0     CO 8298     ok       4      24                  110
2634 CO 8353
  Part_Number status
0     CO 8353     ok
2635 CO 8387Y
  Part_Number status pulley diameter (mm) gauge line (mm) compressor mount
0    CO 8387Y     ok                  152              40              Ear
2636 CO 8399Y
  Part_Number status
0    CO 8399Y     ok
2637 CO 8628
  Part_Number status
0     CO 8628     ok
2638 CO 8628C
  Part_Number status grooves pulley diameter (mm) suction port diameter (mm)  \
0    CO 8628C     ok       6                  120                         17

  compressor mount
0           Direct
2639 CO 8702C
  Part_Number status pulley diameter (mm) suction port diameter (mm)  \
0    CO 8702C     ok                  120                         18

  control valve (y/ n)
0                    N
2640 CO 8925
  Part_Number status grooves voltage pulley diameter (mm) compressor mount
0     CO 8925     ok       1      24                  120           Direct
2641 CO 8926G
  Part_Number status grooves voltage cylinder head pulley diameter (mm)  \
0    CO 8926G     ok       1      24            WM                  127

  compressor mount
0           Direct
2642 CO 8926Z
  Part_Number status
0    CO 8926Z     ok
2643 CO 8948
  Part_Number status grooves voltage
0     CO 8948     ok       1      24
2644 CO 9016Y
  Part_Number status
0    CO 9016Y     ok
2645 CO 9026S
  Part_Number status refrigerant pulley diameter (mm) gauge line (mm)  \
0    CO 9026S     ok       R134A                  132              40

  compressor mount
0              Ear
2646 CO 9056S
  Part_Number status
0    CO 9056S     ok
2647 CO 9096S
  Part_Number status gauge line (mm) compressor mount
0    CO 9096S     ok              37              Ear
2648 CO 9103DC
  Part_Number status grooves voltage pulley diameter (mm) discharge port (mm)  \
0   CO 9103DC     ok       2      12                  132              3/4-16

  suction port (mm) compressor mount
0            7/8-14              Ear

2649 CO 9114DC
  Part_Number status pulley diameter (mm) compressor mount
0   CO 9114DC     ok                  132              Ear
2650 CO 9120C
  Part_Number status
0    CO 9120C     ok
2651 CO 9140
  Part_Number status
0     CO 9140     ok
2652 CO 9149Z
  Part_Number status
0    CO 9149Z     ok
2653 CO 9173S
  Part_Number status
0    CO 9173S     ok
2654 CO 9263S
  Part_Number status
0    CO 9263S     ok
2655 CO 9283S
  Part_Number status
0    CO 9283S     ok
2656 CO 9285C
  Part_Number status refrigerant cylinder head pulley diameter (mm)  \
0    CO 9285C     ok         R12            FG                  132

  gauge line (mm) compressor mount
0              40              Ear
2657 CO 9288Y
  Part_Number status
0    CO 9288Y     ok
2658 CO 9513Y
  Part_Number status grooves
0    CO 9513Y     ok      10
2659 CO 9514S
  Part_Number status
0    CO 9514S     ok
2660 CO 9537C
  Part_Number status grooves pulley diameter (mm) compressor mount  \
0    CO 9537C     ok       7                  119              Ear

  switch (y/ n)
0           Yes
2661 CO 9563S
  Part_Number status pulley diameter (mm) gauge line (mm) compressor mount
0    CO 9563S     ok                  132              40              Ear
2662 CO 9580Y
  Part_Number status
0    CO 9580Y     ok
2663 CO 9652Y
  Part_Number status
0    CO 9652Y     ok
2664 CO 9663S
  Part_Number status
0    CO 9663S     ok
2665 CO 9669Y
  Part_Number status
0    CO 9669Y     ok
2666 CO 9689S
  Part_Number status
0    CO 9689S     ok
2667 CO 9774Z
  Part_Number status
0    CO 9774Z     ok
2668 CO 9775C
  Part_Number status grooves voltage pulley diameter (mm)  \
0    CO 9775C     ok       6      12                  110

  suction port diameter (mm) discharge port (mm) gauge line (mm) diode (y/ n)  \
0                         18                  16              71            Y

  control valve (y/ n)
0                    N
2669 CO 9776C
  Part_Number status
0    CO 9776C     ok
2670 CO 9777C
  Part_Number status grooves compressor type mounting distance (mm)  \
0    CO 9777C     ok       6          Piston                     62

  pulley diameter (mm) discharge port (mm) suction port (mm) gauge line (mm)  \
0                  110                  15                18              55

  compressor mount control valve (y/ n)
0           Direct                  Yes
2671 CO 9779C
  Part_Number status
0    CO 9779C     ok
2672 CO 9779Z
  Part_Number status
0    CO 9779Z     ok
2673 CO 9781C
  Part_Number status grooves rotation      voltage pulley diameter (mm)  \
0    CO 9781C     ok       6       CW  12 No Diode                  107

  discharge port (mm) suction port (mm) gauge line (mm) compressor mount  \
0                  18                23              73          Tangent

  control valve (y/ n)
0                    Y
2674 CRY 5181968AB
     Part_Number status
0  CRY 5181968AB     ok
2675 CRY 5264745
   Part_Number status
0  CRY 5264745     ok
2676 CRY 53001438
    Part_Number status
0  CRY 53001438     ok
2677 CRY 55036679
    Part_Number status
0  CRY 55036679     ok
2678 CRY 68289890AB
      Part_Number status
0  CRY 68289890AB     ok
2679 CRY 68376684AE
      Part_Number status
0  CRY 68376684AE     ok
2680 CRY 68439253AA
      Part_Number status
0  CRY 68439253AA     ok
2681 CRY 68481137AB
      Part_Number status
0  CRY 68481137AB     ok
2682 CU 1450-A2029
     Part_Number status
0  CU 1450-A2029     ok
2683 CU 6759-3081
    Part_Number status
0  CU 6759-3081     ok
2684 FD JX6Z19703M
     Part_Number status
0  FD JX6Z19703M     ok
2685 FD LX6Z19703U
     Part_Number status
0  FD LX6Z19703U     ok
2686 FD ML3Z19703G
     Part_Number status
0  FD ML3Z19703G     ok
2687 FD NL1Z19703A
     Part_Number status
0  FD NL1Z19703A     ok
2688 FIA 68439272AA
      Part_Number status
0  FIA 68439272AA     ok
2689 GM 12567478
   Part_Number status
0  GM 12567478     ok
2690 GM 12569286
   Part_Number status
0  GM 12569286     ok
2691 GM 13271263
   Part_Number status
0  GM 13271263     ok
2692 GM 39176466
   Part_Number status
0  GM 39176466     ok
2693 GM 42483362
   Part_Number status
0  GM 42483362     ok
2694 GM 42502600
   Part_Number status
0  GM 42502600     ok
2695 GM 42733186
   Part_Number status
0  GM 42733186     ok
2696 GM 42733191
   Part_Number status
0  GM 42733191     ok
2697 GM 84021290
   Part_Number status
0  GM 84021290     ok
2698 GM 84208256
   Part_Number status
0  GM 84208256     ok
2699 GM 84334591
   Part_Number status grooves
0  GM 84334591     ok       4
2700 GM 84338629
   Part_Number status
0  GM 84338629     ok
2701 GM 84441372
   Part_Number status
0  GM 84441372     ok
2702 GM 84488491
   Part_Number status
0  GM 84488491     ok
2703 GM 84516974
   Part_Number status
0  GM 84516974     ok
2704 GM 84610777
   Part_Number status
0  GM 84610777     ok
2705 GM 84650874
   Part_Number status
0  GM 84650874     ok
2706 GM 84664206
   Part_Number status
0  GM 84664206     ok
2707 GM 84664213
   Part_Number status
0  GM 84664213     ok
2708 GM 84666664
   Part_Number status
0  GM 84666664     ok
2709 GM 84726380
   Part_Number status
0  GM 84726380     ok
2710 GM 84802769
   Part_Number status
0  GM 84802769     ok
2711 GM 84849910
   Part_Number status
0  GM 84849910     ok
2712 GM 84856232
   Part_Number status
0  GM 84856232     ok
2713 GM 92276906
   Part_Number status
0  GM 92276906     ok
2714 GM 92279283
   Part_Number status
0  GM 92279283     ok
2715 GM 97386417
   Part_Number status
0  GM 97386417     ok
2716 HO 388005RDA01
      Part_Number status
0  HO 388005RDA01     ok
2717 HO 388005WJA02
      Part_Number status
0  HO 388005WJA02     ok
2718 HO 388006C2A02
      Part_Number status
0  HO 388006C2A02     ok
2719 HO 388006L2A01
      Part_Number status
0  HO 388006L2A01     ok
2720 HO 3881051MA22
      Part_Number status
0  HO 3881051MA22     ok
2721 HO 3881058RG01
      Part_Number status
0  HO 3881058RG01     ok
2722 HO 388105WMA11
      Part_Number status
0  HO 388105WMA11     ok
2723 HO 3881064AA02
      Part_Number status
0  HO 3881064AA02     ok
2724 HO 3881064SA01
      Part_Number status
0  HO 3881064SA01     ok
2725 HO 388106A0A01
      Part_Number status
0  HO 388106A0A01     ok
2726 HY 977013T500
     Part_Number status
0  HY 977013T500     ok
2727 HY 97701A7200
     Part_Number status
0  HY 97701A7200     ok
2728 HY 97701A7300
     Part_Number status
0  HY 97701A7300     ok
2729 HY 97701AA100
     Part_Number status
0  HY 97701AA100     ok
2730 HY 97701AA250
     Part_Number status
0  HY 97701AA250     ok
2731 HY 97701B1200
     Part_Number status
0  HY 97701B1200     ok
2732 HY 97701B1400
     Part_Number status
0  HY 97701B1400     ok
2733 HY 97701C2500
     Part_Number status
0  HY 97701C2500     ok
2734 HY 97701D2400
     Part_Number status
0  HY 97701D2400     ok
2735 HY 97701D2550
     Part_Number status
0  HY 97701D2550     ok
2736 HY 97701D2650
     Part_Number status
0  HY 97701D2650     ok
2737 HY 97701D3750
     Part_Number status
0  HY 97701D3750     ok
2738 HY 97701E6100
     Part_Number status
0  HY 97701E6100     ok
2739 HY 97701F3300
     Part_Number status
0  HY 97701F3300     ok
2740 HY 97701F6100
     Part_Number status
0  HY 97701F6100     ok
2741 HY 97701G3000
     Part_Number status
0  HY 97701G3000     ok
2742 HY 97701G3100
     Part_Number status
0  HY 97701G3100     ok
2743 HY 97701G3300
     Part_Number status
0  HY 97701G3300     ok
2744 HY 97701G4300
     Part_Number status
0  HY 97701G4300     ok
2745 HY 97701J3090
     Part_Number status
0  HY 97701J3090     ok
2746 HY 97701J3490
     Part_Number status
0  HY 97701J3490     ok
2747 HY 97701J6100
     Part_Number status
0  HY 97701J6100     ok
2748 HY 97701K2150
     Part_Number status
0  HY 97701K2150     ok
2749 HY 97701K4000
     Part_Number status
0  HY 97701K4000     ok
2750 HY 97701K9000
     Part_Number status
0  HY 97701K9000     ok
2751 HY 97701L0000
     Part_Number status
0  HY 97701L0000     ok
2752 HY 97701L1800
     Part_Number status
0  HY 97701L1800     ok
2753 HY 97701L2350
     Part_Number status
0  HY 97701L2350     ok
2754 HY 97701M5000
     Part_Number status
0  HY 97701M5000     ok
2755 HY 97701N9600
     Part_Number status
0  HY 97701N9600     ok

2756 HY 97701P2500
     Part_Number status
0  HY 97701P2500     ok
2757 HY 97701S2700
     Part_Number status
0  HY 97701S2700     ok
2758 HY 97701S8500
     Part_Number status
0  HY 97701S8500     ok
2759 HY 97729P0000
     Part_Number status
0  HY 97729P0000     ok
2760 HY 97729P4000
     Part_Number status
0  HY 97729P4000     ok
2761 HY 977E1L5000
     Part_Number status
0  HY 977E1L5000     ok
2762 IN 926005NA2A
     Part_Number status
0  IN 926005NA2A     ok
2763 IN 926009NC0B
     Part_Number status
0  IN 926009NC0B     ok
2764 IN 926101CB0A
     Part_Number status
0  IN 926101CB0A     ok
2765 JD 19H1930
  Part_Number status
0  JD 19H1930     ok
2766 JD 19M8007
  Part_Number status
0  JD 19M8007     ok
2767 JD 57M7267
  Part_Number status
0  JD 57M7267     ok
2768 JD AL78780
  Part_Number status
0  JD AL78780     ok
2769 JD R71196
  Part_Number status
0   JD R71196     ok
2770 JD RE69715
  Part_Number status
0  JD RE69715     ok
2771 KIA 977013T300
      Part_Number status
0  KIA 977013T300     ok
2772 KIA 97701A7500
      Part_Number status
0  KIA 97701A7500     ok
2773 KIA 97701C6900
      Part_Number status
0  KIA 97701C6900     ok
2774 KIA 97701C6910
      Part_Number status
0  KIA 97701C6910     ok
2775 KIA 97701C6960
      Part_Number status
0  KIA 97701C6960     ok
2776 KIA 97701D3950
      Part_Number status
0  KIA 97701D3950     ok
2777 KIA 97701D5600
      Part_Number status
0  KIA 97701D5600     ok
2778 KIA 97701F6600
      Part_Number status
0  KIA 97701F6600     ok
2779 KIA 97701G4100
      Part_Number status
0  KIA 97701G4100     ok
2780 KIA 97701J6000
      Part_Number status
0  KIA 97701J6000     ok
2781 KIA 97701K0000
      Part_Number status
0  KIA 97701K0000     ok
2782 KIA 97701M6550
      Part_Number status
0  KIA 97701M6550     ok
2783 KIA 97701M7100
      Part_Number status
0  KIA 97701M7100     ok
2784 KIA 97701M7150
      Part_Number status
0  KIA 97701M7150     ok
2785 KIA 97729K4000
      Part_Number status
0  KIA 97729K4000     ok
2786 LEX 8831024191
      Part_Number status
0  LEX 8831024191     ok
2787 LEX 8846060560
      Part_Number status
0  LEX 8846060560     ok
2788 LR LR112585
   Part_Number status
0  LR LR112585     ok
2789 MB 7813A737
   Part_Number status
0  MB 7813A737     ok
2790 MB 7813A784
   Part_Number status
0  MB 7813A784     ok
2791 MB 7813A801
   Part_Number status
0  MB 7813A801     ok
2792 MB 7813A815
   Part_Number status
0  MB 7813A815     ok
2793 MB 7813A873
   Part_Number status
0  MB 7813A873     ok
2794 MB 7813A969
   Part_Number status
0  MB 7813A969     ok
2795 MB 7813A972
   Part_Number status
0  MB 7813A972     ok
2796 MB 7813A977
   Part_Number status
0  MB 7813A977     ok
2797 MB 7813A991
   Part_Number status
0  MB 7813A991     ok
2798 MB 7813B071
   Part_Number status
0  MB 7813B071     ok
2799 ME 0008303601
     Part_Number status
0  ME 0008303601     ok
2800 ME 0008304202
     Part_Number status
0  ME 0008304202     ok
2801 ME 000830450280
       Part_Number status
0  ME 000830450280     ok
2802 ME 000830470280
       Part_Number status
0  ME 000830470280     ok
2803 ME 000830510080
       Part_Number status
0  ME 000830510080     ok
2804 ME 0008305302
     Part_Number status
0  ME 0008305302     ok
2805 ME 000830760080
       Part_Number status
0  ME 000830760080     ok
2806 ME 003230511180
       Part_Number status
0  ME 003230511180     ok
2807 ME 003230741180
       Part_Number status
0  ME 003230741180     ok
2808 ME 004230231180
       Part_Number status
0  ME 004230231180     ok
2809 ME 1161310001
     Part_Number status
0  ME 1161310001     ok
2810 ME A0022307211
      Part_Number status
0  ME A0022307211     ok
2811 MZ BDGF61450
    Part_Number status
0  MZ BDGF61450     ok
2812 MZ BHAA61450
    Part_Number status
0  MZ BHAA61450     ok
2813 MZ KB8E61450
    Part_Number status
0  MZ KB8E61450     ok
2814 NI 926004AY0B
     Part_Number status
0  NI 926004AY0B     ok
2815 NI 926004BA1A
     Part_Number status
0  NI 926004BA1A     ok
2816 NI 926006GK0A
     Part_Number status
0  NI 926006GK0A     ok
2817 NI 926006MA0A
     Part_Number status
0  NI 926006MA0A     ok
2818 NI 926006SA0C
     Part_Number status
0  NI 926006SA0C     ok
2819 NI 926009BT0B
     Part_Number status
0  NI 926009BT0B     ok
2820 NI 926009BV0A
     Part_Number status
0  NI 926009BV0A     ok
2821 NI 926009FV3B
     Part_Number status
0  NI 926009FV3B     ok
2822 NI 926009FV5A
     Part_Number status
0  NI 926009FV5A     ok
2823 NI 926009SM0A
     Part_Number status
0  NI 926009SM0A     ok
2824 NI 92600JF01B
     Part_Number status
0  NI 92600JF01B     ok
2825 SU 73111AL020
     Part_Number status
0  SU 73111AL020     ok
2826 SU 73111AN01A
     Part_Number status
0  SU 73111AN01A     ok
2827 SU 73111FL140
     Part_Number status
0  SU 73111FL140     ok
2828 SU 73111FL14A
     Part_Number status
0  SU 73111FL14A     ok
2829 SU 73111FL150
     Part_Number status
0  SU 73111FL150     ok
2830 TS 106336900H
     Part_Number status
0  TS 106336900H     ok
2831 TS 108819800P
     Part_Number status
0  TS 108819800P     ok
2832 TY 8831008083
     Part_Number status
0  TY 8831008083     ok
2833 TY 8831033330
     Part_Number status
0  TY 8831033330     ok
2834 TY 8831035A60
     Part_Number status
0  TY 8831035A60     ok
2835 TY 8831052480
     Part_Number status
0  TY 8831052480     ok
2836 TY 88310F4050
     Part_Number status
0  TY 88310F4050     ok
2837 TY 88310WAA02
     Part_Number status
0  TY 88310WAA02     ok
2838 TY 883200E130
     Part_Number status
0  TY 883200E130     ok
2839 TY 883201224084
       Part_Number status
0  TY 883201224084     ok
2840 TY 8832060680
     Part_Number status
0  TY 8832060680     ok
2841 TY 8832060B80
     Part_Number status
0  TY 8832060B80     ok
2842 TY 8837033020
     Part_Number status
0  TY 8837033020     ok
2843 TY 8837042040
     Part_Number status
0  TY 8837042040     ok
2844 TY 8837048170
     Part_Number status
0  TY 8837048170     ok
2845 TY 8837062010
     Part_Number status
0  TY 8837062010     ok
2846 TY 8837062021
     Part_Number status
0  TY 8837062021     ok
2847 TY 8843108010
     Part_Number status
0  TY 8843108010     ok
2848 VO 36010353
   Part_Number status
0  VO 36010353     ok
2849 VW 5QE816803G
     Part_Number status
0  VW 5QE816803G     ok
2850 YC 153
  Part_Number status
0      YC 153     ok
2851 YC 2479
  Part_Number status
0     YC 2479     ok
2852 YC 2552
  Part_Number status grooves
0     YC 2552     ok       6
2853 YC 2560
  Part_Number status
0     YC 2560     ok
2854 YCC 396
  Part_Number status
0     YCC 396     ok
2855 YCC 436
  Part_Number status
0     YCC 436     ok
2856 YCC 445
  Part_Number status
0     YCC 445     ok
2857 YCC 474
  Part_Number status
0     YCC 474     ok
2858 YCC 478
  Part_Number status
0     YCC 478     ok
2859 YCC 516
  Part_Number status
0     YCC 516     ok
2860 YCC 526
  Part_Number status grooves voltage clocking pulley diameter (mm)  \
0     YCC 526     ok       4      12       12                  110

  discharge port (mm) suction port (mm) gauge line (mm) compressor mount  \
0                  18                23              60          Tangent

  diode (y/ n) control valve (y/ n)
0            Y                    Y
2861 YCC 527
  Part_Number status
0     YCC 527     ok
2862 YCC 564
  Part_Number status
0     YCC 564     ok
2863 YCC 566
  Part_Number status
0     YCC 566     ok
2864 YCC 576
  Part_Number status
0     YCC 576     ok
2865 YCC 581
  Part_Number status
0     YCC 581     ok
2866 YCC 586
  Part_Number status
0     YCC 586     ok
2867 YCC 590
  Part_Number status
0     YCC 590     ok
2868 YCC 598
  Part_Number status
0     YCC 598     ok
2869 YCC 599
  Part_Number status
0     YCC 599     ok
2870 YCC 603
  Part_Number status
0     YCC 603     ok
2871 YCC 604
  Part_Number status
0     YCC 604     ok
2872 YCC 607
  Part_Number status
0     YCC 607     ok
2873 YCC 613
  Part_Number status
0     YCC 613     ok
2874 YCC 625
  Part_Number status
0     YCC 625     ok

,Part_Number,status,grooves,pulley diameter (mm),rotation,voltage,clocking,discharge port (mm),suction port (mm),gauge line (mm),...,displacement,service port size,cylinder head,prv (y/ n),diameter (mm),thread size,belt type,terminal qty,quantity,hose ports
0,15 20061,ok,,,,,,,,,...,,,,,,,,,,
1,15 20062,ok,,,,,,,,,...,,,,,,,,,,
2,15 20162,ok,,,,,,,,,...,,,,,,,,,,
3,15 20228Z,ok,,,,,,,,,...,,,,,,,,,,
4,15 20234Z,ok,,,,,,,,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2871,YCC 603,ok,,,,,,,,,...,,,,,,,,,,
2872,YCC 604,ok,,,,,,,,,...,,,,,,,,,,
2873,YCC 607,ok,,,,,,,,,...,,,,,,,,,,
2874,YCC 613,ok,,,,,,,,,...,,,,,,,,,,
2875,YCC 625,ok,,,,,,,,,...,,,,,,,,,,

In [28]:
df

,Part_Number,status,grooves,pulley diameter (mm),rotation,voltage,clocking,discharge port (mm),suction port (mm),gauge line (mm),...,displacement,service port size,cylinder head,prv (y/ n),diameter (mm),thread size,belt type,terminal qty,quantity,hose ports
0,15 20061,ok,,,,,,,,,...,,,,,,,,,,
1,15 20062,ok,,,,,,,,,...,,,,,,,,,,
2,15 20162,ok,,,,,,,,,...,,,,,,,,,,
3,15 20228Z,ok,,,,,,,,,...,,,,,,,,,,
4,15 20234Z,ok,,,,,,,,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2385,CO 4875,ok,1,138,,,,,,,...,,,,,,,,,,
2386,CO 4875C,ok,1,138,,,,,,,...,,,,,,,,,,
2387,CO 4877,ok,1,138,,24,,,,,...,,,,,,,,,,
2388,CO 4877C,ok,1,138,,24,,,,,...,,,,,,,,,,
2389,CO 4881C,ok,,152,,24,,,,40,...,,,,,,,,,,

In [31]:
df.to_excel(r'C:\Users\YangTeng\Desktop\UAC-Compressor Assembly\spec-(2874).xlsx', index=False)