In [1]:
import os
import pandas as pd
import requests
import re 
from bs4 import BeautifulSoup
from lxml import etree
import json
from selenium.webdriver import ChromeOptions

# proxies = {'http': 'http://t19182064816778:9s5s2nv0@f290.kdltps.com:15818',
#            'https': 'http://t19182064816778:9s5s2nv0@f290.kdltps.com:15818'}

In [2]:
ua = pd.read_excel(r'C:\Users\YangTeng\Desktop\ua-L.xlsx', header=0)
# ua_no = ua['No']
# ua_no
ua_OE = ua['OE'] 
ua_OE

0        2020067C
1      2020122GLC
2      2020237GLC
3      2020247GLC
4      2020110GLC
          ...
510       208174C
511       208203C
512        208243
513       208244C
514      209114DC
Name: OE, Length: 515, dtype: object

In [24]:
df = pd.DataFrame(columns=['OE',
                           'fourseaon_OE',
                           'status'])

df

Empty DataFrame
Columns: [OE, fourseaon_OE, status]
Index: []

In [25]:
for j in ua_OE[115:200]:
#     print(j)
    url='https://uacparts.com/Catalog/CrossReference?__aweconid=CRP6&part=CO%'+str(j)
    
    resp = requests.get(url).text
    soup = BeautifulSoup(resp, 'lxml')
    html = etree.HTML(str(soup))
    
    df_temp = pd.DataFrame([{'OE',
                             'fourseaon_OE',
                             'status'}])
    
    list = html.xpath('//tr[@class="awe-row"]/td')
#     print(list[1].text)
#     print(len(list))

    list_name = [name.text for name in html.xpath('//tr[@class="awe-row"]/td[1]')]
    list_name
    list_value = [name.text for name in html.xpath('//tr[@class="awe-row"]/td[2]')]
    list_value
    
    list_fourseason=[]
    for i in range(len(list_name)):
        
        if list_name[i]=='Four Seasons':
            
            list_fourseason.append(list_value[i])
            
            
    df_temp = pd.DataFrame([{'OE': j,
                 'fourseaon_OE': ';'.join(list_fourseason),
                 'status': 'ok'}])
    df = pd.concat([df, df_temp], ignore_index=True).fillna('')
    
list_fourseason
df

           OE             fourseaon_OE status
0    2011248C                              ok
1    2011049C              97391;98391     ok
2    2011259C                   168319     ok
3    2010174C              67497;68497     ok
4    2029135C            197313;198313     ok
..        ...                      ...    ...
80    204486C              57793;58793     ok
81    204776C  57710;57796;58710;58796     ok
82    204885C                              ok
83    204822C              57785;58785     ok
84  204630DKQ                    58625     ok

[85 rows x 3 columns]

In [26]:
df.to_excel(r'C:\Users\YangTeng\Desktop\UA-menu\115-200.xlsx', index=False)