In [6]:
proxies = {'http': 'http://t19182064816778:9s5s2nv0@f290.kdltps.com:15818',
           'https': 'http://t19182064816778:9s5s2nv0@f290.kdltps.com:15818'}

import os
import pandas as pd
import requests
import re 
from bs4 import BeautifulSoup
from lxml import etree
import json
from selenium.webdriver import ChromeOptions

url='https://www.centricparts.com/disc-brake-rotor-121-40080'

resp = requests.get(url)
part_page = BeautifulSoup(resp.text,'lxml')

html = etree.HTML(str(part_page))
part_page

<!DOCTYPE html>
<html lang="en">
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# product: http://ogp.me/ns/product#">
<script>
    var BASE_URL = 'https\u003A\u002F\u002Fwww.centricparts.com\u002F';
    var require = {
        'baseUrl': 'https\u003A\u002F\u002Fwww.centricparts.com\u002Fstatic\u002Fversion1691018300\u002Ffrontend\u002FGamma\u002FBrakes\u002Fen_US'
    };</script> <meta charset="utf-8"/>
<meta content="Disc Brake Rotor" name="title"/>
<meta content="Non-Directional Finishes. Machined non-friction surfaces. Widest application coverage in the afterma" name="description"/>
<meta content="INDEX,FOLLOW" name="robots"/>
<meta content="width=device-width, initial-scale=1, user-scalable=no" name="viewport"/>
<meta content="telephone=no" name="format-detection"/>
<title>Disc Brake Rotor</title>
<link href="https://www.centricparts.com/static/version1691018300/frontend/Gamma/Brakes/en_US/mage/calendar.css" media="all" rel="stylesheet" type="text/css"/>
<link href="https://www.centricparts.com/static/version1691018300/frontend/Gamma/Brakes/en_US/css/styles-m.css" media="all" rel="stylesheet" type="text/css"/>
<link href="https://www.centricparts.com/static/version1691018300/frontend/Gamma/Brakes/en_US/css/bootstrap.min.css" media="all" rel="stylesheet" type="text/css"/>
<link href="https://www.centricparts.com/static/version1691018300/frontend/Gamma/Brakes/en_US/css/slickslider/slick.css" media="all" rel="stylesheet" type="text/css"/>
<link href="https://www.centricparts.com/static/version1691018300/frontend/Gamma/Brakes/en_US/css/slickslider/slick-theme.css" media="all" rel="stylesheet" type="text/css"/>
<link href="https://www.centricparts.com/static/version1691018300/frontend/Gamma/Brakes/en_US/Amasty_Base/vendor/slick/amslick.min.css" media="all" rel="stylesheet" type="text/css"/>
<link href="https://www.centricparts.com/static/version1691018300/frontend/Gamma/Brakes/en_US/Amasty_Storelocator/vendor/chosen/chosen.min.css" media="all" rel="stylesheet" type="text/css"/>
<link href="https://www.centricparts.com/static/version1691018300/frontend/Gamma/Brakes/en_US/mage/gallery/gallery.css" media="all" rel="stylesheet" type="text/css"/>
<link href="https://www.centricparts.com/static/version1691018300/frontend/Gamma/Brakes/en_US/css/styles-l.css" media="screen and (min-width: 768px)" rel="stylesheet" type="text/css"/>
<link href="https://www.centricparts.com/static/version1691018300/frontend/Gamma/Brakes/en_US/css/print.css" media="print" rel="stylesheet" type="text/css"/>
<script src="https://www.centricparts.com/static/version1691018300/frontend/Gamma/Brakes/en_US/requirejs/require.js" type="text/javascript"></script>
<script src="https://www.centricparts.com/static/version1691018300/frontend/Gamma/Brakes/en_US/mage/requirejs/mixins.js" type="text/javascript"></script>
<script src="https://www.centricparts.com/static/version1691018300/frontend/Gamma/Brakes/en_US/requirejs-config.js" type="text/javascript"></script>
<script src="https://cdn.scaleflex.it/plugins/js-cloudimage-360-view/2.6.0/js-cloudimage-360-view.min.js" type="text/javascript"></script>
<link href="https://use.typekit.net/hoo6qdc.css" rel="stylesheet" type="text/css"/>
<link href="https://www.centricparts.com/media/favicon/stores/1/Centric_Parts_Logo.png" rel="icon" type="image/x-icon"/>
<link href="https://www.centricparts.com/media/favicon/stores/1/Centric_Parts_Logo.png" rel="shortcut icon" type="image/x-icon"/>
<link href="https://www.centricparts.com/disc-brake-rotor-121-40080" rel="canonical"/>
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NRNTSLX');</script>
<!-- End Google Tag Manager -->
<!-- Start of LiveChat (www.livechat.com) code -->
<script>
    window.__lc = window.__lc || {};
    window.__lc.license = 9065305;
    ;(function(n,t,c){function i(n){return e._h?e._h.apply(null,n):e._q.push(n)}var e={_q:[],_h:null,_v:"2.0",on:function(){i(["on",c.call(arguments)])},once:function(){i(["once",c.call(arguments)])},off:function(){i(["off",c.call(arguments)])},get:function(){if(!e._h)throw new Error("[LiveChatWidget] You can't use getters before load.");return i(["get",c.call(arguments)])},call:function(){i(["call",c.call(arguments)])},init:function(){var n=t.createElement("script");n.async=!0,n.type="text/javascript",n.src="https://cdn.livechatinc.com/tracking.js",t.head.appendChild(n)}};!n.__lc.asyncInit&&e.init(),n.LiveChatWidget=n.LiveChatWidget||e}(window,document,[].slice))
</script>
<noscript><a href="https://www.livechat.com/chat-with/9065305/ " rel="nofollow">Chat with us</a>, powered by <a href="https://www.livechat.com/?welcome" rel="noopener nofollow" target="_blank">LiveChat</a></noscript>
<!-- End of LiveChat code -->
<meta content="width=device-width, initial-scale=1, user-scalable=no" name="viewport"/>
<style>
    .img-gallery img.fotorama__img {
       width: 100% !important;
    }
</style>
<meta content="product" property="og:type"/>
<meta content="Disc Brake Rotor" property="og:title"/>
<meta content="https://www.centricparts.com/media/catalog/product/cache/cff43daebeab49071a038b2bbdb484a3/1/2/121.40080_FRO_2.jpg" property="og:image"/>
<meta content="Disc Brake Rotor" property="og:description"/>
<meta content="https://www.centricparts.com/disc-brake-rotor-121-40080" property="og:url"/>
<meta content="0" property="product:price:amount"/>
<meta content="USD" property="product:price:currency"/>
</head>
<body class="amasty-mega-menu catalog-product-view product-disc-brake-rotor-121-40080 page-layout-1column" data-container="body" data-mage-init='{"loaderAjax": {}, "loader": { "icon": "https://www.centricparts.com/static/version1691018300/frontend/Gamma/Brakes/en_US/images/loader-2.gif"}}' id="html-body" itemscope="itemscope" itemtype="http://schema.org/Product">
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_PageBuilder/js/widget-initializer": {
                "config": {"[data-content-type=\"slider\"][data-appearance=\"default\"]":{"Magento_PageBuilder\/js\/content-type\/slider\/appearance\/default\/widget":false},"[data-content-type=\"map\"]":{"Magento_PageBuilder\/js\/content-type\/map\/appearance\/default\/widget":false},"[data-content-type=\"row\"]":{"Magento_PageBuilder\/js\/content-type\/row\/appearance\/default\/widget":false},"[data-content-type=\"tabs\"]":{"Magento_PageBuilder\/js\/content-type\/tabs\/appearance\/default\/widget":false},"[data-content-type=\"slide\"]":{"Magento_PageBuilder\/js\/content-type\/slide\/appearance\/default\/widget":{"buttonSelector":".pagebuilder-slide-button","showOverlay":"hover","dataRole":"slide"}},"[data-content-type=\"banner\"]":{"Magento_PageBuilder\/js\/content-type\/banner\/appearance\/default\/widget":{"buttonSelector":".pagebuilder-banner-button","showOverlay":"hover","dataRole":"banner"}},"[data-content-type=\"buttons\"]":{"Magento_PageBuilder\/js\/content-type\/buttons\/appearance\/inline\/widget":false},"[data-content-type=\"products\"][data-appearance=\"carousel\"]":{"Magento_PageBuilder\/js\/content-type\/products\/appearance\/carousel\/widget":false}},
                "breakpoints": {"desktop":{"label":"Desktop","stage":true,"default":true,"class":"desktop-switcher","icon":"Magento_PageBuilder::css\/images\/switcher\/switcher-desktop.svg","conditions":{"min-width":"1024px"},"options":{"products":{"default":{"slidesToShow":"5"}}}},"tablet":{"conditions":{"max-width":"1024px","min-width":"768px"},"options":{"products":{"default":{"slidesToShow":"4"},"continuous":{"slidesToShow":"3"}}}},"mobile":{"label":"Mobile","stage":true,"class":"mobile-switcher","icon":"Magento_PageBuilder::css\/images\/switcher\/switcher-mobile.svg","media":"only screen and (max-width: 768px)","conditions":{"max-width":"768px","min-width":"640px"},"options":{"products":{"default":{"slidesToShow":"3"}}}},"mobile-small":{"conditions":{"max-width":"640px"},"options":{"products":{"default":{"slidesToShow":"2"},"continuous":{"slidesToShow":"1"}}}}}            }
        }
    }
</script>
<div class="cookie-status-message" id="cookie-status">
    The store will not work correctly in the case when cookies are disabled.</div>
<script type="text/javascript">document.querySelector("#cookie-status").style.display = "none";</script>
<script type="text/x-magento-init">
    {
        "*": {
            "cookieStatus": {}
        }
    }
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "mage/cookies": {
                "expires": null,
                "path": "\u002F",
                "domain": ".www.centricparts.com",
                "secure": true,
                "lifetime": "3600"
            }
        }
    }
</script>
<noscript>
<div class="message global noscript">
<div class="content">
<p>
<strong>JavaScript seems to be disabled in your browser.</strong>
<span>
                        For the best experience on our site, be sure to turn on Javascript in your browser.                    </span>
</p>
</div>
</div>
</noscript>
<script>
    window.cookiesConfig = window.cookiesConfig || {};
    window.cookiesConfig.secure = true;
</script><script>    require.config({
        map: {
            '*': {
                wysiwygAdapter: 'mage/adminhtml/wysiwyg/tiny_mce/tinymce5Adapter'
            }
        }
    });</script><script>
    require.config({
        paths: {
            googleMaps: 'https\u003A\u002F\u002Fmaps.googleapis.com\u002Fmaps\u002Fapi\u002Fjs\u003Fv\u003D3\u0026key\u003D'
        },
        config: {
            'Magento_PageBuilder/js/utils/map': {
                style: ''
            },
            'Magento_PageBuilder/js/content-type/map/preview': {
                apiKey: '',
                apiKeyErrorMessage: 'You\u0020must\u0020provide\u0020a\u0020valid\u0020\u003Ca\u0020href\u003D\u0027https\u003A\u002F\u002Fwww.centricparts.com\u002Fadminhtml\u002Fsystem_config\u002Fedit\u002Fsection\u002Fcms\u002F\u0023cms_pagebuilder\u0027\u0020target\u003D\u0027_blank\u0027\u003EGoogle\u0020Maps\u0020API\u0020key\u003C\u002Fa\u003E\u0020to\u0020use\u0020a\u0020map.'
            },
            'Magento_PageBuilder/js/form/element/map': {
                apiKey: '',
                apiKeyErrorMessage: 'You\u0020must\u0020provide\u0020a\u0020valid\u0020\u003Ca\u0020href\u003D\u0027https\u003A\u002F\u002Fwww.centricparts.com\u002Fadminhtml\u002Fsystem_config\u002Fedit\u002Fsection\u002Fcms\u002F\u0023cms_pagebuilder\u0027\u0020target\u003D\u0027_blank\u0027\u003EGoogle\u0020Maps\u0020API\u0020key\u003C\u002Fa\u003E\u0020to\u0020use\u0020a\u0020map.'
            },
        }
    });
</script>
<script>
    require.config({
        shim: {
            'Magento_PageBuilder/js/utils/map': {
                deps: ['googleMaps']
            }
        }
    });
</script>
<div class="page-wrapper"><header class="ammenu-header-container page-header" id="ammenu-header-container"><div class="panel wrapper"><a class="action skip contentarea" href="#contentarea">
<span>
        Skip to Content    </span>
</a>
<div class="panel header"><div class="header links"><div data-appearance="default" data-content-type="html" data-decoded="true" data-element="main"><ul>
<li><a href="https://www.brakepartsinc.com/centric/" target="_blank">Customer Portal</a></li>
<li><a href="/partFinder/page/index">Online Catalog</a></li>
</ul></div></div><div data-appearance="default" data-content-type="html" data-decoded="true" data-element="main"><ul class="social-links">
<li>
<a class="social-links__icon facebook" href="https://www.facebook.com/Centric-Parts-106041871635270" target="_blank"> </a>
</li>
<li>
<a class="social-links__icon linkedin" href="https://www.linkedin.com/company/centricparts" target="_blank"> </a>
</li>
<li>
<a class="social-links__icon youtube" href="https://www.youtube.com/@Centric_Parts" target="_blank"> </a>
</li>
<li>
<a class="social-links__icon instagram" href="http://www.instagram.com/centric.parts/" target="_blank"> </a>
</li>
</ul>
</div>
<div class="language-holder">
<select id="">
<option value="">Select Language</option>
</select>
</div></div></div><div class="header content">
<!-- ko scope: 'index = ammenu_hamburger_toggle' -->
<!-- ko if: $data.source.isMobile() || false -->
<button aria-controls="ammenu-sidebar" aria-haspopup="menu" class="ammenu-button -hamburger -trigger" data-bind="
                    style: {
                        color: color_settings.hamburger_icon_color
                    },
                    event: {
                        click: toggling
                    },
                    attr: {
                        'aria-expanded': isOpen().toString(),
                        'aria-hidden': $data.source.isMobile() ? 'true' : 'false'
                    }" title="Toggling menu" type="button">
</button>
<style>
                @media (min-width: 1025px) {
                    .ammenu-button.-hamburger.-trigger {
                        display: none;
                    }
                }
            </style>
<!-- /ko -->
<!-- /ko -->
<a aria-label="store logo" class="ammenu-logo" href="https://www.centricparts.com/" title="">
<img alt="" src="https://www.centricparts.com/media/logo/stores/1/Centric_Parts_Logo.png" title=""/>
</a>
<button class="accordion dropdown-arrow-down">
<span>Search by part #</span>
</button>
<div class="search-box panel">
<div class="block block-search overlay">
<div class="block block-content">
<label class="toggle-search toggle-search--mob" data-role="minisearch-label" for="search"></label>
<form action="https://www.centricparts.com/catalogsearch/result/" class="form minisearch" id="search_mini_form" method="get">
<div class="field search">
<div class="control">
<span class="title">PARTS FINDER</span>
<input aria-autocomplete="both" aria-haspopup="false" autocomplete="off" class="input-text" id="search" maxlength="128" name="q" placeholder="Search" role="combobox" type="text" value=""/>
<button class="search-button" type="submit">SEARCH</button>
<div class="search-autocomplete" id="search_autocomplete"></div>
</div>
</div>
<div class="actions">
<button class="action search" title="Search" type="submit">
<span>Search</span>
</button>
</div>
</form>
</div>
</div>
</div>
<script>
    require([
        'jquery'
    ], function ($) {
        let width = window.innerWidth;
        const input = $('#search');
        if (width < 475) {
            input.attr('placeholder', 'Search');
        }
    });
</script>
</div>
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NRNTSLX" style="display:none;visibility:hidden" width="0">
</iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
</header>
<section class="ammenu-robots-navigation">
<nav aria-disabled="true" aria-hidden="true" class="navigation" data-action="navigation" tabindex="-1">
<ul aria-disabled="true" aria-hidden="true">
<li class="category-item nav-2" role="presentation">
<a href="https://www.centricparts.com/products" tabindex="-1" title="Products">
        Products    </a>
</li>
<li class="category-item nav-9" role="presentation">
<a href="https://www.centricparts.com/resources" tabindex="-1" title="Resources">
        Resources    </a>
</li>
<li class="category-item nav-17" role="presentation">
<a href="https://www.centricparts.com/partFinder/page/index" tabindex="-1" title="Find My Parts">
        Find My Parts    </a>
</li>
<li class="category-item nav-18" role="presentation">
<a href="https://www.centricparts.com/wheretobuy" tabindex="-1" title="Where to Buy">
        Where to Buy    </a>
</li>
<li class="category-item nav-19" role="presentation">
<a href="https://www.centricparts.com/sponsorship-stoptech-racing" tabindex="-1" title="Sponsorships">
        Sponsorships    </a>
</li>
<li class="category-item nav-20" role="presentation">
<a href="https://www.centricparts.com/about-us" tabindex="-1" title="About us">
        About us    </a>
</li>
</ul>
</nav>
</section>
<section class="ammenu-menu-wrapper" data-bind="
            scope: 'ammenu_wrapper',
            mageInit: {
                'Magento_Ui/js/core/app': {
                    components: {
                        'ammenu_wrapper': {
                            component: 'Amasty_MegaMenuLite/js/wrapper',

In [13]:
part = html.xpath('//div[@class="product-basic-details__text--part"]/span[1]/text()') 
part

['Part #121.40080 ']

In [60]:
Features = html.xpath('//div[@class="product-basic-details__features"]/p[1]/text()') 
Features

['Excellent performance; service life and value for a wide range of applications.']

In [62]:
df_temp = pd.DataFrame([{'Url': url,
                         'part': part,
                         'Features': Features,
                         'status': 'ok'}])

df_temp

,Url,part,Features,status
0,https://www.centricparts.com/disc-brake-rotor-...,[Part #121.40080 ],[Excellent performance; service life and value...,ok

In [48]:
list_name_1 = [name.text for name in html.xpath('//table[@class="product-basic-details__table"]/descendant::td')]
list_name_1 = [x.strip() for x in list_name_1 if x.strip()]
list_name_1

['Performance Level:',
 'Standard',
 'Brand:',
 'C-TEK',
 'Position:',
 'FRONT',
 'Quantity Required:',
 '2']

In [49]:
len(list_name_1)

8

In [58]:
q = 0
number_list = []
while q <len(list_name_1):
    
    number_list.append(q)
    
    q=q+2
 
list_name = []
list_value = []
for i in number_list:
    list_name.append(list_name_1[i])
    list_value.append(list_name_1[i+1])

['Standard', 'C-TEK', 'FRONT', '2']

In [63]:
for name, value in zip(list_name, list_value):
    df_temp[name.lower()] = value
df_temp

,Url,part,Features,status,performance level:,brand:,position:,quantity required:
0,https://www.centricparts.com/disc-brake-rotor-...,[Part #121.40080 ],[Excellent performance; service life and value...,ok,Standard,C-TEK,FRONT,2

In [84]:
list_name_2 = [name.text for name in html.xpath('//div[@class="product-basic-details__text--section"]/descendant::td')][2:]
list_name_2 = [x.strip() for x in list_name_2 if x.strip()]
list_name_2

['Brand Description',
 'C-Tek Standard Brake Rotor',
 'Outside Diameter (Millimeter)',
 '311.800',
 'Outside Diameter (Inch)',
 '12.276',
 'ABS Tone Ring Included',
 'No',
 'Short Description',
 'Standard Brake Rotor',
 'Hazardous Material',
 'No',
 'Minimum Order Quantity',
 '1',
 'Weight [cntrc] lbs',
 '16.750',
 'Misc Holes [cntrc]',
 '4',
 'Notes [cntrc]',
 'Vented Hat',
 'California Proposition 65 Site [basic]',
 'https://www.p65warnings.ca.gov/',
 'Disc Mounting [cntrc]',
 'Floating',
 'Nominal Thickness (Inch)',
 '0.984',
 'Bearings Included',
 'No',
 'Mounting Bolt Hole Circle Diameter (Inch)',
 '4.500',
 'Stud/Lug Hole Diameter (Inch)',
 '0.496',
 'Overall Height (Inch)',
 '1.858',
 'Surface Type',
 'Smooth',
 'Center Hole Diameter (Inch)',
 '2.528',
 'Center Hole Diameter (Millimeter)',
 '64.200',
 'Overall Height (Millimeter)',
 '47.200',
 'Discard Thickness (Inch)',
 '0.906',
 'Nominal Thickness (Millimeter)',
 '25.000',
 'Stud/Lug Hole Quantity',
 '5',
 'Stud/Lug Hole Diameter (Millimeter)',
 '12.600',
 'Discard Thickness (Millimeter)',
 '23.000',
 'Mounting Bolt Hole Circle Diameter (Millimeter)',
 '114.300',
 'Solid Or Vented Type Rotor',
 'Vented',
 'Vane Style [cntrc]',
 'Straight']

In [85]:
len(list_name_2)

58

In [86]:
p = 0
number_list = []
while p <len(list_name_2):
    number_list.append(p)
    p=p+2
      
list_name = []
list_value = []
for i in number_list:
    list_name.append(list_name_2[i])
    list_value.append(list_name_2[i+1])

'Brand Description'

In [87]:
for name, value in zip(list_name, list_value):
    df_temp[name.lower()] = value
df_temp

,Url,part,Features,status,performance level:,brand:,position:,quantity required:,no,brand description,...,center hole diameter (millimeter),overall height (millimeter),discard thickness (inch),nominal thickness (millimeter),stud/lug hole quantity,stud/lug hole diameter (millimeter),discard thickness (millimeter),mounting bolt hole circle diameter (millimeter),solid or vented type rotor,vane style [cntrc]
0,https://www.centricparts.com/disc-brake-rotor-...,[Part #121.40080 ],[Excellent performance; service life and value...,ok,Standard,C-TEK,FRONT,2,Short Description,C-Tek Standard Brake Rotor,...,64.200,47.200,0.906,25.000,5,12.600,23.000,114.300,Vented,Straight

In [72]:
Application_Summary = html.xpath('//div[@class="product-basic-details__applicable-car"]/text()') [1]
Application_Summary

'\n                Acura ILX 2016, RDX 2018-2013            '