In [1]:
import os
list_file = list(os.walk(r'C:\Users\YangTeng\Downloads\爬虫\爬\MAF\STANDARD-官网'))[0][2]
if '.DS_Store' in list_file:
   list_file.remove('.DS_Store')

len(list_file)

4

In [2]:
import pandas as pd
df = pd.DataFrame(columns=['Part_Number', 'Scr','Title','POP','Per_Car'])

df

Empty DataFrame
Columns: [Part_Number, Scr, Title, POP, Per_Car]
Index: []

In [3]:
import json

In [4]:
for file in list_file:
    print(file)
    with open('C:/Users/YangTeng/Downloads/爬虫/爬/MAF/STANDARD-官网/' + file) as f:
        list_part = f.read()[1:-1].split('},{')
        for i in range(len(list_part)):
            if i == 0:
                part = json.loads(list_part[i] + '}')
            elif i == len(list_part) - 1:
                part = json.loads('{' + list_part[i])
            else:
                part = json.loads('{' + list_part[i] + '}')
                
            df_temp = pd.DataFrame([{'Part_Number': part['Part_Number'],
                                     'Src': part['Src'],
                                    'Title':part['Title']
#                                     'POP':part['POP'],
#                                     'Per_Car':part['Per_Car']
                                    }])
            df = pd.concat([df, df_temp], ignore_index=True)

ecatalog.smpcorp.com_V2_STD_# (1).txt
ecatalog.smpcorp.com_V2_STD_# (2).txt
ecatalog.smpcorp.com_V2_STD_#.txt
ecatalog.smpcorp.com_V2_STD_#_partsearch_searchText_Air%20Flow%20Sensor_type=p&search=s.txt

In [5]:
df.to_excel(r'C:\Users\YangTeng\Desktop\MAF\STANDARD.xlsx', index=False)

df

,Part_Number,Scr,Title,POP,Per_Car,Src
0,MAS0418,NaN,New Mass Air Flow Sensor,NaN,NaN,https://extapi.smpcorp.com/ihgs/imagehandlergs...
1,MAS0420,NaN,New Mass Air Flow Sensor,NaN,NaN,https://extapi.smpcorp.com/ihgs/imagehandlergs...
2,MAS0421,NaN,New Mass Air Flow Sensor,NaN,NaN,https://extapi.smpcorp.com/ihgs/imagehandlergs...
3,MAS0422,NaN,New Mass Air Flow Sensor,NaN,NaN,https://extapi.smpcorp.com/ihgs/imagehandlergs...
4,MAS0423,NaN,New Mass Air Flow Sensor,NaN,NaN,https://extapi.smpcorp.com/ihgs/imagehandlergs...
...,...,...,...,...,...,...
360,MAS0245,NaN,New Mass Air Flow Sensor,NaN,NaN,https://extapi.smpcorp.com/ihgs/imagehandlergs...
361,MAS0251,NaN,New Mass Air Flow Sensor,NaN,NaN,https://extapi.smpcorp.com/ihgs/imagehandlergs...
362,MAS0259,NaN,New Mass Air Flow Sensor,NaN,NaN,https://extapi.smpcorp.com/ihgs/imagehandlergs...
363,MAS0280,NaN,New Mass Air Flow Sensor,NaN,NaN,https://extapi.smpcorp.com/ihgs/imagehandlergs...
364,MAS0302,NaN,New Mass Air Flow Sensor,NaN,NaN,https://extapi.smpcorp.com/ihgs/imagehandlergs...