###### 网站：https://www.ebay.de/sch/i.html?_dkr=1&iconV2Request=true&_blrs=recall_filtering&_ssn=nb-parts-de&store_cat=0&store_name=nbpartsersatzteile&_oac=1&_nkw=bremsscheiben
注：请求方式：https://developer.ebay.com/devzone/shopping/docs/CallRef/GetSingleItem.html

In [1]:
auth = '757F054AA22E1711B598A89EB276EDC193933EC8'

list_appid = ['tfy6d12dc-19a5-4093-9f00-f276d950f77',
              'picheng11-5163-4258-be21-a5629527a07',
              'Shanghai-b2aa-4eed-82c3-b1e42e2e9179',
              'danjidin-f8b1-4e84-adce-026944025ceb',
              'ibay365a-b93e-46e7-8b46-6a33b716ab2a',
              '-IBAY365-PRD-08e35c535-85b731b3']

In [2]:
import pandas as pd

In [4]:
df_menu = pd.read_excel(r'C:\Users\YangTeng\Desktop\结果\03、eBay\menu_J.xlsx', header=0, dtype={'Item_Number': str})
list_item = df_menu['Item_Number'].to_list()

print('总数量：' + str(len(list_item)))
list_item

总数量：5210

['373651381733',
 '372749825457',
 '352852280880',
 '371671143501',
 '231811140279',
 '372607254605',
 '354863824088',
 '234724594860',
 '373603471564',
 '231999231771',
 '351591859793',
 '373603456794',
 '234524726177',
 '374040164887',
 '231998752345',
 '232998814725',
 '353576959375',
 '373651422336',
 '373652586576',
 '235055845742',
 '374763041141',
 '353244176405',
 '371713349375',
 '373651450430',
 '372563364968',
 '354852956813',
 '373652531695',
 '373652531848',
 '231998639555',
 '233360502330',
 '353578674047',
 '233069634778',
 '353522057824',
 '353578695397',
 '234041063480',
 '354774422203',
 '374759018638',
 '234039534691',
 '234041045078',
 '351814360939',
 '351814360979',
 '351773312632',
 '351773304629',
 '372543984610',
 '372560205984',
 '231997911534',
 '373604507078',
 '373652593250',
 '351772588338',
 '231998046113',
 '234572133213',
 '353587242103',
 '352149179093',
 '353578697934',
 '372544066078',
 '372564353851',
 '374702048862',
 '351003080788',
 '351002654837',
 '373603461426',
 '353578635088',
 '353522042566',
 '353523587025',
 '352553591878',
 '234999228024',
 '351788128556',
 '354671007557',
 '374582560351',
 '371671049575',
 '351772958804',
 '352511578687',
 '373652558362',
 '353577031252',
 '231848264689',
 '354858848456',
 '374759013747',
 '372003028352',
 '352592109154',
 '234092963197',
 '234041076207',
 '373652579369',
 '351002727662',
 '352363261141',
 '372544000601',
 '353594459413',
 '352493177761',
 '373651381675',
 '373651381780',
 '354774422782',
 '352742591848',
 '234093019539',
 '235055863492',
 '371688379611',
 '352511582702',
 '233000180561',
 '234483728299',
 '373994489163',
 '235052255447',
 '353522042616',
 '353523587032',
 '372560182115',
 '233315331737',
 '231999627246',
 '235052248820',
 '373604504369',
 '352553563621',
 '353578673828',
 '374678447289',
 '374678448393',
 '354774422787',
 '234478418069',
 '233330653024',
 '354223415486',
 '233104782606',
 '351002212773',
 '231999409345',
 '354763669459',
 '374678460527',
 '233000176377',
 '233047971767',
 '231848316272',
 '354763668961',
 '234999237400',
 '374113687250',
 '372497636707',
 '373603456631',
 '372562525840',
 '372341744327',
 '233061497854',
 '234214694093',
 '372742155661',
 '353522032470',
 '233329634477',
 '374688163680',
 '352555083338',
 '352482087114',
 '373604487813',
 '373604487867',
 '352746449801',
 '372733005815',
 '374138900770',
 '233149646361',
 '234039559907',
 '233315329917',
 '351831910382',
 '234039561168',
 '371671194143',
 '233151996131',
 '231770787953',
 '234999229421',
 '234658966858',
 '373635542702',
 '232780212751',
 '373627139547',
 '234999225098',
 '234039569145',
 '353536344281',
 '353578695167',
 '354852919300',
 '351773304593',
 '350846641046',
 '370809156559',
 '234091476834',
 '352271693773',
 '373604504321',
 '352521748645',
 '352550929813',
 '354634086703',
 '374551514900',
 '374678439818',
 '354763656022',
 '374678439752',
 '234999229656',
 '373651443520',
 '374737456477',
 '373603454328',
 '354318381822',
 '374678448455',
 '235005373025',
 '233230110898',
 '374767581647',
 '354763656084',
 '372413811598',
 '374678461139',
 '372320551881',
 '233089678014',
 '234091515015',
 '234999227220',
 '374759024915',
 '373603464756',
 '373652558136',
 '371053737477',
 '371671709554',
 '235005370675',
 '352392237092',
 '352837810338',
 '373251652591',
 '233715189195',
 '234091466123',
 '234091466183',
 '354852961018',
 '372493505105',
 '231312219407',
 '374688162449',
 '354763653188',
 '374678438875',
 '374678460878',
 '233272341327',
 '234999227544',
 '374678436006',
 '233220719733',
 '372316127182',
 '374702049273',
 '234999225272',
 '235005371456',
 '234058442403',
 '351772668596',
 '231999248782',
 '373603461379',
 '373604482874',
 '353523594908',
 '232855310807',
 '233084032793',
 '374678439137',
 '374759027209',
 '234039594736',
 '374244091267',
 '374244097147',
 '234091518784',
 '234091518828',
 '354763664664',
 '371688379374',
 '354763667796',
 '353576964232',
 '234041076098',
 '232998814321',
 '235005368996',
 '234039560331',
 '234039560574',
 '373659868343',
 '233123377559',
 '234612770409',
 '373603476079',
 '354774419477',
 '371008616403',
 '373651415562',
 '234091489248',
 '371008555851',
 '232782539188',
 '373603456615',
 '234039560645',
 '235052248803',
 '354763669976',
 '373652586658',
 '354763651675',
 '372320496867',
 '354763668694',
 '371671174044',
 '352503286818',
 '232029892832',
 '354763650395',
 '235008008230',
 '353577014028',
 '232459736958',
 '372497372369',
 '353576966409',
 '373652570636',
 '354763653621',
 '353663804033',
 '354774421129',
 '234091476997',
 '235059553562',
 '353776869487',
 '353776869594',
 '352621163824',
 '374763042396',
 '353522048973',
 '373603464943',
 '231999594786',
 '372316189432',
 '352565064150',
 '371067073145',
 '354858840058',
 '354769461544',
 '354769463587',
 '374678460532',
 '352553597995',
 '234999229407',
 '354790861774',
 '351590927824',
 '370833923629',
 '372614306986',
 '232417159929',
 '354763653646',
 '235052254202',
 '352562410150',
 '234039667288',
 '374678438948',
 '352368410861',
 '374103694397',
 '352615363514',
 '234256755657',
 '232785821619',
 '353758937498',
 '234226833109',
 '232941786469',
 '352510816327',
 '373603454384',
 '231819366849',
 '353522027507',
 '353523568251',
 '373977016599',
 '233003585280',
 '234999230093',
 '374678458056',
 '373651394769',
 '372685962471',
 '371226896561',
 '353523568308',
 '234041060070',
 '233084101161',
 '352550909433',
 '371001405119',
 '234039534702',
 '372564354233',
 '232788262863',
 '372314310107',
 '351589326635',
 '234170479308',
 '353959500184',
 '351011409215',
 '351773642918',
 '352562410461',
 '233072025559',
 '372215901623',
 '353578695392',
 '352555039089',
 '372449000974',
 '371671995335',
 '353960478642',
 '353576974788',
 '232011091388',
 '371598250992',
 '231848223025',
 '371495981981',
 '232785929483',
 '232549616430',
 '232578996882',
 '352222005669',
 '353522042816',
 '234126063735',
 '234092963019',
 '232566217555',
 '351050446222',
 '232997552809',
 '352510013983',
 '351136467150',
 '351148745097',
 '371702399426',
 '373651422153',
 '233088226862',
 '234039615751',
 '234041083995',
 '371088770309',
 '354763673519',
 '353578660332',
 '373652551652',
 '372318856294',
 '353576993671',
 '373673311706',
 '371008580318',
 '351772540599',
 '234039559695',
 '234499938283',
 '373652546016',
 '235014199844',
 '374523622744',
 '234904957269',
 '352511580929',
 '354790860368',
 '354763648642',
 '235005372766',
 '371970660082',
 '234999225315',
 '235005372729',
 '351633938092',
 '352274979470',
 '371008590944',
 '371672057277',
 '351002733790',
 '372518656222',
 '354763676851',
 '372326423397',
 '233072070154',
 '371671665434',
 '372625890491',
 '232652983494',
 '232652983527',
 '231997833389',
 '234091486475',
 '234708775485',
 '353577013901',
 '352621163652',
 '371671959403',
 '372765321066',
 '352363260814',
 '374678469729',
 '234999244879',
 '354763673191',
 '351773494853',
 '354774422945',
 '374678431710',
 '353523594931',
 '234092963213',
 '352368449872',
 '371693801275',
 '231767507305',
 '234534160223',
 '234534160364',
 '234039615685',
 '373652558561',
 '354763673032',
 '373977015259',
 '353576974793',
 '352511582534',
 '370860828222',
 '234039550138',
 '234999238168',
 '234999244507',
 '352482087103',
 '353578684726',
 '234100957652',
 '235005372982',
 '234999225311',
 '234084008760',
 '353577009169',
 '371071903488',
 '373977013994',
 '234039549971',
 '373616540460',
 '351589489508',
 '351773414252',
 '372497372515',
 '234499866371',
 '234091457452',
 '374678467023',
 '234039594697',
 '234092963141',
 '234092963203',
 '350848660979',
 '352511581171',
 '353960478215',
 '372215902141',
 '352222005555',
 '233234670951',
 '352698277510',
 '233087079902',
 '372564349887',
 '352703128230',
 '352564200060',
 '371009453137',
 '351772967093',
 '351775769731',
 '234039568674',
 '353522037212',
 '372493461753',
 '354725750093',
 '354725751089',
 '234493814076',
 '373975867276',
 '351655970515',
 '353578698068',
 '233069658000',
 '373603456673',
 '351005356673',
 '351773412298',
 '232950647118',
 '374678436574',
 '373651443502',
 '234091527254',
 '371013894586',
 '371030896309',
 '371671861302',
 '373651441170',
 '373603450492',
 '352572548171',
 '371671232742',
 '371503706653',
 '231999402074',
 '232780407238',
 '370982137884',
 '234091477006',
 '232440834634',
 '234091455066',
 '352363981016',
 '370922564906',
 '370922873999',
 '233315330709',
 '234091486476',
 '373975865586',
 '353959503189',
 '373977015260',
 '353522019890',
 '353523543195',
 '371671232754',
 '373604485936',
 '233089621910',
 '234093007179',
 '232789575807',
 '373652565249',
 '370888443530',
 '373975863148',
 '234465834785',
 '234091486469',
 '234091486546',
 '231848137731',
 '371009011736',
 '373075962224',
 '353577013919',
 '353578655851',
 '353576941096',
 '373651375889',
 '232780235852',
 '372314324699',
 '374678463826',
 '233000177283',
 '373651377862',
 '372577508490',
 '234041052239',
 '372466500873',
 '234999237558',
 '372577508433',
 '371671517262',
 '234999237907',
 '351011446253',
 '353960477257',
 '352555061144',
 '233089559256',
 '235005372989',
 '372321527859',
 '352482086631',
 '371014977825',
 '354763673551',
 '371555956006',
 '371555999051',
 '371089707723',
 '351616240773',
 '232781375061',
 '370914964050',
 '371672211027',
 '352636146973',
 '372512091131',
 '233324854998',
 '371671447194',
 '234091512107',
 '234091512260',
 '373651439194',
 '371555973730',
 '353960476954',
 '351593738913',
 '374702048475',
 '372622533924',
 '372444660484',
 '374678452119',
 '374759011388',
 '353523599394',
 '234091518678',
 '353578655604',
 '234999229522',
 '372649895989',
 '233072026098',
 '233084025490',
 '234041078183',
 '374759022651',
 '354403031721',
 '354470018638',
 '354863444637',
 '374678438805',
 '233089538903',
 '234091489464',
 '353578695048',
 '374688163722',
 '232814029649',
 '374678438883',
 '352550952453',
 '234039550313',
 '234041060031',
 '234082884250',
 '353522054494',
 '353523602599',
 '374759018625',
 '374803662490',
 '373652551827',
 '352598972696',
 '235052251894',
 '374678447353',
 '372477682331',
 '350737201941',
 '373603464930',
 '231919071377',
 '232785945611',
 '352368447225',
 '373603473043',
 '373604513985',
 '354790862631',
 '235005371763',
 '372563411984',
 '354763651761',
 '353523578128',
 '235005369100',
 '373652551839',
 '373603464740',
 '233072093574',
 '374432940175',
 '374432940380',
 '354819591798',
 '235059269282',
 '352576739845',
 '232789565012',
 '353577009213',
 '234296356191',
 '353522049022',
 '235005369514',
 '354852962532',
 '372320503713',
 '233219614000',
 '234039534798',
 '374719842924',
 '354763652738',
 '231999606841',
 '350894171208',
 '374678440335',
 '373182956203',
 '353190441822',
 '373651376105',
 '374759013225',
 '354763656115',
 '233069709475',
 '235026551203',
 '235026551206',
 '232903842601',
 '234041076197',
 '353577009191',
 '372548148641',
 '374759022575',
 '374688163059',
 '353576941214',
 '235052247194',
 '234999235228',
 '234999227692',
 '354763650697',
 '374678438856',
 '354763651007',
 '374678441452',
 '232582780571',
 '232785929379',
 '373651415599',
 '233061711954',
 '374678438103',
 '372612462607',
 '351772607003',
 '234041086459',
 '234224963796',
 '233314563499',
 '232806830569',
 '374678440956',
 '372500569223',
 '373604487967',
 '372457282498',
 '352560723297',
 '234039594928',
 '374759013857',
 '233347419022',
 '372778050085',
 '373603456799',
 '373604487933',
 '353990593516',
 '352731572635',
 '371672098822',
 '374688162436',
 '235052255048',
 '353522048948',
 '233084073883',
 '373652540999',
 '374348897553',
 '232788312794',
 '234999234859',
 '234999224889',
 '234692168643',
 '373441334359',
 '353367850997',
 '234639866922',
 '235058145754',
 '373977083324',
 '354279039064',
 '234694969477',
 '234041089515',
 '374678432427',
 '371672098797',
 '352553597481',
 '352363277826',
 '372550323273',
 '234092962758',
 '354763653655',
 '232789598654',
 '373604496559',
 '352555101175',
 '234091489488',
 '354763653620',
 '353095309745',
 '353523614542',
 '374688162744',
 '353960478186',
 '235008008618',
 '234999228362',
 '373603461235',
 '234091489259',
 '234041056354',
 '374688163122',
 '235058145361',
 '234999225276',
 '351773462132',
 '235005371466',
 '234064608504',
 '372548006023',
 '353523594810',
 '235093559568',
 '371730183815',
 '373604487932',
 '232785893504',
 '373603471778',
 '354852912770',
 '234041067959',
 '235052253158',
 '374759013670',
 '354774419462',
 '234396320280',
 '353523611249',
 '373652582576',
 '373652570702',
 '373603494820',
 '353578634910',
 '374168929030',
 '353523607663',
 '353523607808',
 '234999227259',
 '352555101029',
 '373419315782',
 '233088189060',
 '235005368976',
 '235005371968',
 '351651270153',
 '232999884506',
 '234041060142',
 '353523559947',
 '234041073208',
 '352482086684',
 '373643749322',
 '351755379113',
 '374678435598',
 '354763652370',
 '235052248360',
 '354774421773',
 '354852950682',
 '234093027866',
 '373651435941',
 '234093019500',
 '373652579561',
 '353700951754',
 '353576981581',
 '354536039781',
 '354536040449',
 '353577017664',
 '232961130982',
 '353578664757',
 '373651441149',
 '234999228642',
 '372564413137',
 '354400425319',
 '354400425578',
 '374004075314',
 '353990593245',
 '354400425716',
 '374759026268',
 '353576985659',
 '234091494480',
 '372563417459',
 '232788306035',
 '354794660756',
 '354763673043',
 '233069555276',
 '373651443391',
 '354763668805',
 '350894149669',
 '373652540949',
 '354387290786',
 '374688163284',
 '354763656041',
 '353577009175',
 '353577009284',
 '374688163684',
 '374759011119',
 '235052256163',
 '374759029736',
 '234041084137',
 '354852962485',
 '353583826480',
 '354863447940',
 '235059554072',
 '374577987325',
 '231999675332',
 '352564209250',
 '372560178224',
 '234092963080',
 '373652541187',
 '372562588414',
 '372625890567',
 '371695774430',
 '232570812465',
 '235052251048',
 '352837810292',
 '374759011062',
 '354388680037',
 '372320519450',
 '235058317004',
 '373603458659',
 '235052250799',
 '354763656599',
 '353598072984',
 '234041063790',
 '232241874825',
 '374767580874',
 '352689036873',
 '235069250916',
 '354863821470',
 '234630725646',
 '353522039036',
 '374678439711',
 '373603495014',
 '374759022559',
 '374759022254',
 '353577030243',
 '234039582789',
 '354791094698',
 '373603456838',
 '373977017306',
 '234055962673',
 '235052255761',
 '374688163280',
 '353522042773',
 '374763036787',
 '352570921163',
 '372497364258',
 '234092988323',
 '231999505890',
 '373652531911',
 '353522038315',
 '354763680981',
 '232806856938',
 '372321546133',
 '353523599420',
 '372562561578',
 '352511580715',
 '354852921729',
 '352363996417',
 '234091471768',
 '374328237485',
 '354363840968',
 '374732088775',
 '373917979687',
 '234039579997',
 '373732678438',
 '234039594664',
 '354852963225',
 '373652545726',
 '234041078201',
 '373604504371',
 '374781965890',
 '352565961273',
 '353537164818',
 '232780280087',
 '373651425581',
 '234562737210',
 '354072744063',
 '353522032518',
 '374678455897',
 '234999237018',
 '374759021223',
 '353523577988',
 '374759020981',
 '354763651458',
 '374678436926',
 '353523595088',
 '373652531646',
 '353520602189',
 '373572094588',
 '234041084058',
 '371497275937',
 '352703130648',
 '354059437204',
 '373564546839',
 '352385542828',
 '353578634823',
 '372316179949',
 '374759012857',
 '373749756959',
 '233364191743',
 '235074563207',
 '373436334710',
 '353578684927',
 '354863820271',
 '374122900427',
 '232911235620',
 '373603470042',
 '234039615589',
 '372321527878',
 '234785881351',
 '234785882323',
 '353578646659',
 '235005371088',
 '353578660377',
 '353578655477',
 '374719840230',
 '372550250103',
 '352562378685',
 '374759018677',
 '372725930990',
 '234261223680',
 '233125685928',
 '354858880040',
 '374073040009',
 '353522049243',
 '374759021537',
 '233100542549',
 '232384786522',
 '354852925867',
 '235033395407',
 '372649899426',
 '354863820827',
 '374678447249',
 '372351198587',
 '234999234071',
 '234039620188',
 '353578709005',
 '235005371793',
 '354852952487',
 '374759013730',
 '353522049162',
 '371860438895',
 '235055842717',
 '374763042737',
 '374719840973',
 '232013244014',
 '373604488124',
 '234499938347',
 '353998409402',
 '373603461301',
 '373651415639',
 '235026551553',
 '373652531849',
 '352441451190',
 '374702049426',
 '235052251340',
 '234041093642',
 '234582623799',
 '352562446403',
 '372497364290',
 '233234670983',
 '233234671006',
 '373604499685',
 '354852962924',
 '233007725917',
 '235052253427',
 '354852921674',
 '374678459224',
 '371672067360',
 '234624888198',
 '374759013359',
 '354823637168',
 '372743867175',
 '234041078494',
 '234092963161',
 '354823635698',
 '374732088036',
 '374732089601',
 '354852917219',
 '373603465028',
 '235052251777',
 '354852962949',
 '234041078319',
 '374759018674',
 '374767189112',
 '235052248377',
 '354863341343',
 '235052248518',
 '373604485796',
 '374678463616',
 '354852919147',
 '374702049267',
 '234694968877',
 ...]

In [5]:
df = pd.DataFrame(columns=['Item_Number',
                           'Title',
                           'Price',
                           'Sold',
                           'Vehicle',
                           'Src',
                           'status'])

df

Empty DataFrame
Columns: [Item_Number, Title, Price, Sold, Vehicle, Src, status]
Index: []

In [6]:
import random
import requests
import json

In [7]:
i = 0

index_appid = random.randint(0, 5)

developer = 'http://106.75.138.2/index.php/api/GetAppToken?auth=' + auth + '&appid=' + list_appid[index_appid]
resp = requests.get(developer).text
token = json.loads(resp)['getapptokenResponse']['token']

token

headers = {'X-EBAY-API-IAF-TOKEN': token}
resp = requests.get('https://open.api.ebay.com/shopping?callname=GetSingleItem&appid=' + list_appid[index_appid] + '&responseencoding=JSON&siteid=0&version=967&IncludeSelector=Details,Compatibility,ItemSpecifics&ItemID=' + a, headers=headers).text

info = json.loads(resp)
if info['Ack'] != 'Success':
    print('Error')
else:
    print('Success')
    
info

Error

{'Timestamp': '2023-08-31T08:31:30.705Z',
 'Ack': 'Failure',
 'Errors': [{'ShortMessage': 'IP limit exceeded.',
   'LongMessage': 'Applications from this IP address are limited in the number of calls they can make.',
   'ErrorCode': '1.21',
   'SeverityCode': 'Error',
   'ErrorClassification': 'RequestError'}],
 'Build': '1299_CORE_APILW_19146596_R1',
 'Version': '1299'}

In [8]:
# Item.Title - None
title = info['Item']['Title']

title

'Headlight For 2012 2013 2014 Ford Focus Hatchback or Sedan Right With Bulb CAPA'

In [9]:
# Item.CurrentPrice - None
price = info['Item']['CurrentPrice']['CurrencyID'] + ' ' + str(info['Item']['CurrentPrice']['Value'])

price

'USD 160.86'

In [10]:
# Item.QuantitySold - Details
sold = info['Item']['QuantitySold']

sold

0

In [11]:
# Item.ItemCompatibilityList - Compatibility
if 'ItemCompatibilityList' in info['Item']:
    vehicle = info['Item']['ItemCompatibilityList']['Compatibility']
else:
    vehicle = ''
    
vehicle

[{'NameValueList': [{'Value': []},
   {'Name': 'Year', 'Value': ['2014']},
   {'Name': 'Make', 'Value': ['Ford']},
   {'Name': 'Model', 'Value': ['Focus']},
   {'Name': 'Trim', 'Value': ['ST Hatchback 4-Door']},
   {'Name': 'Engine',
    'Value': ['2.0L 1999CC 122Cu. In. l4 GAS DOHC Turbocharged']}],
  'CompatibilityNotes': 'Hatchback, Location : Passenger Side -- For 4Cyl 2.0L 2013-2014 Ford Focus Headlight Lamp Head light'},
 {'NameValueList': [{'Value': []},
   {'Name': 'Year', 'Value': ['2014']},
   {'Name': 'Make', 'Value': ['Ford']},
   {'Name': 'Model', 'Value': ['Focus']},
   {'Name': 'Trim', 'Value': ['Titanium Hatchback 4-Door']},
   {'Name': 'Engine',
    'Value': ['2.0L 1999CC 122Cu. In. l4 FLEX DOHC Naturally Aspirated']}],
  'CompatibilityNotes': 'Hatchback, Location : Passenger Side -- For 4Cyl 2.0L 2012-2014 Ford Focus Headlight Lamp Head light'},
 {'NameValueList': [{'Value': []},
   {'Name': 'Year', 'Value': ['2014']},
   {'Name': 'Make', 'Value': ['Ford']},
   {'Name': 'Model', 'Value': ['Focus']},
   {'Name': 'Trim', 'Value': ['Titanium Hatchback 4-Door']},
   {'Name': 'Engine',
    'Value': ['2.0L 1999CC 122Cu. In. l4 GAS DOHC Naturally Aspirated']}],
  'CompatibilityNotes': 'Hatchback, Location : Passenger Side -- For 4Cyl 2.0L 2013-2014 Ford Focus Headlight Lamp Head light'},
 {'NameValueList': [{'Value': []},
   {'Name': 'Year', 'Value': ['2014']},
   {'Name': 'Make', 'Value': ['Ford']},
   {'Name': 'Model', 'Value': ['Focus']},
   {'Name': 'Trim', 'Value': ['Titanium Sedan 4-Door']},
   {'Name': 'Engine',
    'Value': ['2.0L 1999CC 122Cu. In. l4 FLEX DOHC Naturally Aspirated']}],
  'CompatibilityNotes': 'Sedan, Location : Passenger Side -- For 4Cyl 2.0L 2012-2014 Ford Focus Headlight Lamp Head light'},
 {'NameValueList': [{'Value': []},
   {'Name': 'Year', 'Value': ['2014']},
   {'Name': 'Make', 'Value': ['Ford']},
   {'Name': 'Model', 'Value': ['Focus']},
   {'Name': 'Trim', 'Value': ['Titanium Sedan 4-Door']},
   {'Name': 'Engine',
    'Value': ['2.0L 1999CC 122Cu. In. l4 GAS DOHC Naturally Aspirated']}],
  'CompatibilityNotes': 'Sedan, Location : Passenger Side -- For 4Cyl 2.0L 2013-2014 Ford Focus Headlight Lamp Head light'},
 {'NameValueList': [{'Value': []},
   {'Name': 'Year', 'Value': ['2013']},
   {'Name': 'Make', 'Value': ['Ford']},
   {'Name': 'Model', 'Value': ['Focus']},
   {'Name': 'Trim', 'Value': ['ST Hatchback 4-Door']},
   {'Name': 'Engine',
    'Value': ['2.0L 1999CC 122Cu. In. l4 GAS DOHC Turbocharged']}],
  'CompatibilityNotes': 'Hatchback, Location : Passenger Side -- For 4Cyl 2.0L 2013-2014 Ford Focus Headlight Lamp Head light'},
 {'NameValueList': [{'Value': []},
   {'Name': 'Year', 'Value': ['2013']},
   {'Name': 'Make', 'Value': ['Ford']},
   {'Name': 'Model', 'Value': ['Focus']},
   {'Name': 'Trim', 'Value': ['Titanium Hatchback 4-Door']},
   {'Name': 'Engine',
    'Value': ['2.0L 1999CC 122Cu. In. l4 FLEX DOHC Naturally Aspirated']}],
  'CompatibilityNotes': 'Hatchback, Location : Passenger Side -- For 4Cyl 2.0L 2012-2014 Ford Focus Headlight Lamp Head light'},
 {'NameValueList': [{'Value': []},
   {'Name': 'Year', 'Value': ['2013']},
   {'Name': 'Make', 'Value': ['Ford']},
   {'Name': 'Model', 'Value': ['Focus']},
   {'Name': 'Trim', 'Value': ['Titanium Hatchback 4-Door']},
   {'Name': 'Engine',
    'Value': ['2.0L 1999CC 122Cu. In. l4 GAS DOHC Naturally Aspirated']}],
  'CompatibilityNotes': 'Hatchback, Location : Passenger Side -- For 4Cyl 2.0L 2013-2014 Ford Focus Headlight Lamp Head light'},
 {'NameValueList': [{'Value': []},
   {'Name': 'Year', 'Value': ['2013']},
   {'Name': 'Make', 'Value': ['Ford']},
   {'Name': 'Model', 'Value': ['Focus']},
   {'Name': 'Trim', 'Value': ['Titanium Sedan 4-Door']},
   {'Name': 'Engine',
    'Value': ['2.0L 1999CC 122Cu. In. l4 FLEX DOHC Naturally Aspirated']}],
  'CompatibilityNotes': 'Sedan, Location : Passenger Side -- For 4Cyl 2.0L 2012-2014 Ford Focus Headlight Lamp Head light'},
 {'NameValueList': [{'Value': []},
   {'Name': 'Year', 'Value': ['2013']},
   {'Name': 'Make', 'Value': ['Ford']},
   {'Name': 'Model', 'Value': ['Focus']},
   {'Name': 'Trim', 'Value': ['Titanium Sedan 4-Door']},
   {'Name': 'Engine',
    'Value': ['2.0L 1999CC 122Cu. In. l4 GAS DOHC Naturally Aspirated']}],
  'CompatibilityNotes': 'Sedan, Location : Passenger Side -- For 4Cyl 2.0L 2013-2014 Ford Focus Headlight Lamp Head light'},
 {'NameValueList': [{'Value': []},
   {'Name': 'Year', 'Value': ['2012']},
   {'Name': 'Make', 'Value': ['Ford']},
   {'Name': 'Model', 'Value': ['Focus']},
   {'Name': 'Trim', 'Value': ['Titanium Hatchback 4-Door']},
   {'Name': 'Engine',
    'Value': ['2.0L 1999CC 122Cu. In. l4 FLEX DOHC Naturally Aspirated']}],
  'CompatibilityNotes': 'Hatchback, Location : Passenger Side -- For 4Cyl 2.0L 2012-2014 Ford Focus Headlight Lamp Head light'},
 {'NameValueList': [{'Value': []},
   {'Name': 'Year', 'Value': ['2012']},
   {'Name': 'Make', 'Value': ['Ford']},
   {'Name': 'Model', 'Value': ['Focus']},
   {'Name': 'Trim', 'Value': ['Titanium Sedan 4-Door']},
   {'Name': 'Engine',
    'Value': ['2.0L 1999CC 122Cu. In. l4 FLEX DOHC Naturally Aspirated']}],
  'CompatibilityNotes': 'Sedan, Location : Passenger Side -- For 4Cyl 2.0L 2012-2014 Ford Focus Headlight Lamp Head light'}]

In [12]:
dict_vehicle = {}
for list_name_value in vehicle:
    make = ''
    model = ''
    year = ''
    for name_value in list_name_value['NameValueList']:
        if 'Name' in name_value and 'Make' in name_value['Name']:
            make = name_value['Value'][0]
        elif 'Name' in name_value and 'Model' in name_value['Name']:
            model = name_value['Value'][0]
        elif 'Name' in name_value and 'Year' in name_value['Name']:
            year = name_value['Value'][0]
            
    if make not in dict_vehicle:
        dict_vehicle[make] = {model: [year]}
    else:
        if model not in dict_vehicle[make]:
            dict_vehicle[make][model] = [year]
        else:
            dict_vehicle[make][model].append(year)
            
list_vehicle = []
for make in dict_vehicle:
    for model in dict_vehicle[make]:
        list_vehicle.append(make + ' ' + model + ' ' + min(dict_vehicle[make][model]) + '-' + max(dict_vehicle[make][model]))
        
vehicle = '\n'.join(list_vehicle)

print(vehicle)

Ford Focus 2012-2014

In [13]:
# Item.GalleryURL - None
if 'GalleryURL' in info['Item']:
    src = info['Item']['GalleryURL']
elif 'PictureURL' in info['Item']:
    if len(info['Item']['PictureURL']) == 0:
        src = ''
    else:
        src = info['Item']['PictureURL'][0]
        
src

'https://i.ebayimg.com/00/s/MTQwMFgxNDAw/z/~WgAAOSwLghksHjq/$_1.JPG?set_id=880000500F'

In [14]:
# Item.ItemSpecifics - ItemSpecifics
if 'ItemSpecifics' in info['Item']:
    details = info['Item']['ItemSpecifics']['NameValueList']
else:
    details = ''
    
details

[{'Name': 'Brand', 'Value': ['Perfect Fit']},
 {'Name': 'California Prop 65 Warning',
  'Value': ['<p><b>WARNING: This product can expose you to chemicals including']},
 {'Name': 'Certifications', 'Value': ['CAPA']},
 {'Name': 'Features', 'Value': ['Composite Design', 'CAPA Certified']},
 {'Name': 'Fitment Type', 'Value': ['Direct Replacement']},
 {'Name': 'Housing Color', 'Value': ['OE comparable']},
 {'Name': 'Interchange Part Number',
  'Value': ['BM5Z13008H-PFM',
   '2014 2013 2012',
   'Ford',
   'Focus',
   'Hatchback',
   'Sedan',
   'Passenger Right Side 4Cyl',
   '2.0L',
   'Titanium ST',
   'Headlight']},
 {'Name': 'Items Included', 'Value': ['With bulb(s)']},
 {'Name': 'Lighting Technology', 'Value': ['Halogen']},
 {'Name': 'Manufacturer Part Number', 'Value': ['16572425']},
 {'Name': 'Manufacturer Warranty',
  'Value': ['1-year unlimited-mileage warranty']},
 {'Name': 'OE Number', 'Value': ['BM5Z13008H-PFM']},
 {'Name': 'OE/OEM Part Number', 'Value': ['BM5Z13008H-PFM']},
 {'Name': 'Part Name', 'Value': ['Headlight']},
 {'Name': 'Performance Part', 'Value': ['No']},
 {'Name': 'Placement on Vehicle', 'Value': ['Right']},
 {'Name': 'Quantity', 'Value': ['Sold individually']},
 {'Name': 'Returns Policy', 'Value': ['60-Day Return Policy']},
 {'Name': 'Superseded Part Number',
  'Value': ['BM5Z13008H-PFM',
   '2014 2013 2012',
   'Ford',
   'Focus',
   'Hatchback',
   'Sedan',
   'Passenger Right Side 4Cyl',
   '2.0L',
   'Titanium ST',
   'Headlight']},
 {'Name': 'Type', 'Value': ['Headlight']},
 {'Name': 'Universal Fitment', 'Value': ['No']},
 {'Name': 'UPC', 'Value': ['723650317075']}]

In [15]:
df_temp = pd.DataFrame([{'Item_Number': list_item[i],
                         'Title': title,
                         'Price': price,
                         'Sold': sold,
                         'Vehicle': vehicle,
                         'Src': src,
                         'status': 'ok'}])

df_temp

,Item_Number,Title,Price,Sold,Vehicle,Src,status
0,373651381733,Headlight For 2012 2013 2014 Ford Focus Hatchb...,USD 160.86,0,Ford Focus 2012-2014,https://i.ebayimg.com/00/s/MTQwMFgxNDAw/z/~WgA...,ok

In [16]:
for name_value in details:
    df_temp[name_value['Name'].lower()] = ';'.join(name_value['Value'])
    
df = pd.concat([df, df_temp], ignore_index=True).fillna('')

df

,Item_Number,Title,Price,Sold,Vehicle,Src,status,brand,california prop 65 warning,certifications,...,oe/oem part number,part name,performance part,placement on vehicle,quantity,returns policy,superseded part number,type,universal fitment,upc
0,373651381733,Headlight For 2012 2013 2014 Ford Focus Hatchb...,USD 160.86,0,Ford Focus 2012-2014,https://i.ebayimg.com/00/s/MTQwMFgxNDAw/z/~WgA...,ok,Perfect Fit,<p><b>WARNING: This product can expose you to ...,CAPA,...,BM5Z13008H-PFM,Headlight,No,Right,Sold individually,60-Day Return Policy,BM5Z13008H-PFM;2014 2013 2012;Ford;Focus;Hatch...,Headlight,No,723650317075