In [1]:
import os
list_file = list(os.walk(r'C:\Users\YangTeng\Downloads\爬虫\爬\MAF\CARDONE'))[0][2]
if '.DS_Store' in list_file:
   list_file.remove('.DS_Store')

len(list_file)

47

In [2]:
import pandas as pd
df = pd.DataFrame(columns=['Title', 'Vehicle', 'Url'])

df

Empty DataFrame
Columns: [Title, Vehicle, Url]
Index: []

In [3]:
import json
for file in list_file:
    print(file)
    with open('C:/Users/YangTeng/Downloads/爬虫/爬/MAF/CARDONE/' + file) as f:
        list_part = f.read()[1:-1].split('},{')
        for i in range(len(list_part)):
            if i == 0:
                part = json.loads(list_part[i] + '}')
            elif i == len(list_part) - 1:
                part = json.loads('{' + list_part[i])
            else:
                part = json.loads('{' + list_part[i] + '}')
                
            df_temp = pd.DataFrame([{'Title': part['Title'],
                                     'Vehicle': part['Vehicle'],
                                     'Url': part['Url']}])
            df = pd.concat([df, df_temp], ignore_index=True)

www.cardone.com_search.php_page=10&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=11&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=12&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=13&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=14&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=15&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=16&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=17&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=18&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=19&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=2&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=20&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=21&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=22&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=23&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=24&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=25&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=26&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=27&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=28&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=29&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=3&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=30&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=31&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=32&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=33&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=34&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=35&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=36&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=37&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=38&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=39&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=4&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=40&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=41&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=42&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=43&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=44&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=45&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=46&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s (1).txt
www.cardone.com_search.php_page=46&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=5&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=6&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=7&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=8&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_page=9&section=product&search_query=%22Air+Flow+Sensor%22&f=Air+Flow+Sensor&sort=alphaasc&type=p&search=s.txt
www.cardone.com_search.php_section=product&search_query=%22Air%20Flow%20Sensor%22&f=Air%20Flow%20Sensor&sort=alphaasc&type=p&search=s.txt

In [4]:
df.to_excel(r'C:\Users\YangTeng\Desktop\MAF\CARDONR.xlsx', index=False)

df

,Title,Vehicle,Url
0,Mass Air Flow Sensor - 74-10129,,https://www.cardone.com/product/mass-air-flow-...
1,Mass Air Flow Sensor - 74-10131,,https://www.cardone.com/product/mass-air-flow-...
2,Mass Air Flow Sensor - 74-10132,,https://www.cardone.com/product/mass-air-flow-...
3,Mass Air Flow Sensor - 74-10133,,https://www.cardone.com/product/mass-air-flow-...
4,Mass Air Flow Sensor - 74-10134,,https://www.cardone.com/product/mass-air-flow-...
...,...,...,...
559,Mass Air Flow Sensor - 74-10011,,https://www.cardone.com/product/mass-air-flow-...
560,Mass Air Flow Sensor - 74-10012,,https://www.cardone.com/product/mass-air-flow-...
561,Mass Air Flow Sensor - 74-10013,,https://www.cardone.com/product/mass-air-flow-...
562,Mass Air Flow Sensor - 74-10014,,https://www.cardone.com/product/mass-air-flow-...
563,Mass Air Flow Sensor - 74-10015,,https://www.cardone.com/product/mass-air-flow-...