In [2]:
import pandas as pd
df_menu = pd.read_excel(r'C:\Users\YangTeng\Downloads\爬虫\cardone-brake caliper\menu.xlsx', header=0)
list_url = df_menu['Url'].to_list()

print('总数量：' + str(len(list_url)))
list_url

总数量：9239

In [3]:
df = pd.DataFrame(columns=['Url',
                           'Part_Number',
                           'Src',
                           'status'])

df

Empty DataFrame
Columns: [Url, Part_Number, Src, status]
Index: []

In [5]:
import requests
i = 1

resp = requests.get(list_url[i]).text

resp

ProxyError: HTTPSConnectionPool(host='uacparts.com', port=443): Max retries exceeded with url: /Catalog/CrossReference?__aweconid=CRP6&part=CO%2020067C (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 449 Foreign Host Forbidden')))

In [14]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(resp, 'lxml')

print(soup.prettify())

<!DOCTYPE html>
<html class="no-js" lang="en">
 <head>
  <title>
   Brake Caliper - 18-4003
  </title>
  <link crossorigin="" href="https://cdn11.bigcommerce.com/s-z9vhe3o238" rel="dns-prefetch preconnect"/>
  <link crossorigin="" href="https://fonts.googleapis.com/" rel="dns-prefetch preconnect"/>
  <link crossorigin="" href="https://fonts.gstatic.com/" rel="dns-prefetch preconnect"/>
  <meta content="0" property="product:price:amount"/>
  <meta content="USD" property="product:price:currency"/>
  <meta content="https://www.cardone.com/product/unloaded-caliper-18-4003" property="og:url"/>
  <meta content="CARDONE Industries" property="og:site_name"/>
  <meta content="CARDONE Reman,Brake Caliper,Chevrolet Chevette 1979-78; Pontiac Acadian 1979-78" name="description"/>
  <link href="https://www.cardone.com/product/unloaded-caliper-18-4003" rel="canonical"/>
  <meta content="bigcommerce.stencil" name="platform"/>
  <meta content="product" property="og:type"/>
  <meta content="Brake Caliper - 18-4003" property="og:title"/>
  <meta content="CARDONE Reman,Brake Caliper,Chevrolet Chevette 1979-78; Pontiac Acadian 1979-78" property="og:description"/>
  <meta content="https://cdn11.bigcommerce.com/s-z9vhe3o238/products/54530/images/5514290/482__86004.1687987719.386.513.jpg?c=1" property="og:image"/>
  <meta content="disabled" property="pinterest:richpins"/>
  <style>
   .stickyBody {
        padding-top: 147px;
    }
    @media only screen and (max-width: 800px) {
        .stickyBody {
            padding-top: 120px;
        }
    }
    @media only screen and (max-width: 550px) {
        .stickyBody {
            padding-top: 99px;
        }
    }
  </style>
  <style>
   .productView-price {
        display: none!important;
    }
    .stickyBody .productView-description {
        margin-top: 4.8rem !important;
    }
    .productView .productView-images {
        margin-bottom: 0!important;
    }
    .productView .productView-details.productView-details--header {
        grid-row: 1!important;
    }
    .productView .productView-details {
        grid-row: 2!important;
    }
    @media only screen and (min-width: 1261px) {
        .stickyBody .productView-description {
            margin-top: 8.8rem !important;
        }
    }
  </style>
  <link href="https://cdn11.bigcommerce.com/s-z9vhe3o238/product_images/CARDONE-CMark.png?t=1645211120" rel="shortcut icon"/>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport"/>
  <meta content="Camden B2B" name="ft-name"/>
  <meta content="1.7.3" name="ft-version"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js">
  </script>
  <script>
   // Change document class from no-js to js so we can detect this in css
            document.documentElement.className = document.documentElement.className.replace('no-js', 'js');
  </script>
  <script>
   window.lazySizesConfig = window.lazySizesConfig || {};
            window.lazySizesConfig.loadMode = 1;
  </script>
  <script async="" src="https://cdn11.bigcommerce.com/s-z9vhe3o238/stencil/033eb870-fd2a-013b-d35b-0e32ab8fdfb1/e/57ce0840-297e-013c-53e7-767c56c8428d/dist/theme-bundle.head_async.js">
  </script>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:600,400&amp;display=swap" rel="stylesheet"/>
  <link data-stencil-stylesheet="" href="https://cdn11.bigcommerce.com/s-z9vhe3o238/stencil/033eb870-fd2a-013b-d35b-0e32ab8fdfb1/e/57ce0840-297e-013c-53e7-767c56c8428d/css/theme-72538df0-2a31-013c-53e7-767c56c8428d.css" rel="stylesheet"/>
  <style>
   .DisplayNoneCompare {
              display: none!important;
          }
          .right:before {
            display: none!important;
        }
        @media only screen and (max-width: 800px){
          .HeaderTopMobile .right a:last-child:before {
              padding: 5.5px 3px 0.35px 4px !important;
          }
          .HeaderTopMobile i:after {
              padding: 10px 3px 0.5px 11px !important;
          }
        }
  </style>
  <!-- Start Tracking Code for analytics_googleanalytics4 -->
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async="" data-bc-cookie-consent="3" src="https://www.googletagmanager.com/gtag/js?id=G-CGRGM8KGNX" type="text/plain">
  </script>
  <script data-bc-cookie-consent="3" src="/app/assets/js/google_analytics4.js" type="text/plain">
  </script>
  <script data-bc-cookie-consent="3" type="text/plain">
   function initGA4() {
    if (typeof subscribeOnBodlEvents === 'function') {
      subscribeOnBodlEvents('G-CGRGM8KGNX', 'dMjk3Nj');

      return true;
    }

    return false;
  }

  var eventName = document.readyState === 'complete' ? 'consentScriptsLoaded' : 'DOMContentLoaded';
  window.addEventListener(eventName, initGA4, false);
  </script>
  <!-- End Tracking Code for analytics_googleanalytics4 -->
  <script type="text/javascript">
   (function () {
    var xmlHttp = new XMLHttpRequest();

    xmlHttp.open('POST', 'https://bes.gcp.data.bigcommerce.com/nobot');
    xmlHttp.setRequestHeader('Content-Type', 'application/json');
    xmlHttp.send('{"store_id":"1002203534","timezone_offset":"-4","timestamp":"2023-09-04T07:08:10.66911000Z","visit_id":"705b31aa-607d-4924-9410-29d55720d051","channel_id":1}');
})();
  </script>
  <script async="" defer="" src="https://www.google.com/recaptcha/api.js">
  </script>
  <script>
   window.consentManagerStoreConfig = function () { return {"storeName":"CARDONE Industries","privacyPolicyUrl":"https:\/\/www.cardone.com\/privacy-policy\/","writeKey":null,"improvedConsentManagerEnabled":true}; };
  </script>
  <script defer="" src="https://cdn11.bigcommerce.com/shared/js/storefront/consent-manager-config-b7e506e311fc3d0837884c9e76dd5851852a6317.js" type="text/javascript">
  </script>
  <script defer="" src="https://cdn11.bigcommerce.com/shared/js/storefront/consent-manager-08633fe15aba542118c03f6d45457262fa9fac88.js" type="text/javascript">
  </script>
  <script type="text/javascript">
   var BCData = {"csrf_token":"affa891ec205df1172c9c55a03e612e173c50c6d4ce40f96fac0813801c75243","product_attributes":{"sku":"18-4003","upc":"00082617010498","mpn":"18-4003","gtin":"00082617010498","weight":null,"base":true,"image":null,"price":{"without_tax":{"formatted":"$0.00","value":0,"currency":"USD"},"tax_label":"Tax"},"out_of_stock_behavior":"label_option","out_of_stock_message":"Out of Stock","available_modifier_values":[],"in_stock_attributes":[],"stock":0,"instock":false,"stock_message":"Out of Stock","purchasable":true,"purchasing_message":"The selected product combination is currently unavailable."}};
  </script>
  <script data-bc-cookie-consent="3" type="text/plain">
   (function(c,l,a,r,i,t,y){
        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
    })(window, document, "clarity", "script", "ebrplbsz6c");
  </script>
  <!-- Google Tag Manager -->
  <script data-bc-cookie-consent="3" type="text/plain">
   (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PMVCPDH');
  </script>
  <!-- End Google Tag Manager -->
  <script src="https://microapps.bigcommerce.com/bodl-events/index.js">
  </script>
  <script>
   window.bodl = JSON.parse("{\"session\":{\"id\":\"6edf1b12-4568-473b-8421-de9fe4809af3\",\"first_touch_timestamp\":\"2023-09-04T07:08:10\",\"first_touch_referral_url\":\"\",\"first_touch_request_url\":\"https://www.cardone.com/product/unloaded-caliper-18-4003\"},\"shopper\":{\"visitor_id\":\"\",\"customer_id\":null,\"email\":null,\"first_name\":null,\"last_name\":null},\"data_consent\":{\"functional\":false,\"analytics\":false,\"advertising\":false},\"events\":[{\"bodl_v1_product_page_viewed\":{\"event_id\":\"416c02f1-a2c7-42f0-a8c0-279513c23338\",\"channel_id\":1,\"currency\":\"USD\",\"product_value\":0.0,\"line_items\":[{\"product_id\":\"54530\",\"sku\":\"18-4003\",\"variant_id\":null,\"product_name\":\"Brake Caliper - 18-4003\",\"gift_certificate_id\":null,\"gift_certificate_name\":null,\"gift_certificate_theme\":null,\"purchase_price\":0.0,\"sale_price\":null,\"base_price\":null,\"retail_price\":null,\"quantity\":null,\"discount\":null,\"index\":0,\"brand_name\":\"CARDONE Reman\",\"category_names\":[\"Brakes\"],\"currency\":\"USD\"}]}}]}");
  </script>
  <!-- snippet location htmlhead -->
 </head>
 <body>
  <!-- snippet location header -->
  <svg class="icons-svg-sprite" data-src="https://cdn11.bigcommerce.com/s-z9vhe3o238/stencil/033eb870-fd2a-013b-d35b-0e32ab8fdfb1/e/57ce0840-297e-013c-53e7-767c56c8428d/img/icon-sprite.svg">
  </svg>
  <div data-content-region="above_header_banner--global">
  </div>
  <div data-content-region="above_header_banner">
  </div>
  <!--<div data-content-region="above_header--global"><div data-layout-id="f2c9bb93-00c1-4211-9338-f2d1e306e60b"><div data-sub-layout-container="741a01fe-3c81-4643-9e2e-ca20d3a917de" data-layout-name="Layout">
  <style data-container-styling="741a01fe-3c81-4643-9e2e-ca20d3a917de">
    [data-sub-layout-container="741a01fe-3c81-4643-9e2e-ca20d3a917de"] {
      box-sizing: border-box;
      display: flex;
      flex-wrap: wrap;
      z-index: 0;
      position: relative;
    }
    [data-sub-layout-container="741a01fe-3c81-4643-9e2e-ca20d3a917de"]:after {
      background-position: center center;
      background-size: cover;
      z-index: auto content: "";
      display: block;
      position: absolute;
      top: 0;
      left: 0;
      bottom: 0;
      right: 0;
    }
  </style>
  <div data-sub-layout="cefa0b57-3d88-4d4d-9701-d824405fa4e5">
    <style data-column-styling="cefa0b57-3d88-4d4d-9701-d824405fa4e5">
      [data-sub-layout="cefa0b57-3d88-4d4d-9701-d824405fa4e5"] {
        display: flex;
        flex-direction: column;
        box-sizing: border-box;
        flex-basis: 100%;
        max-width: 100%;
        z-index: 0;
        justify-content: center;
        position: relative;
      }
      [data-sub-layout="cefa0b57-3d88-4d4d-9701-d824405fa4e5"]:after {
        background-position: center center;
        background-size: cover;
        z-index: auto content: "";
        display: block;
        position: absolute;
        top: 0;
        left: 0;
        bottom: 0;
        right: 0;
      }
      @media only screen and (max-width: 700px) {
        [data-sub-layout="cefa0b57-3d88-4d4d-9701-d824405fa4e5"] {
          flex-basis: 100%;
          max-width: 100%;
        }
      }
    </style>
    <div data-widget-id="44b57949-cf87-4f50-b30b-214884e0b457" data-placement-id="cab251a6-1ba7-4575-86ca-9f9e84fac9fb" data-placement-status="ACTIVE"><div class="RedTopBanner">
  Are you a current MyCARDONE customer? <a href="https://my.cardone.com/English/Club/login.asp" target="_blank">Login Here</a>
</div>
</div>
  </div>
</div></div></div>-->
  <div class="RedTopBanner">
   Customers: The transition from
   <a href="https://my.cardone.com/English/Club/login.asp" target="_blank">
    MyCARDONE
   </a>
   to the new CARDONE.com is underway. Watch your email!
  </div>
  <div data-content-region="above_header">
  </div>
  <header class="header header--gift-certificate-disabled header--no-margin" id="menu" role="banner">
   <div class="container">
    <div class="HeaderTop">
     <!--
        <div class="sku-add sku-add--sku">
    <form class="form js-quick-add" action="/cart.php" method="post" enctype="multipart/form-data" data-error="Please complete the SKU and quantity fields">
    <div class="add-sku-item"></div>
        <fieldset class="form-fieldset">
            <div class="form-field">
                <div class="form-input-wrap">
                    <input class="form-input form-input--sku-num" name="sku" type="text" placeholder="Add SKU to Cart" data-sku autocorrect="off">
                    <input class="form-input form-input--sku-qty" name="qty" type="tel" value="1" min="1" data-qty autocomplete="off">
                </div>
                <span class="quick-add-result"></span>
                <button type="submit" class="search-button" type="submit">Add to Cart</button>
            </div>
        </fieldset>
    </form>
</div>
    -->
    </div>
    <div class="HeaderTopMobile HeaderMobileNotLoggedIn">
     <div class="left">
      <a href="/locations/">
       <i aria-hidden="true" class="fa fa-map-marker">
       </i>
      </a>
      <a href="/contact-us/">
       <i aria-hidden="true" class="fa fa-phone">
       </i>
      </a>
     </div>
     <div class="right">
      <a href="/account.php">
       <i aria-hidden="true" class="fa fa-user">
       </i>
      </a>
     </div>
    </div>
    <div class="header__inner">
     <a class="mobileMenu-toggle" data-mobile-menu-toggle="menu" href="#">
      <span class="mobileMenu-toggleIcon">
       Toggle menu
      </span>
     </a>
     <div class="header-logo header-logo--image header-logo--center">
      <a href="https://www.cardone.com/">
       <span class="header-logo-text">
        <img alt="CARDONE Industries" class="header-logo-image" src="https://cdn11.bigcommerce.com/s-z9vhe3o238/images/stencil/200x150/cardone-logo-notag_1653082481__21641.original.jpg" title="CARDONE Industries"/>
       </span>
      </a>
     </div>
     <div class="header__bottom-nav">
      <div class="header__bottom-nav-inner">
       <div class="navPages-container" data-menu="" id="menu">
        <nav class="navPages" data-options="">
         <ul class="navPages-list navPages-list-depth-max simple">
          <li class="navPages-item">
           <a class="navPages-action navPages-action-depth-max has-subMenu is-root" data-collapsible="navPages-44444" href="#!">
            Parts
            <i aria-hidden="true" class="icon navPages-action-moreIcon">
             <svg>
              <use xlink:href="#icon-chevron-down">
              </use>
             </svg>
            </i>
           </a>
           <div aria-hidden="true" class="navPage-subMenu navPage-subMenu-horizontal MainPartsMenu" id="navPages-44444" tabindex="-1">
            <ul class="navPage-subMenu-list">
             <li class="navPages-item">
              <a class="navPages-action navPages-action-depth-max has-subMenu is-root" data-collapsible="navPages-18" href="https://www.cardone.com/brakes/">
               Brakes
               <i aria-hidden="true" class="icon navPages-action-moreIcon">
                <svg>
                 <use xlink:href="#icon-chevron-down">
                 </use>
                </svg>
               </i>
              </a>
              <div aria-hidden="true" class="navPage-subMenu navPage-subMenu-horizontal" id="navPages-18" tabindex="-1">
               <ul class="navPage-subMenu-list">
                <li class="navPage-subMenu-item-parent">
                 <a class="navPage-subMenu-action navPages-action navPages-action-depth-max" href="https://www.cardone.com/brakes/">
                  All Brakes
                 </a>
                </li>
                <li class="navPage-subMenu-item-child">
                 <a class="NavPageSubMenu" href="https://www.cardone.com/brakes/abs-components/">
                  <img alt="ABS Components" class="DesktopNav" src="https://cdn11.bigcommerce.com/s-z9vhe3o238/images/stencil/original/d/apizovxov__58662.original.jpg" title="ABS Components"/>
                  <br/>
                  ABS Components
                  <i aria-hidden="true" class="icon navPages-action-moreIcon">
                   <svg>
                    <use xlink:href="#icon-chevron-down">
                    </use>
                   </svg>
                  </i>
                 </a>
                 <div aria-hidden="true" class="navPage-subMenu navPage-subMenu-horizontal" id="navPages-87" tabindex="-1">
                  <ul class="navPage-subMenu-list">
                   <li class="navPage-subMenu-item-parent">
                    <a class="navPage-subMenu-action navPages-action navPages-action-depth-max" href="https://www.cardone.com/brakes/abs-components/">
                     All ABS Components
                    </a>
                   </li>
                   <li class="navPage-subMenu-item-child">
                    <a class="navPage-subMenu-action navPages-action" href="https://www.cardone.com/brakes/abs-components/abs-control-module/">
                     ABS Control Module
                    </a>
                   </li>
                   <li class="navPage-subMenu-item-child">
                    <a class="navPage-subMenu-action navPages-action" href="https://www.cardone.com/brakes/abs-components/abs-hydraulic-assembly/">
                     ABS Hydraulic Assembly
                    </a>
                   </li>
                   <li class="navPage-subMenu-item-child">
                    <a class="navPage-subMenu-action navPages-action" href="https://www.cardone.com/brakes/abs-components/abs-pump-motor-assembly/">
                     ABS Pump &amp; Motor Assembly
                    </a>
                   </li>
                  </ul>
                 </div>
                </li>
                <li class="navPage-subMenu-item-child">
                 <a class="NavPageSubMenu" href="https://www.cardone.com/brakes/brake-boosters-pumps/">
                  <img alt="Brake Boosters &amp; Pumps" class="DesktopNav" src="https://cdn11.bigcommerce.com/s-z9vhe3o238/images/stencil/original/h/apibkivfj__54509.original.jpg" title="Brake Boosters &amp; Pumps"/>
                  <br/>
                  Brake Boosters &amp; Pumps
                  <i aria-hidden="true" class="icon navPages-action-moreIcon">
                   <svg>
                    <use xlink:href="#icon-chevron-down">
                    </use>
                   </svg>
                  </i>
                 </a>
                 <div aria-hidden="true" class="navPage-subMenu navPage-subMenu-horizontal" id="navPages-52" tabindex="-1">
                  <ul class="navPage-subMenu-list">
                   <li class="navPage-subMenu-item-parent">
                    <a class="navPage-subMenu-action navPages-action navPages-action-depth-max" href="https://www.cardone.com/brakes/brake-boosters-pumps/">
                     All Brake Boosters &amp; Pumps
                    </a>
                   </li>
                   <li class="navPage-subMenu-item-child">
                    <a class="navPage-subMenu-action navPages-action" href="https://www.cardone.com/brakes/brake-boosters-pumps/electronic-brake-assembly/">
                     Electronic Brake Assembly
                    </a>
                   </li>
                   <li class="navPage-subMenu-item-child">
                    <a class="navPage-subMenu-action navPages-action" href="https://www.cardone.com/brakes/brake-boosters-pumps/electronic-brake-booster-vacuum-pump/">
                     Electronic Brake Booster Vacuum Pump
                    </a>
                   </li>
                   <li class="navPage-subMenu-item-child">
                    <a class="navPage-subMenu-action navPages-action" href="https://www.cardone.com/brakes/brake-boosters-pumps/electronic-brake-pedal-simulator/">
                     Electronic Brake Pedal Simulator
                    </a>
                   </li>
                   <li class="navPage-subMenu-item-child">
                    <a class="navPage-subMenu-action navPages-action" href="https://www.cardone.com/brakes/brake-boosters-pumps/electronic-brake-pump-motor/">
                     Electronic Brake Pump &amp; Motor
                    </a>
                   </li>
                   <li class="navPage-subMenu-item-child">

In [15]:
from lxml import etree

html = etree.HTML(str(soup))

part_number = html.xpath('//dd[@data-product-sku]/text()')[0]

part_number

'18-4003'

In [16]:
src = html.xpath('//div[@class="productView-img-container"]/a/@href')[0]

src

'https://cdn11.bigcommerce.com/s-z9vhe3o238/images/stencil/1280x1280/products/54530/5514290/482__86004.1687987719.jpg?c=1'

In [17]:
df_temp = pd.DataFrame([{'Url': list_url[i],
                         'Part_Number': part_number,
                         'Src': src,
                         'status': 'ok'}])

df_temp

,Url,Part_Number,Src,status
0,https://www.cardone.com/product/unloaded-calip...,18-4003,https://cdn11.bigcommerce.com/s-z9vhe3o238/ima...,ok

In [18]:
list_general = html.xpath('//div[@class="productView-table general"]/div[@class="productView-table-row"]')

list_general

[<Element div at 0x199cedba300>,
 <Element div at 0x199cefd5c00>,
 <Element div at 0x199cefd5940>,
 <Element div at 0x199cefd60c0>,
 <Element div at 0x199cefd5a80>,
 <Element div at 0x199cefd4e00>,
 <Element div at 0x199cefd4600>,
 <Element div at 0x199cefd5880>]

In [9]:
for row in list_general:
    name = row.xpath('./div[@class="productView-table-header"]/text()')[0]
    if name.endswith(':'):
        name = name[:-1]
    value = row.xpath('./div[@class="productView-table-data"]/text()')[0]
    df_temp[name.lower()] = value
    
list_technical = html.xpath('//div[@class="productView-table technical"]/div[@class="productView-table-row"]')

list_technical

[<Element div at 0x19e78172580>,
 <Element div at 0x19e78173f80>,
 <Element div at 0x19e7815c680>,
 <Element div at 0x19e7815c800>,
 <Element div at 0x19e7815c880>,
 <Element div at 0x19e7815c900>,
 <Element div at 0x19e7815c940>,
 <Element div at 0x19e7815c9c0>,
 <Element div at 0x19e7815ca40>,
 <Element div at 0x19e7815c340>,
 <Element div at 0x19e7815ca00>]

In [10]:
for row in list_technical:
    name = row.xpath('./div[@class="productView-table-header"]/text()')[0]
    if name.endswith(':'):
        name = name[:-1]
    value = row.xpath('./div[@class="productView-table-data"]/text()')[0]
    df_temp[name.lower()] = value
    
df = pd.concat([df, df_temp], ignore_index=True).fillna('')

df

,Url,Part_Number,Src,status,part type,product condition,lifecycle status,package contents,packaged weight,upc,...,color,finish,inlet port size,installation hardware included,mounting bolts included,pads included,piston material,piston quantity,piston size od - imperial,piston size od - metric
0,https://www.cardone.com/product/unloaded-calip...,18-4003,https://cdn11.bigcommerce.com/s-z9vhe3o238/ima...,ok,Brake Caliper,Remanufactured,Available to Order,Caliper; Instruction Sheet; Hardware Kit,4.4900 lb,00082617010498,...,Gray,Powder Coated,0.39,Yes,Yes,No,Steel,1,1.87 in,47.52 mm