In [1]:
import os

In [2]:
list_file = list(os.walk('C:/Users/YangTeng/Downloads/爬虫/爬/MAF/CARDONE/OE'))[0][2]
if '.DS_Store' in list_file:
   list_file.remove('.DS_Store')

len(list_file)

565

In [3]:
import pandas as pd

In [4]:
df = pd.DataFrame(columns=['Part_Number', 'OE_Numbers'])

df

Empty DataFrame
Columns: [Part_Number, OE_Numbers]
Index: []

In [5]:
import json

In [6]:
for file in list_file:
    print(file)
    with open('C:/Users/YangTeng/Downloads/爬虫/爬/MAF/CARDONE/OE/' + file,'rb') as f:
        part = json.loads(f.read()[1:-1])
                
        df_temp = pd.DataFrame([{'Part_Number': part['Part_Number'],
                                 'OE_Numbers': part['OE_Numbers']}])
        df = pd.concat([df, df_temp], ignore_index=True)

productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10000&index=545.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10001&index=547.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10002&index=558.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10003&index=549.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10004&index=555.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10005&index=559.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10010&index=552.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10011&index=554.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10012&index=562.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10013&index=553.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10014&index=563.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10015&index=557.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10016&index=119.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10017&index=163.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10018&index=122.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10019&index=116.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10020&index=115.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10021&index=124.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10022&index=126.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10023&index=123.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10024&index=132.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10033&index=125.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10034&index=127.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10035&index=129.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10037&index=247.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10038&index=249.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10039&index=250.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10040&index=251.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10041&index=256.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10042&index=252.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10043&index=254.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10044&index=265.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10045&index=264.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10046&index=257.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10047&index=258.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10048&index=259.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10049&index=383.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10050&index=384.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10051&index=382.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10052&index=386.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10053&index=387.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10054&index=398.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10055&index=395.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10056&index=388.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10057&index=393.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10058&index=396.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10059&index=391.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10060&index=389.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10061&index=504.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10062&index=486.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10063&index=488.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10064&index=496.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10065&index=505.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10066&index=490.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10068&index=514.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10069&index=493.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10070&index=500.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10072&index=495.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10073&index=499.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10074&index=506.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10075&index=507.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10076&index=518.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10077&index=498.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10078&index=516.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10079&index=502.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10080&index=501.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10081&index=503.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10082&index=508.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10083&index=510.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10084&index=509.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10086&index=522.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10087&index=520.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10088&index=517.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10089&index=526.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10090&index=511.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10091&index=530.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10092&index=512.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10093&index=513.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10094&index=523.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10095&index=515.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10098&index=525.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10099&index=519.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10100&index=521.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10101&index=528.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10103&index=541.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10104&index=529.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10105&index=524.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10106&index=537.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10108&index=539.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10109&index=546.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10110&index=527.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10111&index=534.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10112&index=560.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10113&index=531.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10114&index=533.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10115&index=532.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10116&index=540.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10117&index=536.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10118&index=535.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10119&index=543.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10120&index=538.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10121&index=548.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10122&index=561.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10123&index=542.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10124&index=544.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10125&index=550.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10126&index=551.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10128&index=556.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10129&index=5.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10131&index=4.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10132&index=6.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10133&index=15.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10134&index=7.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10135&index=0.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10135.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10137&index=2.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10138&index=1.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10139&index=17.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10140&index=3.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10143&index=8.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10146&index=9.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10147&index=12.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10152&index=11.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10154&index=10.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10156&index=14.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10157&index=13.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10158&index=18.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10159&index=19.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10160&index=16.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10161&index=21.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10163&index=23.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10164&index=20.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10165&index=26.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10166&index=29.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10167&index=22.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10168&index=27.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10171&index=25.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10172&index=24.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10174&index=28.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10203&index=35.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10204&index=30.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10213&index=32.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10244&index=31.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10246&index=34.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10248&index=40.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10249&index=33.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10253&index=38.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10256&index=36.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10260&index=39.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10261&index=37.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10262&index=47.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10263&index=41.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10274&index=73.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10275&index=44.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10278&index=42.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10280&index=43.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10281&index=46.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10282&index=48.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-10283&index=45.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-1243&index=49.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-20000&index=52.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-20001&index=51.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-20002&index=50.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-20003&index=54.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-20004&index=53.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-20006&index=57.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-20008&index=58.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-20010&index=55.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-20012&index=85.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-20014&index=56.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-20016&index=66.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-20020&index=59.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-20021&index=60.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-20022&index=61.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-20025&index=67.txt
productdesk-api.cellacore.net_legacy_cardone_FinishedGood__q=productDeskItemNumber.keyword_74-20028&index=62.txt

In [7]:
df.to_excel(r'C:\Users\YangTeng\Desktop\MAF\CARDONR-detail-oe.xlsx', index=False)

df

    Part_Number                                         OE_Numbers
0      74-10000  2268016E10;2268032F00;2268042E00;A36000E20;A36...
1      74-10001                               2268043E00;A36000N03
2      74-10002  2268009P00;2268024P00;A36000007;A36000014;A360...
3      74-10003                               2268025P00;A36000N12
4      74-10004               0280212002;1326065;13260658;53266454
..          ...                                                ...
560     86-9933                        3L7Z12B579AA;3L7Z12B579AARM
561     86-9936                                         22680CA000
562     86-9936                                         22680CA000
563     86-9937                                         226802J200
564     86-9937                                         226802J200

[565 rows x 2 columns]